import { courseLevels, courseStats, levelLessons, type CefrLevel } from '../learning/curriculum';
import { languageByCode } from '../data/catalog';
import type { CourseState } from '../learning/course-state';
import type { PlatformProgress } from '../learning/progress';
import type { Lesson } from '../learning/types';
import './course-view.css';

type Props={progress:PlatformProgress;courseState:CourseState;targetLanguage:string;onSelectLevel:(level:CefrLevel)=>void;openLesson:(lesson:Lesson)=>void;openPlacement:()=>void};
function levelProgress(level:CefrLevel,progress:PlatformProgress,targetLanguage:string){const lessons=levelLessons(level,targetLanguage);const done=lessons.filter(lesson=>progress.completedLessonIds.includes(lesson.id)).length;return{done,total:lessons.length,percent:lessons.length?Math.round(done/lessons.length*100):0};}

export default function CourseView({progress,courseState,targetLanguage,onSelectLevel,openLesson,openPlacement}:Props){
  const stats=courseStats(targetLanguage),levels=courseLevels(targetLanguage),language=languageByCode(targetLanguage),fullEnglish=targetLanguage==='en';
  const courseRange=levels.length>1?`${levels[0].id}–${levels[levels.length-1].id}`:(levels[0]?.id||courseState.activeLevel);
  return <section className="course-hub platform-view"><div className="course-hub-hero"><div><span className="eyebrow">{language.name.toUpperCase()} · {courseRange}</span><h1>{fullEnglish?'Ein klarer Lernpfad für jede Stufe.':`${language.name} Schritt für Schritt aufbauen.`}</h1><p>{fullEnglish?'Wähle dein aktuelles Niveau selbst oder nutze die Einstufung als Orientierung. Jede Stufe verbindet Wortschatz, Grammatik, Hören, Sprechen und aktive Anwendung.':`Der aktuelle ${language.name}-Lernpfad deckt ${courseRange} ab und führt dich durch alltagsnahe Situationen, Hörverstehen und aktive Sprachproduktion. Dein Fortschritt bleibt beim Wechsel zwischen Stufen erhalten.`}</p><div className="course-hub-actions">{fullEnglish&&<button className="view-primary" onClick={openPlacement}>Niveau bestimmen →</button>}<button className="course-ghost" onClick={()=>openLesson(levelLessons(courseState.activeLevel,targetLanguage)[0])}>Im aktuellen Level weiterlernen</button></div></div><div className="course-stat-cluster"><article><strong>{stats.levels}</strong><span>Stufen</span></article><article><strong>{stats.units}</strong><span>Lernblöcke</span></article><article><strong>{stats.lessons}</strong><span>Lektionen</span></article><article><strong>{stats.exercises}</strong><span>Aufgaben</span></article></div></div>
  {fullEnglish&&courseState.placement&&<div className="placement-summary"><div><span className="eyebrow">LETZTE EINSTUFUNG</span><strong>{courseState.placement.recommendedLevel}</strong><p>{courseState.placement.score}/{courseState.placement.total} Aufgaben richtig</p>{courseState.placement.focus?.[0]&&<small>Nächster Fokus: {courseState.placement.focus[0]}</small>}</div><button onClick={openPlacement}>Neu einstufen</button></div>}
  <div className="course-levels">{levels.map(level=>{const lp=levelProgress(level.id,progress,targetLanguage),active=level.id===courseState.activeLevel,all=level.units.flatMap(unit=>unit.lessons),firstOpen=all.find(lesson=>!progress.completedLessonIds.includes(lesson.id))??all[0];return <article key={level.id} className={`course-level-card ${active?'active':''}`}><div className="course-level-side"><div className="course-level-badge">{level.id}</div><span>{active?'AKTIV':'STUFE'}</span></div><div className="course-level-main"><div className="course-level-title"><div><span>{level.descriptor}</span><h2>{level.title}</h2></div><div className="course-level-progress"><strong>{lp.percent}%</strong><small>{lp.done}/{lp.total} Lektionen</small></div></div><p className="course-level-goal">{level.goal}</p><div className="course-unit-grid">{level.units.map(unit=>{const done=unit.lessons.filter(lesson=>progress.completedLessonIds.includes(lesson.id)).length;return <div key={unit.id} className="course-unit-mini"><div><span>UNIT {unit.number}</span><strong>{unit.title}</strong></div><small>{done}/{unit.lessons.length} · {unit.subtitle}</small></div>})}</div><div className="course-level-actions"><button className="course-select" onClick={()=>onSelectLevel(level.id)}>{active?'Aktuelles Level':`${level.id} auswählen`}</button><button className="course-start" onClick={()=>{onSelectLevel(level.id);openLesson(firstOpen)}}>Lektion starten →</button></div></div></article>})}</div></section>;
}
