import { courseLevels, courseStats, levelLessons, type CefrLevel } from '../learning/curriculum';
import { languageByCode } from '../data/catalog';
import type { CourseState } from '../learning/course-state';
import type { PlatformProgress } from '../learning/progress';
import type { Lesson } from '../learning/types';
import './course-view.css';

type Props={progress:PlatformProgress;courseState:CourseState;targetLanguage:string;onSelectLevel:(level:CefrLevel)=>void;openLesson:(lesson:Lesson)=>void;openPlacement:()=>void};
function levelProgress(level:CefrLevel,progress:PlatformProgress,targetLanguage:string){const lessons=levelLessons(level,targetLanguage);const done=lessons.filter(lesson=>progress.completedLessonIds.includes(lesson.id)).length;return{done,total:lessons.length,percent:lessons.length?Math.round(done/lessons.length*100):0};}

export default function CourseView({progress,courseState,targetLanguage,onSelectLevel,openLesson,openPlacement}:Props){
  const stats=courseStats(targetLanguage),levels=courseLevels(targetLanguage),language=languageByCode(targetLanguage),fullEnglish=targetLanguage==='en';
  return <section className="course-hub platform-view"><div className="course-hub-hero"><div><span className="eyebrow">{language.name.toUpperCase()} · {fullEnglish?'CEFR A1 BIS C2':'A1 GRUNDKURS'}</span><h1>{fullEnglish?'Ein Lernsystem vom ersten Satz bis zum sprachlichen Feinschliff.':`${language.name} für echte Alltagssituationen – Schritt für Schritt.`}</h1><p>{fullEnglish?'Wähle dein aktuelles Niveau oder starte mit der Einstufung. Der Kurs verbindet Wortschatz, Grammatik, Hören, Sprechen und aktive Produktion.':'Der Kroatisch-Kurs trainiert Begrüßung, Reisen, Café, Einkaufen, Alltag, Hörverstehen und Sprechen. Weitere Stufen werden ausgebaut, ohne deinen A1-Fortschritt zu verlieren.'}</p><div className="course-hub-actions">{fullEnglish&&<button className="view-primary" onClick={openPlacement}>36-Fragen-Einstufung →</button>}<button className="course-ghost" onClick={()=>openLesson(levelLessons(courseState.activeLevel,targetLanguage)[0])}>Aktuelles Level starten</button></div></div><div className="course-stat-cluster"><article><strong>{stats.levels}</strong><span>CEFR-Stufen</span></article><article><strong>{stats.units}</strong><span>Lernblöcke</span></article><article><strong>{stats.lessons}</strong><span>Lektionen</span></article><article><strong>{stats.exercises}</strong><span>Aufgaben</span></article></div></div>
  {fullEnglish&&courseState.placement&&<div className="placement-summary"><div><span className="eyebrow">LETZTE EINSTUFUNG</span><strong>{courseState.placement.recommendedLevel}</strong><p>{courseState.placement.score}/{courseState.placement.total} Orientierungsfragen richtig</p>{courseState.placement.focus?.[0]&&<small>Fokus: {courseState.placement.focus[0]}</small>}</div><button onClick={openPlacement}>Neu einstufen</button></div>}
  <div className="course-levels">{levels.map(level=>{const lp=levelProgress(level.id,progress,targetLanguage),active=level.id===courseState.activeLevel,all=level.units.flatMap(unit=>unit.lessons),firstOpen=all.find(lesson=>!progress.completedLessonIds.includes(lesson.id))??all[0];return <article key={level.id} className={`course-level-card ${active?'active':''}`}><div className="course-level-side"><div className="course-level-badge">{level.id}</div><span>{active?'AKTIV':'CEFR'}</span></div><div className="course-level-main"><div className="course-level-title"><div><span>{level.descriptor}</span><h2>{level.title}</h2></div><div className="course-level-progress"><strong>{lp.percent}%</strong><small>{lp.done}/{lp.total} Lektionen</small></div></div><p className="course-level-goal">{level.goal}</p><div className="course-unit-grid">{level.units.map(unit=>{const done=unit.lessons.filter(lesson=>progress.completedLessonIds.includes(lesson.id)).length;return <div key={unit.id} className="course-unit-mini"><div><span>UNIT {unit.number}</span><strong>{unit.title}</strong></div><small>{done}/{unit.lessons.length} · {unit.subtitle}</small></div>})}</div><div className="course-level-actions"><button className="course-select" onClick={()=>onSelectLevel(level.id)}>{active?'Ausgewählt':`${level.id} auswählen`}</button><button className="course-start" onClick={()=>{onSelectLevel(level.id);openLesson(firstOpen)}}>Lektion starten →</button></div></div></article>})}</div></section>;
}
