import { studySeconds } from '../learning/study-time';
import { specialties, languageByCode } from '../data/catalog';
import { courseLevels, lessonIsUnlocked, levelById, type CefrLevel } from '../learning/curriculum';
import type { PlacementResult } from '../learning/course-state';
import type { LearnerPreferences } from '../learning/preferences';
import type { PlatformProgress } from '../learning/progress';
import type { Lesson, LessonResult } from '../learning/types';

type Props={progress:PlatformProgress;preferences:LearnerPreferences;activeLevel:CefrLevel;placement:PlacementResult|null;lastResult:LessonResult|null;targetLanguage:string;openLesson:(lesson:Lesson)=>void;buildReview:()=>Lesson;openPro:()=>void;openCourse:()=>void;openPlacement:()=>void;openTranslator:()=>void;onSelectLevel:(level:CefrLevel)=>void};
const placementLabels={grammar:'Grammatik',vocabulary:'Wortschatz',communication:'Kommunikation'} as const;

export default function DashboardView({progress,preferences,activeLevel,placement,lastResult,targetLanguage,openLesson,buildReview,openPro,openCourse,openPlacement,openTranslator,onSelectLevel}:Props){
  const language=languageByCode(targetLanguage),levels=courseLevels(targetLanguage),level=levelById(activeLevel,targetLanguage),lessons=level.units.flatMap(unit=>unit.lessons);
  const curriculumCompleted=lessons.filter(lesson=>progress.completedLessonIds.includes(lesson.id)).length,courseProgress=lessons.length?Math.round(curriculumCompleted/lessons.length*100):0,nextLesson=lessons.find(lesson=>!progress.completedLessonIds.includes(lesson.id))??lessons[lessons.length-1],fullEnglish=targetLanguage==='en';
  const courseRange=levels.length>1?`${levels[0].id} bis ${levels[levels.length-1].id}`:(levels[0]?.id||activeLevel);
  const minutes=Math.floor(studySeconds()/60),goalPercent=Math.min(100,Math.round(studySeconds()/(preferences.dailyMinutes*60)*100)),studiedToday=goalPercent>=100;
  const placementAreas=placement?.breakdown?(Object.keys(placementLabels) as Array<keyof typeof placementLabels>).map(key=>{const item=placement.breakdown![key];return{key,label:placementLabels[key],percent:item.total?Math.round(item.score/item.total*100):0}}):[];
  return <div className="page-grid"><section className="primary-column">
    <div className="hero-panel"><div className="hero-copy"><span className="eyebrow">{preferences.name.toUpperCase()} · {language.name.toUpperCase()} {activeLevel}</span><h1>Heute ein Stück sicherer in {language.name}.</h1><p>{level.goal} VocabFast verbindet neue Inhalte, aktives Anwenden und gezielte Wiederholung zu deinem nächsten sinnvollen Lernschritt.</p><div className="hero-actions"><button className="primary-action" onClick={()=>openLesson(nextLesson)}>Weiterlernen <span>→</span></button><button className="secondary-action" onClick={openTranslator}>Übersetzer öffnen</button></div></div><div className="hero-orbit" aria-hidden="true"><div className="orbit-ring ring-one"/><div className="orbit-ring ring-two"/><div className="core-word"><span>{activeLevel}</span><strong>{courseProgress}%</strong><small>{curriculumCompleted}/{lessons.length} Lektionen</small></div><div className="orbit-dot dot-one">Aa</div><div className="orbit-dot dot-two">✓</div><div className="orbit-dot dot-three">🎙</div></div></div>
    <div className="cefr-strip" aria-label="CEFR-Level auswählen">{levels.map(item=><button key={item.id} className={item.id===activeLevel?'active':''} onClick={()=>onSelectLevel(item.id)}><strong>{item.id}</strong><small>{item.title}</small></button>)}</div>
    <div className="dashboard-course-callout"><div><strong>{language.name}: {courseRange} im aktuellen Lernpfad.</strong><p>{fullEnglish?'Nutze die Einstufung für eine Empfehlung oder wähle dein Level direkt selbst.':'Wechsle zwischen den verfügbaren Stufen, ohne deinen bisherigen Fortschritt zu verlieren.'}</p></div><div className="hero-actions">{fullEnglish&&<button onClick={openPlacement}>Niveau bestimmen</button>}<button onClick={openCourse}>Kursübersicht →</button></div></div>
    {fullEnglish&&placement&&<section className="personal-plan-card"><div className="personal-plan-head"><div><span className="eyebrow">DEINE EINSTUFUNG</span><h2>Empfohlener Start: {placement.recommendedLevel}</h2><p>Die Auswertung zeigt dir einen sinnvollen Einstieg und die Bereiche, die sich als Nächstes am meisten lohnen.</p></div><div className="personal-plan-level"><span>START</span><strong>{placement.recommendedLevel}</strong><small>{placement.score}/{placement.total} richtig</small></div></div>{placementAreas.length>0&&<div className="personal-plan-bars">{placementAreas.map(item=><div key={item.key}><span><strong>{item.label}</strong><small>{item.percent}%</small></span><div><i style={{width:`${item.percent}%`}}/></div></div>)}</div>}<div className="personal-plan-focus"><div><span className="eyebrow">DEINE NÄCHSTEN SCHWERPUNKTE</span>{(placement.focus?.length?placement.focus:['Kurze tägliche Einheiten festigen deinen Fortschritt.']).map(item=><p key={item}>✓ {item}</p>)}</div><button onClick={openPlacement}>Einstufung wiederholen</button></div></section>}
    {lastResult&&<div className="section-heading"><div><span className="eyebrow">LETZTE EINHEIT</span><h2>{lastResult.accuracy}% richtig · +{lastResult.xp} XP</h2></div><button className="text-button" onClick={()=>openLesson(buildReview())}>Fehler gezielt wiederholen</button></div>}
    <div className="section-heading" id="course-units"><div><span className="eyebrow">DEIN LERNPFAD</span><h2>{language.name} · {activeLevel} {level.title}</h2></div><span className="pro-label">{lessons.length} Lektionen</span></div>
    <div className="learning-path">{level.units.map((unit,index)=>{const done=unit.lessons.filter(lesson=>progress.completedLessonIds.includes(lesson.id)).length,percent=unit.lessons.length?Math.round(done/unit.lessons.length*100):0,unlocked=index===0||level.units[index-1].lessons.every(lesson=>progress.completedLessonIds.includes(lesson.id)),state=percent===100?'done':unlocked?'active':'locked',nextInUnit=unit.lessons.find(lesson=>!progress.completedLessonIds.includes(lesson.id))??unit.lessons[unit.lessons.length-1];return <article key={unit.id} className={`unit-card ${state}`}><div className="path-rail"><div className="unit-node">{state==='done'?'✓':unit.number}</div>{index<level.units.length-1&&<div className="rail-line"/>}</div><div className="unit-body"><div className="unit-topline"><span>Unit {unit.number}</span><span>{unit.lessons.length} Lektionen</span></div><h3>{unit.title}</h3><p>{unit.subtitle}</p><div className="progress-row"><div className="progress-track"><span style={{width:`${percent}%`}}/></div><strong>{percent}%</strong></div>{state==='active'&&<button className="unit-action" onClick={()=>openLesson(nextInUnit)}>{nextInUnit.title} <span>→</span></button>}{state==='locked'&&<span className="locked-copy">Beende zuerst den vorherigen Lernblock.</span>}</div></article>})}</div>
    {level.units.map(unit=><div key={`${unit.id}-detail`} className="course-unit-detail"><div className="section-heading"><div><span className="eyebrow">{activeLevel} · UNIT {unit.number}</span><h2>{unit.title}</h2></div><span className="pro-label">{unit.lessons.length} Lektionen</span></div><div className="starter-lessons">{unit.lessons.map((lesson,index)=>{const completed=progress.completedLessonIds.includes(lesson.id),unlocked=lessonIsUnlocked(lesson.id,progress.completedLessonIds,targetLanguage),result=progress.results[lesson.id];return <button key={lesson.id} className={`starter-lesson ${completed?'completed':''}`} disabled={!unlocked} onClick={()=>openLesson(lesson)}><div className="starter-lesson-top"><span>Lektion {index+1}</span><span className="starter-lesson-status">{completed?'✓':unlocked?'→':'🔒'}</span></div><h3>{lesson.title}</h3><p>{lesson.subtitle}</p><div className="starter-lesson-footer"><span>{lesson.estimatedMinutes} Min · {lesson.exercises.length} Aufgaben</span><strong>{result?`${result.accuracy}%`:(unlocked?'Starten':'Gesperrt')}</strong></div></button>})}</div></div>)}
    <div className="adaptive-strip"><div><strong>{activeLevel} · Intelligente Wiederholung</strong><span>Fällige und unsichere Inhalte werden automatisch stärker gewichtet.</span></div><button onClick={()=>openLesson(buildReview())}>Wiederholung starten</button></div>
    {fullEnglish&&<><div className="section-heading specialty-heading"><div><span className="eyebrow">FÜR DEINEN ALLTAG</span><h2>Fachsprache für konkrete Situationen</h2></div><button type="button" className="pro-label pro-link" onClick={openPro} aria-label="VocabFast Pro ansehen">PRO</button></div><div className="specialty-grid">{specialties.slice(0,4).map(item=><article key={item.id} className="specialty-card"><div className="specialty-icon">{item.icon}</div><div><strong>{item.name}</strong><p>{item.description}</p></div><button onClick={openPro} aria-label={`${item.name} mit VocabFast Pro ansehen`}>→</button></article>)}</div></>}
  </section><aside className="right-column"><section className="daily-card"><div className="card-heading"><div><span className="eyebrow">HEUTE</span><h3>{preferences.dailyMinutes}-Minuten-Ziel</h3></div><strong>{studiedToday?'✓':`${goalPercent}%`}</strong></div><div className="daily-ring"><div><strong>{`${goalPercent}%`}</strong><span>{`${minutes} / ${preferences.dailyMinutes} Min`}</span></div></div><div className="task-list"><div className={studiedToday?'done':''}><span>{studiedToday?'✓':'1'}</span><div><strong>Nächste Lektion</strong><small>{nextLesson?.estimatedMinutes||8} Minuten</small></div></div><div><span>2</span><div><strong>Wiederholen</strong><small>Unsichere Inhalte</small></div></div><div><span>3</span><div><strong>Hören</strong><small>Aussprache verstehen</small></div></div><div><span>4</span><div><strong>Übersetzen</strong><small>Neue Sätze klären</small></div></div></div></section><section className="coach-card"><div className="coach-head"><div className="coach-mark">AI</div><div><span className="eyebrow">VOCABFAST</span><h3>{progress.sessions?'Dein Training passt sich an.':'Beginne mit deiner ersten Einheit.'}</h3></div></div><p>Wiederholungen orientieren sich an deinem Lernpfad und an den Aufgaben, die dir noch schwerfallen.</p><div className="coach-insight"><span>Aktueller Fokus</span><strong>{language.name} {activeLevel}</strong><small>{level.descriptor}</small></div><button onClick={()=>openLesson(progress.sessions?buildReview():lessons[0])}>Training starten</button></section><section className="streak-card"><div className="card-heading"><div><span className="eyebrow">KONTINUITÄT</span><h3>{progress.currentStreak} Tage am Stück</h3></div><span className="streak-fire">🔥</span></div><div className="streak-number"><strong>{progress.currentStreak}</strong><span>aktueller Streak</span></div><p>Bestwert: {progress.longestStreak} Tage. Regelmäßige kurze Einheiten bringen dich verlässlicher weiter als seltene lange Sessions.</p></section>{fullEnglish&&<section className="pro-card"><button type="button" className="pro-pill pro-link" onClick={openPro}>VOCABFAST PRO</button><h3>Mehr Training, mehr persönliches Feedback.</h3><p>KI-Coach, Fachsprache und zusätzliche Analysefunktionen.</p><div className="price-row"><strong>19,99 €</strong><span>/ Monat</span></div><button onClick={openPro}>Pro ansehen</button></section>}</aside></div>;
}
