import { lazy, Suspense, useMemo, useState } from 'react';
import { levelVocabulary } from '../data/level-vocabulary';
import type { CefrLevel } from '../learning/curriculum';
import { makeWord, mergeWords, parseWordImport, rateWord, readWords, saveWords, type PersonalWord } from '../learning/personal-words';
import { readPreferences } from '../learning/preferences';
import { speakLanguage } from '../learning/speech';
import './personal-words.css';

const PDFWordScanner=lazy(()=>import('./PDFWordScanner'));
type TrainingMode='due'|'all';
type Props={isPro:boolean;openPro:()=>void;showLevelPacks?:boolean;languageName?:string};
const cefrLevels:CefrLevel[]=['A1','A2','B1','B2','C1','C2'];
const normalize=(value:string)=>value.trim().toLocaleLowerCase();
const pairKey=(word:string,translation:string)=>`${normalize(word)}|${normalize(translation)}`;
const fromStudyTool=(item:PersonalWord)=>item.tag==='Übersetzer'||item.tag.startsWith('PDF Reader')||item.tag.startsWith('PDF-')||item.tag.startsWith('PDF ');

export default function PersonalWords({isPro,openPro,showLevelPacks=true,languageName='deine Lernsprache'}:Props){
 const [words,setWords]=useState(readWords),[query,setQuery]=useState(''),[tagFilter,setTagFilter]=useState('Alle'),[stageFilter,setStageFilter]=useState('Alle');
 const [word,setWord]=useState(''),[translation,setTranslation]=useState(''),[tag,setTag]=useState(''),[editing,setEditing]=useState<string|null>(null),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const [importOpen,setImportOpen]=useState(false),[importText,setImportText]=useState(''),[scannerOpen,setScannerOpen]=useState(false);
 const [queue,setQueue]=useState<{id:string;reverse:boolean}[]>([]),[index,setIndex]=useState(0),[revealed,setRevealed]=useState(false),[score,setScore]=useState(0),[training,setTraining]=useState(false),[trainingMode,setTrainingMode]=useState<TrainingMode>('due'),[trainingLabel,setTrainingLabel]=useState('FÄLLIGE WÖRTER');
 const preferences=readPreferences();
 const filtered=words.filter(w=>(tagFilter==='Alle'||w.tag===tagFilter)&&(stageFilter==='Alle'||(stageFilter==='Fällig'?w.stage>0&&w.dueAt<=Date.now():w.stage===Number(stageFilter)))&&`${w.word} ${w.translation} ${w.tag}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 const current=words.find(w=>w.id===queue[index]?.id),reverse=queue[index]?.reverse;
 const savedKeys=useMemo(()=>new Set(words.map(item=>pairKey(item.word,item.translation))),[words]);
 const toolWords=useMemo(()=>words.filter(fromStudyTool).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)).slice(0,20),[words]);
 const toolSources=useMemo(()=>[...new Set(toolWords.map(item=>item.tag.startsWith('PDF')?'PDF':'Translate'))],[toolWords]);
 function persist(next:PersonalWord[]){try{saveWords(next);setWords(next);setError('');return true;}catch{setError('Die Wörter konnten nicht gespeichert werden. Bitte sichere sie per Export und versuche es erneut.');return false;}}
 function submit(event:React.FormEvent){event.preventDefault();const next=editing?words.map(w=>w.id===editing?{...w,word:word.trim(),translation:translation.trim(),tag:tag.trim()||'Eigene Wörter',stage:3 as const,hits:0,dueAt:0}:w):mergeWords(words,[makeWord(word,translation,tag)]);if(!editing&&next.length===words.length){setError('Dieses Wort mit dieser Übersetzung ist bereits vorhanden.');return;}if(persist(next)){setWord('');setTranslation('');setTag('');setEditing(null);setNotice(editing?'Wort aktualisiert.':'Wort hinzugefügt und für dein Training gespeichert.');}}
 function startQueue(source:PersonalWord[],label:string,mode:TrainingMode='all'){
   const batch=[...source].sort(()=>Math.random()-.5).slice(0,30).map(w=>({id:w.id,reverse:(mode==='all'||w.stage<=2)&&Math.random()<.5}));
   if(!batch.length)return;
   setTrainingMode(mode);setTrainingLabel(label);setQueue(batch);setIndex(0);setScore(0);setRevealed(false);setTraining(true);setNotice('');setError('');
 }
 function start(mode:TrainingMode){const source=mode==='due'?filtered.filter(w=>w.stage>0&&w.dueAt<=Date.now()):filtered;startQueue(source,mode==='due'?'FÄLLIGE WÖRTER':'GESPEICHERTE WÖRTER',mode);}
 function levelWordsFrom(source:PersonalWord[],level:CefrLevel){const keys=new Set(levelVocabulary[level].map(item=>pairKey(item.word,item.translation)));return source.filter(item=>keys.has(pairKey(item.word,item.translation)));}
 function saveLevel(level:CefrLevel,startAfter=false){
   const pack=levelVocabulary[level];
   const next=mergeWords(words,pack.map(item=>makeWord(item.word,item.translation,`Level ${level}`)));
   const added=next.length-words.length;
   if(!persist(next))return;
   setNotice(added?`${added} neue ${level}-Wörter gespeichert.`:`Der ${level}-Kernwortschatz ist bereits gespeichert.`);
   if(startAfter)startQueue(levelWordsFrom(next,level),`LEVEL ${level}`,'all');
 }
 function practiceLevel(level:CefrLevel){const available=levelWordsFrom(words,level);if(available.length)startQueue(available,`LEVEL ${level}`,'all');}
 function rate(correct:boolean){if(!current)return;if(!persist(words.map(w=>w.id===current.id?rateWord(w,correct):w)))return;setScore(score+(correct?1:0));setIndex(index+1);setRevealed(false);}
 function importWords(text=importText){try{const next=mergeWords(words,parseWordImport(text));if(persist(next)){setNotice(`${next.length-words.length} neue Wörter importiert. Doppelte Einträge wurden übersprungen.`);setImportText('');setImportOpen(false);}}catch(reason){setError(reason instanceof Error?reason.message:'Import fehlgeschlagen.');}}
 function exportWords(){const url=URL.createObjectURL(new Blob([JSON.stringify(words.map(({word,translation,tag})=>({word,translation,tag})),null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='vocabfast-woerter.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Wortliste exportiert. Beim Import beginnt das Training neu.');}
 const due=filtered.filter(w=>w.stage>0&&w.dueAt<=Date.now()).length;
 return <section className="personal-words"><div className="view-section-head"><div><span className="eyebrow">MEINE ÜBUNGSWÖRTER</span><h2>Dein persönlicher {languageName}-Wortschatz.</h2><p>{isPro?'Speichere Wörter und Sätze aus Translate, PDFs oder manuell und trainiere genau deinen eigenen Lernstoff.':'Speichere Wörter und Sätze aus Translate oder manuell und trainiere genau deinen eigenen Lernstoff. PDF-Import ist in Pro enthalten.'}</p></div><div className="word-training-actions"><button onClick={()=>start('all')} disabled={!filtered.length}>Gespeicherte Wörter üben</button><button className="view-primary" onClick={()=>start('due')} disabled={!due}>{due?`${due} fällige Wörter üben`:'Nichts fällig'}</button></div></div>
 <div className="word-stats"><span><strong>{words.length}</strong> Übungswörter</span><span><strong>{words.filter(w=>w.stage>0&&w.dueAt<=Date.now()).length}</strong> fällig</span><span><strong>{words.filter(w=>w.stage===0).length}</strong> gemeistert</span></div>
 {toolWords.length>0&&<section className="recent-study-card"><div><span className="eyebrow">AUS DEINEN ECHTEN INHALTEN</span><h3>Gerade übersetzt oder aus PDFs übernommen.</h3><p>Trainiere zuerst die Sätze und Wörter, die du selbst gebraucht hast. Das macht deinen Wortschatz automatisch persönlicher.</p><div className="recent-study-chips">{toolSources.map(source=><span key={source}>{source}</span>)}<span>{toolWords.length} Karten</span></div></div><div className="recent-study-preview">{toolWords.slice(0,3).map(item=><span key={item.id}><strong>{item.word}</strong><small>{item.translation}</small></span>)}</div><button className="view-primary" onClick={()=>startQueue(toolWords,'AUS TRANSLATE & PDF','all')}>Jetzt wiederholen →</button></section>}
 {showLevelPacks&&<section className="level-vocabulary"><div className="level-vocabulary-head"><div><span className="eyebrow">LEVEL-WORTSCHATZ</span><strong>Wichtige Wörter von A1 bis C2</strong><p>Speichere den VocabFast-Kernwortschatz eines Levels gesammelt und trainiere anschließend genau diese Wörter. Die Listen orientieren sich an typischen CEFR-Kommunikationssituationen, sind aber kein offizielles CEFR-Wörterbuch.</p></div></div><div className="level-vocabulary-row">{cefrLevels.map(level=>{const pack=levelVocabulary[level],saved=pack.filter(item=>savedKeys.has(pairKey(item.word,item.translation))).length,percent=Math.round(saved/pack.length*100);return <article key={level}><header><span>{level}</span><div><strong>{saved}/{pack.length}</strong><small>gespeichert</small></div></header><div className="level-word-progress"><span style={{width:`${percent}%`}}/></div><p>{pack.slice(0,5).map(item=>item.word).join(' · ')} …</p><div><button onClick={()=>saveLevel(level)} disabled={saved===pack.length}>{saved===pack.length?'Komplett gespeichert':'Alle speichern'}</button><button className="view-primary" onClick={()=>saved?practiceLevel(level):saveLevel(level,true)}>{saved?'Level üben':'Speichern & üben'}</button></div></article>})}</div></section>}
 {!showLevelPacks&&<div className="word-language-note"><strong>Persönlicher Wortschatz für {languageName}</strong><span>Level-Pakete werden nur dort angezeigt, wo VocabFast bereits einen geprüften Wortschatz dafür hat. Eigene Wörter, Translate, PDF, Audio und Wiederholung funktionieren hier trotzdem vollständig.</span></div>}
 <div className="word-source-bar"><div><span className="eyebrow">SCHNELL HINZUFÜGEN</span><strong>Wie möchtest du neue Wörter übernehmen?</strong></div><button className={scannerOpen?'active':''} onClick={()=>{if(!isPro){openPro();return;}setScannerOpen(value=>!value)}}>▣ PDF-Wortscanner {!isPro&&<b>PRO</b>}</button><button onClick={()=>setImportOpen(!importOpen)}>⇧ Liste importieren</button></div>
 {scannerOpen&&isPro&&<Suspense fallback={<div className="word-tool-loading"><i/><span>PDF-Scanner wird geladen …</span></div>}><PDFWordScanner onSaved={count=>{setWords(readWords());setNotice(count?`${count} Wörter aus der PDF wurden gespeichert.`:'Die ausgewählten Wörter waren bereits gespeichert.');}}/></Suspense>}
 <form className="word-form" onSubmit={submit}><label>Wort / Ausdruck<input required maxLength={200} value={word} onChange={e=>setWord(e.target.value)} placeholder="z. B. visibility"/></label><label>Übersetzung<input required maxLength={500} value={translation} onChange={e=>setTranslation(e.target.value)} placeholder="z. B. Sichtweite"/></label><label>Thema<input maxLength={60} value={tag} onChange={e=>setTag(e.target.value)} placeholder="z. B. Reise" list="word-topics"/></label><datalist id="word-topics">{[...new Set(words.map(w=>w.tag))].map(t=><option key={t} value={t}/>)}</datalist><button className="view-primary" type="submit">{editing?'Änderung speichern':'+ Hinzufügen'}</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setWord('');setTranslation('');setTag('')}}>Abbrechen</button>}</form>
 {error&&<p className="word-error" role="alert">{error}</p>}{notice&&<p className="word-notice" role="status">{notice}</p>}
 <div className="word-toolbar"><label className="word-search">Suchen<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Wort oder Übersetzung …"/></label><label>Thema<select value={tagFilter} onChange={e=>setTagFilter(e.target.value)}><option>Alle</option>{[...new Set(words.map(w=>w.tag))].sort().map(t=><option key={t}>{t}</option>)}</select></label><label>Lernstand<select value={stageFilter} onChange={e=>setStageFilter(e.target.value)}><option>Alle</option><option>Fällig</option><option value="3">Stufe 3 · Neu</option><option value="2">Stufe 2 · Im Aufbau</option><option value="1">Stufe 1 · Sicher</option><option value="0">Gemeistert</option></select></label><button onClick={exportWords} disabled={!words.length}>Exportieren</button></div>
 {importOpen&&<div className="word-import"><h3>Wörter gesammelt hinzufügen</h3><p>Eine Zeile pro Wort: Wort, Tab, Übersetzung, optional Tab und Thema. JSON-Exporte kannst du ebenfalls laden. Importierte Wörter starten in Stufe 3.</p><textarea aria-label="Wörter zum Importieren" value={importText} onChange={e=>setImportText(e.target.value)} placeholder={'visibility\tSichtweite\tAviation'}/><div><button className="view-primary" disabled={!importText.trim()} onClick={()=>importWords()}>Text importieren</button><label className="word-file">Datei auswählen<input type="file" accept=".json,.tsv,.txt" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>2_000_000){setError('Die Datei darf höchstens 2 MB groß sein.');return;}try{importWords(await f.text());}catch{setError('Die Datei konnte nicht gelesen werden.');}e.target.value='';}}/></label></div></div>}
 <div className="personal-word-list">{filtered.length?filtered.slice(0,100).map(w=><article key={w.id}><div><span className="concept-type">{w.tag}</span><strong>{w.word}</strong><span>{w.translation}</span></div><div className="word-stage"><strong>{w.stage?`Stufe ${w.stage}`:'Gemeistert'}</strong><small>{w.stage?`${w.hits}/5 richtig`:'✓ abgeschlossen'}</small>{w.stage>0&&<small>{w.dueAt<=Date.now()?'Jetzt fällig':`Ab ${new Date(w.dueAt).toLocaleDateString('de-AT')}`}</small>}</div><div className="word-row-actions"><button aria-label={`${w.word} vorlesen`} onClick={()=>{if(!speakLanguage(w.word,preferences.targetLanguage,preferences.audioRate))setError('Sprachausgabe ist in diesem Browser nicht verfügbar.');}}>▶</button><button onClick={()=>{setEditing(w.id);setWord(w.word);setTranslation(w.translation);setTag(w.tag);document.querySelector('.word-form')?.scrollIntoView({behavior:'smooth',block:'center'});}}>Bearbeiten</button><button aria-label={`${w.word} löschen`} onClick={()=>{if(window.confirm(`„${w.word}“ aus deinen Wörtern löschen?`))persist(words.filter(x=>x.id!==w.id));}}>×</button></div></article>):<div className="empty-state"><strong>{words.length?'Keine passenden Wörter.':'Dein persönlicher Wortschatz beginnt hier.'}</strong><span>{words.length?'Passe deine Suche oder die Filter an.':'Füge dein erstes Wort hinzu oder speichere eine Übersetzung.'}</span></div>}{filtered.length>100&&<p>Die ersten 100 von {filtered.length} Treffern. Nutze die Suche, um weiter einzugrenzen.</p>}</div>
 <details className="word-rules"><summary>So funktionieren Training und Lernstufen</summary><p>Mit „Gespeicherte Wörter üben“ kannst du jederzeit die aktuell gefilterten Wörter trainieren. Die fällige Wiederholung zeigt dir gezielt Karten nach dem Lernplan. Fünf richtige Bewertungen bringen dich von Stufe 3 in Stufe 2, dann in Stufe 1 und schließlich zu „gemeistert“. Ein Fehler stuft das Wort wieder zurück. Ab Stufe 2 wechseln die Übersetzungsrichtungen zufällig.</p></details>
 {training&&<div className="modal-backdrop"><section className="word-training" role="dialog" aria-modal="true" aria-labelledby="word-training-title"><header><span className="eyebrow">{trainingLabel}</span><button onClick={()=>setTraining(false)} aria-label="Training schließen">×</button></header>{current?<><p>{index+1} / {queue.length} · {current.tag}</p><h2 id="word-training-title">{reverse?current.translation:current.word}</h2><button className="word-audio" onClick={()=>speakLanguage(reverse?current.translation:current.word,reverse?preferences.sourceLanguage:preferences.targetLanguage,preferences.audioRate)}>▶ Vorlesen</button>{revealed?<><div className="word-answer">{reverse?current.word:current.translation}</div><p>Konntest du die Übersetzung selbst abrufen?</p><div className="word-rating"><button onClick={()=>rate(false)}>Noch üben</button><button className="view-primary" onClick={()=>rate(true)}>Gewusst ✓</button></div></>:<><p>Sprich die Übersetzung laut aus, bevor du nachsiehst.</p><button className="view-primary" onClick={()=>setRevealed(true)}>Antwort anzeigen</button></>}</>:<><h2 id="word-training-title">Runde abgeschlossen.</h2><p>{score} von {queue.length} Karten gewusst. Dein Lernstand wurde aktualisiert.</p><div className="word-rating"><button onClick={()=>setTraining(false)}>Zurück zum Wortschatz</button><button className="view-primary" onClick={()=>start(trainingMode)}>Noch eine Runde</button></div></>}</section></div>}
 </section>;
}