import { useMemo, useState } from 'react';
import type { CefrLevel } from '../learning/curriculum';
import type { PlacementBreakdown } from '../learning/course-state';
import './placement-test.css';

type Area='grammar'|'vocabulary'|'communication';
type Format='use'|'reading'|'situation';
type Question={level:CefrLevel;area:Area;format:Format;prompt:string;context?:string;passage?:string;choices:string[];answer:string};
type Props={onClose:()=>void;onFinish:(level:CefrLevel,score:number,total:number,details:{breakdown:PlacementBreakdown;focus:string[]})=>void};

const questions:Question[]=[
  {level:'A1',area:'grammar',format:'use',prompt:'Choose the correct form.',context:'My sister ___ in Graz.',choices:['lives','live','living','is live'],answer:'lives'},
  {level:'A1',area:'grammar',format:'use',prompt:'Complete the question.',context:'___ you like coffee?',choices:['Do','Are','Does','Have'],answer:'Do'},
  {level:'A1',area:'vocabulary',format:'situation',prompt:'Which word fits the situation?',context:'You buy something in a shop and want proof that you paid.',choices:['receipt','recipe','ticket office','reservation'],answer:'receipt'},
  {level:'A1',area:'communication',format:'situation',prompt:'Choose the most natural reply.',context:'Someone says: “Nice to meet you.”',choices:['Nice to meet you too.','I am meeting at five.','Yes, I can meet.','You are nice too?'],answer:'Nice to meet you too.'},
  {level:'A1',area:'communication',format:'reading',prompt:'Where should the passenger go?',passage:'TRAIN INFORMATION\nPlatform change: The 08:40 train to Vienna will leave from platform 6, not platform 4.',choices:['Platform 6','Platform 4','The ticket office','The bus station'],answer:'Platform 6'},

  {level:'A2',area:'grammar',format:'use',prompt:'Choose the correct form.',context:'I have worked here ___ two years.',choices:['for','since','during','from'],answer:'for'},
  {level:'A2',area:'grammar',format:'use',prompt:'Complete the sentence.',context:'When I called, she ___ dinner.',choices:['was making','made','has made','makes'],answer:'was making'},
  {level:'A2',area:'vocabulary',format:'situation',prompt:'Choose the correct verb.',context:'Can I ___ your pen for a minute?',choices:['borrow','lend','owe','bring'],answer:'borrow'},
  {level:'A2',area:'communication',format:'situation',prompt:'What is the most polite request?',context:'Your hotel room is very noisy and you want another one.',choices:['Could I change to a quieter room, please?','Give me another room because this is loud.','I want that you change my room.','Can the room change me?'],answer:'Could I change to a quieter room, please?'},
  {level:'A2',area:'communication',format:'reading',prompt:'Why will the delivery arrive later?',passage:'Hi Sam, your parcel was due today, but heavy snow has delayed deliveries in your area. We now expect it tomorrow afternoon.',choices:['Bad weather','The address is wrong','The parcel was cancelled','The customer changed the date'],answer:'Bad weather'},

  {level:'B1',area:'grammar',format:'use',prompt:'Choose the connector that fits.',context:'___ the course was difficult, I learned a lot.',choices:['Although','Because of','Despite of','Unless'],answer:'Although'},
  {level:'B1',area:'grammar',format:'use',prompt:'Which sentence gives hypothetical advice?',choices:['If I were you, I would speak to the manager.','If I am you, I will speak to the manager.','If I was you, I speak to the manager.','If I were you, I spoke to the manager.'],answer:'If I were you, I would speak to the manager.'},
  {level:'B1',area:'vocabulary',format:'use',prompt:'Which word completes the sentence naturally?',context:'We need to finish the report before the ___.',choices:['deadline','occasion','appointment','timetable'],answer:'deadline'},
  {level:'B1',area:'communication',format:'situation',prompt:'Choose the clearest way to disagree politely.',context:'A colleague suggests cancelling the whole project because one task is late.',choices:['I see your point, but I think cancelling the whole project would be too drastic.','No, that idea is completely wrong.','You should not think like that.','I disagree because I disagree with cancelling.'],answer:'I see your point, but I think cancelling the whole project would be too drastic.'},
  {level:'B1',area:'communication',format:'reading',prompt:'What is the writer mainly asking for?',passage:'Hi Laura, I have finished the first draft of the presentation. Could you look at slides 4–7 before tomorrow morning? I am mainly unsure about the figures on slide 6.',choices:['Feedback on part of the presentation','A completely new presentation','Permission to cancel the meeting','Help booking a meeting room'],answer:'Feedback on part of the presentation'},

  {level:'B2',area:'grammar',format:'use',prompt:'Complete the unreal past condition.',context:'If we had known earlier, we ___ a different route.',choices:['would have taken','would take','had taken','will have taken'],answer:'would have taken'},
  {level:'B2',area:'grammar',format:'use',prompt:'Choose the most natural formal wording.',context:'I would appreciate it if you ___ the figures by Friday.',choices:['could confirm','can confirm','must confirm','would confirmed'],answer:'could confirm'},
  {level:'B2',area:'vocabulary',format:'use',prompt:'Which phrase means that a trend became stable?',context:'After rising sharply for six months, demand finally ___.',choices:['levelled off','dropped out','held up','broke through'],answer:'levelled off'},
  {level:'B2',area:'communication',format:'situation',prompt:'Which response shows balanced professional disagreement?',context:'You agree with the idea, but the proposed deadline looks unrealistic.',choices:['I support the overall approach, although I have reservations about the proposed timeline.','I support it, therefore the timeline is a problem.','The idea is good despite the deadline is impossible.','I agree, but everything about the timing is wrong.'],answer:'I support the overall approach, although I have reservations about the proposed timeline.'},
  {level:'B2',area:'communication',format:'reading',prompt:'What is the author’s main concern?',passage:'The pilot programme produced encouraging results, particularly in customer satisfaction. However, the sample was small and the trial lasted only six weeks. Expanding it nationwide now would therefore involve more uncertainty than the headline figures suggest.',choices:['The evidence is promising but still limited','Customer satisfaction fell during the trial','The trial was too expensive to continue','A nationwide rollout has already failed'],answer:'The evidence is promising but still limited'},

  {level:'C1',area:'grammar',format:'use',prompt:'Choose the correct formal conditional structure.',context:'___ demand continue to fall, we would need to revise the forecast.',choices:['Should','Would','Had','Could'],answer:'Should'},
  {level:'C1',area:'grammar',format:'use',prompt:'Choose the correct inversion.',context:'Rarely ___ such a rapid shift in public opinion.',choices:['have we seen','we have seen','did we have seen','we saw'],answer:'have we seen'},
  {level:'C1',area:'vocabulary',format:'use',prompt:'Which verb best completes the collocation?',context:'The latest evidence ___ doubt on the original explanation.',choices:['casts','throws up','makes','gives'],answer:'casts'},
  {level:'C1',area:'communication',format:'situation',prompt:'Which sentence expresses nuanced disagreement?',choices:['I can see the merit of the proposal, but I am not convinced it addresses the underlying issue.','The proposal has merit, whereas it is still wrong overall.','I understand the proposal, therefore I cannot agree with its issue.','The proposal is useful even though its reasoning is invalid in every respect.'],answer:'I can see the merit of the proposal, but I am not convinced it addresses the underlying issue.'},
  {level:'C1',area:'communication',format:'reading',prompt:'Which conclusion best reflects the passage?',passage:'Both studies report a decline in commuting time after flexible working was introduced. The first attributes this mainly to fewer journeys, while the second emphasises changes in when employees travel. The findings point in the same direction, but the proposed mechanisms differ.',choices:['The studies identify a similar trend but explain it differently','The studies prove exactly the same cause','The studies reach opposite conclusions','Neither study finds any change in commuting'],answer:'The studies identify a similar trend but explain it differently'},

  {level:'C2',area:'grammar',format:'use',prompt:'Complete the inversion.',context:'Not until the final figures were released ___ how misleading the estimate had been.',choices:['did we realise','we realised','had we realised','we had realised'],answer:'did we realise'},
  {level:'C2',area:'grammar',format:'use',prompt:'Choose the most idiomatic concessive structure.',context:'___ the objections may be, they do not invalidate the central argument.',choices:['Valid though','However validity','As valid','Valid despite'],answer:'Valid though'},
  {level:'C2',area:'vocabulary',format:'use',prompt:'Which verb best completes the academic collocation?',context:'The paper stops short of ___ a direct causal relationship.',choices:['asserting','assuring','assigning','assuming'],answer:'asserting'},
  {level:'C2',area:'communication',format:'situation',prompt:'Which recommendation is precise and appropriately restrained?',context:'The evidence is incomplete and the decision would be difficult to reverse.',choices:['On balance, I would defer the decision until the underlying assumptions have been tested more rigorously.','The decision must be abandoned because incomplete evidence proves it is unsound.','We should perhaps wait, though proceeding immediately would be equally justified.','The only responsible option is to reject the proposal outright.'],answer:'On balance, I would defer the decision until the underlying assumptions have been tested more rigorously.'},
  {level:'C2',area:'communication',format:'reading',prompt:'What is the most defensible interpretation?',passage:'The correlation remains statistically robust after several controls are introduced. Even so, the design is observational, and unmeasured factors may still account for part of the relationship. The results are therefore compatible with a causal explanation without establishing one conclusively.',choices:['The evidence is consistent with causality but does not prove it','The study conclusively proves a causal relationship','The correlation disappears after controls','The study rules out all alternative explanations'],answer:'The evidence is consistent with causality but does not prove it'}
];

const levels:CefrLevel[]=['A1','A2','B1','B2','C1','C2'];
const areaOrder:Area[]=['grammar','vocabulary','communication'];
const areaLabels:Record<Area,string>={grammar:'Sprachgebrauch & Grammatik',vocabulary:'Wortschatz & Kollokationen',communication:'Lesen & Situationen'};
const sectionCopy:Record<Area,string>={grammar:'Abschnitt 1 von 3',vocabulary:'Abschnitt 2 von 3',communication:'Abschnitt 3 von 3'};
const promotionThreshold:Record<CefrLevel,number>={A1:3,A2:3,B1:3,B2:4,C1:4,C2:4};
const levelCopy:Record<CefrLevel,{title:string;text:string}>={
  A1:{title:'A1 · Grundlagen',text:'Baue ein sicheres Fundament für einfache Alltagssituationen, Grundwortschatz und klare kurze Sätze auf.'},
  A2:{title:'A2 · Alltag',text:'Du kannst viele Standardsituationen bewältigen. Jetzt geht es um mehr Sicherheit, Zeitformen und spontane Reaktionen.'},
  B1:{title:'B1 · Selbstständig',text:'Du kannst zusammenhängend kommunizieren. Der nächste Schritt ist längeres Erzählen, Begründen und flexibler Wortschatz.'},
  B2:{title:'B2 · Sicher & präzise',text:'Du arbeitest bereits selbstständig auf gutem Niveau. Fokus: Präzision, Register, Argumentation und komplexere Texte.'},
  C1:{title:'C1 · Fortgeschritten',text:'Dein Englisch ist stark. Trainiere Nuance, implizite Bedeutung, Synthese und professionelle Wirkung.'},
  C2:{title:'C2 · Feinschliff',text:'Du bewegst dich auf sehr hohem Niveau. Der Fokus liegt auf stilistischer Kontrolle, feinen Bedeutungsunterschieden und Registerwechsel.'}
};

function shuffle<T>(items:T[]):T[]{const copy=[...items];for(let i=copy.length-1;i>0;i-=1){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]];}return copy;}
function buildTestForm(){return areaOrder.flatMap(area=>shuffle(questions.filter(question=>question.area===area)).map(question=>({...question,choices:shuffle(question.choices)})));}
function levelScores(testQuestions:Question[],answers:Record<number,string>){const scores:Record<CefrLevel,number>={A1:0,A2:0,B1:0,B2:0,C1:0,C2:0};testQuestions.forEach((question,index)=>{if(answers[index]===question.answer)scores[question.level]+=1;});return scores;}
function recommendation(testQuestions:Question[],answers:Record<number,string>):CefrLevel{const scores=levelScores(testQuestions,answers);if(scores.A1<promotionThreshold.A1)return'A1';if(scores.A2<promotionThreshold.A2)return'A2';if(scores.B1<promotionThreshold.B1)return'B1';if(scores.B2<promotionThreshold.B2)return'B2';if(scores.C1<promotionThreshold.C1)return'C1';return scores.C2>=promotionThreshold.C2?'C2':'C1';}
function breakdown(testQuestions:Question[],answers:Record<number,string>):PlacementBreakdown{const result:PlacementBreakdown={grammar:{score:0,total:0},vocabulary:{score:0,total:0},communication:{score:0,total:0}};testQuestions.forEach((question,index)=>{result[question.area].total+=1;if(answers[index]===question.answer)result[question.area].score+=1;});return result;}
function focusFor(result:PlacementBreakdown,level:CefrLevel){const areas=(Object.keys(result) as Area[]).map(area=>({area,ratio:result[area].total?result[area].score/result[area].total:0})).sort((a,b)=>a.ratio-b.ratio);const focus:string[]=[];for(const item of areas.slice(0,2)){if(item.area==='grammar')focus.push('Zeitformen, Satzbau und sichere Strukturen gezielt festigen.');if(item.area==='vocabulary')focus.push('Aktiven Wortschatz und natürliche Kollokationen systematisch ausbauen.');if(item.area==='communication')focus.push('Leseverstehen, situationsgerechte Formulierungen und Register trainieren.');}if(level==='A1'||level==='A2')focus.push('Kurze tägliche Hör- und Sprechübungen bringen jetzt besonders viel.');else if(level==='B1'||level==='B2')focus.push('Meinungen, Erfahrungen und berufliche Situationen in längeren Antworten üben.');else focus.push('Nuance, implizite Bedeutung und stilistische Kontrolle bewusst trainieren.');return focus.slice(0,3);}

export default function PlacementTest({onClose,onFinish}:Props){
  const [started,setStarted]=useState(false),[index,setIndex]=useState(0),[answers,setAnswers]=useState<Record<number,string>>({}),[finished,setFinished]=useState(false),[attempt,setAttempt]=useState(0);
  const testQuestions=useMemo(buildTestForm,[attempt]);
  const question=testQuestions[index],selected=answers[index]??'';
  const score=useMemo(()=>testQuestions.reduce((sum,item,i)=>sum+(answers[i]===item.answer?1:0),0),[answers,testQuestions]);
  const levelProfile=useMemo(()=>levelScores(testQuestions,answers),[answers,testQuestions]);
  const recommended=useMemo(()=>recommendation(testQuestions,answers),[answers,testQuestions]);
  const resultBreakdown=useMemo(()=>breakdown(testQuestions,answers),[answers,testQuestions]);
  const focus=useMemo(()=>focusFor(resultBreakdown,recommended),[resultBreakdown,recommended]);
  const progress=finished?100:Math.round(((index+(selected?1:0))/testQuestions.length)*100);
  function next(){if(!selected)return;if(index>=testQuestions.length-1){setFinished(true);return;}setIndex(value=>value+1);}
  function restart(){setAnswers({});setIndex(0);setFinished(false);setStarted(false);setAttempt(value=>value+1);}

  if(!started)return <div className="placement-backdrop" role="dialog" aria-modal="true" aria-labelledby="placementIntroTitle"><section className="placement-card result placement-intro"><button className="placement-close" onClick={onClose} aria-label="Einstufung schließen">×</button><span className="placement-kicker">FREIWILLIGE EINSTUFUNG</span><div className="placement-result-badge intro">30</div><h1 id="placementIntroTitle">Ein realistischerer Startpunkt für deinen Lernpfad.</h1><p>30 Aufgaben prüfen Sprachgebrauch, Wortschatz sowie Lesen und typische Alltagssituationen. Die Aufgaben sind nach Kompetenzbereichen gegliedert und mischen unterschiedliche CEFR-Niveaus, ohne dir während des Tests zu zeigen, welche Stufe gerade geprüft wird.</p><div className="placement-section-overview"><span><strong>01</strong> Sprachgebrauch</span><span><strong>02</strong> Wortschatz</span><span><strong>03</strong> Lesen & Situationen</span></div><div className="placement-note">Dauer: ungefähr 10–15 Minuten. Antworte ohne Übersetzer oder Nachschlagen. Der Test ist freiwillig, jederzeit abbrechbar und liefert eine Lernempfehlung – keinen offiziellen CEFR-Nachweis.</div><div className="placement-actions"><button className="placement-secondary" onClick={onClose}>Lieber selbst wählen</button><button className="placement-primary placement-big-start" onClick={()=>setStarted(true)}>Test starten →</button></div></section></div>;

  if(finished){const copy=levelCopy[recommended];return <div className="placement-backdrop" role="dialog" aria-modal="true" aria-labelledby="placementResultTitle"><section className="placement-card result"><button className="placement-close" onClick={onClose} aria-label="Einstufung schließen">×</button><span className="placement-kicker">DEINE LERNEMPFEHLUNG</span><div className="placement-result-badge">{recommended}</div><h1 id="placementResultTitle">{copy.title}</h1><p>{copy.text}</p><div className="placement-score"><strong>{score}/{testQuestions.length}</strong><span>Aufgaben richtig · Rohwert</span></div><div className="placement-level-profile" aria-label="Niveauprofil">{levels.map(level=><div key={level}><span>{level}</span><strong>{levelProfile[level]}/5</strong><i><b style={{width:`${Math.round(levelProfile[level]/5*100)}%`}}/></i></div>)}</div><div className="placement-breakdown">{(Object.keys(resultBreakdown) as Area[]).map(area=>{const item=resultBreakdown[area],percent=item.total?Math.round(item.score/item.total*100):0;return <div key={area}><span><strong>{areaLabels[area]}</strong><small>{item.score}/{item.total} · {percent}%</small></span><div><i style={{width:`${percent}%`}}/></div></div>;})}</div><div className="placement-focus"><span>DEINE NÄCHSTEN SCHWERPUNKTE</span>{focus.map(item=><p key={item}>✓ {item}</p>)}</div><div className="placement-note">Die Empfehlung ist bewusst konservativ: Für höhere Stufen reicht nicht nur der Gesamtwert – auch die Aufgaben der darunterliegenden Niveaus müssen stabil gelöst werden.</div><div className="placement-actions"><button className="placement-secondary" onClick={restart}>Neu testen</button><button className="placement-primary" onClick={()=>onFinish(recommended,score,testQuestions.length,{breakdown:resultBreakdown,focus})}>Mit {recommended} starten →</button></div></section></div>;}

  return <div className="placement-backdrop" role="dialog" aria-modal="true" aria-labelledby="placementQuestionTitle"><section className="placement-card"><header className="placement-head"><button className="placement-close" onClick={onClose} aria-label="Einstufung schließen">×</button><div className="placement-progress"><span style={{width:`${progress}%`}}/></div><strong>{index+1}/{testQuestions.length}</strong></header><div className="placement-body"><div className="placement-level"><span>{sectionCopy[question.area]} · {areaLabels[question.area]}</span></div><span className="placement-kicker">EINSTUFUNGSTEST</span><h1 id="placementQuestionTitle">{question.prompt}</h1>{question.passage&&<div className="placement-passage"><span>TEXT</span><p>{question.passage}</p></div>}{question.context&&<p className="placement-context">{question.context}</p>}<div className="placement-choices">{question.choices.map((choice,choiceIndex)=><button key={choice} className={selected===choice?'selected':''} onClick={()=>setAnswers(current=>({...current,[index]:choice}))}><span>{String.fromCharCode(65+choiceIndex)}</span><strong>{choice}</strong></button>)}</div></div><footer className="placement-footer"><span>{areaLabels[question.area]}</span><button className="placement-primary" disabled={!selected} onClick={next}>{index===testQuestions.length-1?'Auswerten':'Weiter →'}</button></footer></section></div>;
}
