import { useRef, useState } from 'react';
import { loginAccount, registerAccount, type AccountUser } from '../learning/account';
import './welcome-gate.css';

type Props={onAuthenticated:(user:AccountUser,isNew:boolean)=>void|Promise<void>;notice?:string};
type Mode='login'|'register';
const legalBase='https://vocabfast.net';

export default function WelcomeGate({onAuthenticated,notice}:Props){
  const [mode,setMode]=useState<Mode>('login'),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const authRef=useRef<HTMLElement|null>(null),nameRef=useRef<HTMLInputElement|null>(null),emailRef=useRef<HTMLInputElement|null>(null);
  function focusAuth(nextMode:Mode){setMode(nextMode);setError('');requestAnimationFrame(()=>{authRef.current?.scrollIntoView({behavior:'smooth',block:'center'});window.setTimeout(()=>nextMode==='register'?nameRef.current?.focus():emailRef.current?.focus(),260);});}
  async function submit(event:React.FormEvent){event.preventDefault();if(busy)return;setBusy(true);setError('');try{const result=mode==='register'?await registerAccount({name,email,password}):await loginAccount({email,password});setPassword('');await onAuthenticated(result.user,result.isNew);}catch(reason){setError(reason instanceof Error?reason.message:'Die Anmeldung ist fehlgeschlagen.');}finally{setBusy(false);}}
  return <div className="welcome-shell"><header className="welcome-topbar"><a className="welcome-brand" href="/" aria-label="VocabFast Startseite"><span>V</span><div><strong>VocabFast</strong><small>Language Platform</small></div></a><span className="welcome-preview-label">Englisch · Kroatisch · Übersetzer</span></header>
  <main className="welcome-main"><section className="welcome-story"><span className="welcome-kicker">DEIN PERSÖNLICHES SPRACHTRAINING</span><h1>Sprachen lernen, die im echten Leben funktionieren.</h1><p>VocabFast verbindet strukturierte Lernpfade mit aktivem Sprechen, Hörtraining, intelligenten Wiederholungen und einem Übersetzer für alle angebotenen Sprachen. Englisch reicht von A1 bis C2; Kroatisch startet mit einem umfangreichen A1-Grundkurs.</p><div className="welcome-hero-actions"><button className="welcome-hero-primary" onClick={()=>focusAuth('register')}>Kostenlos starten <span>→</span></button><button className="welcome-hero-secondary" onClick={()=>focusAuth('login')}>Ich habe schon ein Konto</button></div><div className="welcome-trust-line"><span>✓ Keine Zahlungsdaten für Free</span><span>✓ Fortschritt pro Sprache gespeichert</span><span>✓ Mehrere Lernsprachen parallel</span></div>
  <div className="welcome-points"><article><span>01</span><div><strong>Starte mit deiner Sprache.</strong><p>Wähle beim ersten Start deine Ausgangssprache und deine Lernsprache. Später kannst du weitere Lernpfade hinzufügen und jederzeit wechseln.</p></div></article><article><span>02</span><div><strong>Lerne aktiv statt nur wiederzuerkennen.</strong><p>Übersetzen, Satzbau, Hören, Diktat und Sprechen sorgen dafür, dass du Sprache wirklich abrufen kannst.</p></div></article><article><span>03</span><div><strong>Dein Fortschritt bleibt erhalten.</strong><p>XP, Lektionen, Streak, CEFR-Level und adaptive Wiederholungen werden für jede Sprachkombination separat gespeichert.</p></div></article></div>
  <div className="welcome-level-rail" aria-label="Englischer CEFR Lernpfad"><span>A1</span><i/><span>A2</span><i/><span>B1</span><i/><span>B2</span><i/><span>C1</span><i/><span>C2</span></div>
  <div className="welcome-value-strip"><article><span>FREE</span><strong>Ein sinnvoller Einstieg, der dich wirklich weiterbringt.</strong><p>Lernpfade, Übersetzer, Hören, Sprechen, Wiederholung und Fortschritt als Basis.</p><em>0 €</em></article><article className="pro"><span>PRO</span><strong>Für Nutzer, die schneller und gezielter vorankommen wollen.</strong><p>KI-Coach, Fachsprache, intensiveres Training und tiefere Analyse.</p><em>19,99 € / Monat</em></article></div></section>
  <section className="welcome-auth-card" ref={authRef}><div className="welcome-auth-head"><span className="welcome-auth-mark">V</span><div><small>VOCABFAST KONTO</small><h2>{mode==='login'?'Willkommen zurück.':'Dein Lernkonto erstellen.'}</h2></div></div><div className="welcome-auth-tabs"><button className={mode==='login'?'active':''} onClick={()=>{setMode('login');setError('')}}>Anmelden</button><button className={mode==='register'?'active':''} onClick={()=>{setMode('register');setError('')}}>Registrieren</button></div>{notice&&<div className="welcome-notice">{notice}</div>}{mode==='register'&&<div className="welcome-register-promise"><strong>Dein Start:</strong><span>Konto → Sprachen wählen → Lernziel → bei Englisch Einstufung → persönlicher Lernpfad.</span></div>}<form onSubmit={submit}>{mode==='register'&&<label><span>Name</span><input ref={nameRef} autoComplete="name" value={name} onChange={event=>setName(event.target.value)} placeholder="Wie sollen wir dich nennen?" required minLength={2}/></label>}<label><span>E-Mail</span><input ref={emailRef} type="email" autoComplete="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="name@beispiel.at" required/></label><label><span>Passwort</span><input type="password" autoComplete={mode==='register'?'new-password':'current-password'} value={password} onChange={event=>setPassword(event.target.value)} placeholder={mode==='register'?'Mindestens 12 Zeichen':'Dein Passwort'} required minLength={mode==='register'?12:1}/></label>{error&&<div className="welcome-error">{error}</div>}<button className="welcome-submit" disabled={busy||!email||!password||(mode==='register'&&!name.trim())}>{busy?'Bitte warten …':mode==='login'?'Jetzt anmelden →':'Kostenloses Konto erstellen →'}</button></form><div className="welcome-card-note">{mode==='register'?<>Mit der Registrierung akzeptierst du unsere <a href={`${legalBase}/nutzungsbedingungen.html`}>Nutzungsbedingungen</a> und bestätigst, die <a href={`${legalBase}/datenschutz.html`}>Datenschutzhinweise</a> gelesen zu haben.</>:<>Deine gespeicherten Lernpfade werden nach der Anmeldung automatisch geladen.</>}</div><div className="welcome-security"><span>●</span><p><strong>Sicheres Lernkonto.</strong> Dein Fortschritt wird deinem Konto zugeordnet. Passwörter werden nicht im Klartext gespeichert.</p></div></section></main>
  <footer className="welcome-footer"><span>© {new Date().getFullYear()} VocabFast</span><nav aria-label="Rechtliche Informationen"><a href={`${legalBase}/impressum.html`}>Impressum</a><a href={`${legalBase}/datenschutz.html`}>Datenschutz</a><a href={`${legalBase}/nutzungsbedingungen.html`}>Nutzungsbedingungen</a><a href={`${legalBase}/widerruf.html`}>Widerruf</a></nav></footer></div>;
}
