(() => {
'use strict';
const $=(s,r=document)=>r.querySelector(s);
const ADMIN_ROUTE=location.pathname.replace(/\/+$/,'')==='/admin';
function meta(name,content,property=false){let el=document.head.querySelector(`meta[${property?'property':'name'}="${name}"]`);if(!el){el=document.createElement('meta');el.setAttribute(property?'property':'name',name);document.head.appendChild(el)}el.content=content}
function head(){if(ADMIN_ROUTE)return;let canonical=document.head.querySelector('link[rel="canonical"]');if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.appendChild(canonical)}canonical.href='https://vocabfast.net/';meta('robots','index,follow,max-image-preview:large');meta('og:title','VocabFast – Englisch effizient lernen',true);meta('og:description','Englisch, Fachsprache und Grammatik mit persönlichem Lernstand, Übungen und optionalen Elite-Funktionen.',true);meta('og:type','website',true);meta('og:url','https://vocabfast.net/',true)}
function consent(){const form=$('#registerForm');if(!form||$('#vfLegalConsent'))return;const button=form.querySelector('button[type="submit"]');if(!button)return;const wrap=document.createElement('label');wrap.id='vfLegalConsent';wrap.className='vf-legal-consent';wrap.innerHTML='<input type="checkbox" required> <span>Ich akzeptiere die <a href="/nutzungsbedingungen.html" target="_blank" rel="noopener">Nutzungsbedingungen</a> und habe die <a href="/datenschutz.html" target="_blank" rel="noopener">Datenschutzerklärung</a> zur Kenntnis genommen.</span>';button.before(wrap)}
function footer(){if(ADMIN_ROUTE||$('#vfSiteFooter'))return;const f=document.createElement('footer');f.id='vfSiteFooter';f.className='vf-site-footer';f.innerHTML=`<div class="vf-footer-inner"><div><strong>VocabFast</strong><span>English Learning Workspace</span></div><nav aria-label="Rechtliches"><a href="/impressum.html">Impressum</a><a href="/datenschutz.html">Datenschutz</a><a href="/nutzungsbedingungen.html">Nutzungsbedingungen</a><a href="/widerruf.html">Widerruf</a><a href="https://billing.stripe.com/p/login/cNi28qfQ24OA4sybh3ao800" target="_blank" rel="noopener">Abo verwalten / kündigen</a></nav><small>VocabFast-Kompetenznachweise und CEFR-Schätzungen sind Lernorientierungen und keine amtlich oder institutionell akkreditierten Sprachzertifikate.</small></div>`;document.body.appendChild(f)}
function skip(){if(ADMIN_ROUTE||$('#vfSkip'))return;const a=document.createElement('a');a.id='vfSkip';a.className='vf-skip-link';a.href='#mainContent';a.textContent='Zum Inhalt springen';document.body.prepend(a);const main=$('main');if(main&&!main.id)main.id='mainContent';if(main)main.tabIndex=-1}
function boot(){head();consent();skip();footer()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
