(() => {
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
let me=null;
const GATED_SELECTOR='#mainNav button[data-view="pdf"],#v8TestNav,#mainNav button[data-view="test"],#autoGenerateTopic,#exportLearn,.v8-mini-test,#v8StartGrammarTest,#v8StartVocabTest,#pdfInput,.filebtn,#selectAllPdf,#deleteSelectedPdf,#deleteAllPdf,.v9-preview-cert,.v9-download-cert,#v9CertDownload';
async function loadMe(){try{const r=await fetch('/api/me',{credentials:'same-origin'}),d=await r.json();me=d.user||null;return me}catch{return null}}
function isPro(){return me?.effectivePlan==='pro'}
function ensureModal(){if($('#v12ProModal'))return;document.body.insertAdjacentHTML('beforeend',`<div id="v12ProModal" class="v12-pro-modal"><div class="v12-pro-card"><div class="v12-pro-badge">VOCABFAST PRO</div><h2>Diese Funktion gehört zu Pro</h2><p id="v12ProReason">Mit Pro schaltest du zusätzliche Lern- und Prüfungsfunktionen frei.</p><div class="v12-pro-list"><span>PDF-Bibliothek & PDF-Analyse</span><span>KI-Fachwortlisten für eigene Themen</span><span>20-Fragen-Grammatik-Kapiteltests</span><span>50-Fragen-Kompetenztests & Urkunden</span><span>CSV-Export deiner Wortlisten</span></div><button class="btn primary" id="v12ProClose">Verstanden</button></div></div>`);$('#v12ProClose').onclick=()=>$('#v12ProModal').classList.remove('open');$('#v12ProModal').onclick=e=>{if(e.target.id==='v12ProModal')e.currentTarget.classList.remove('open')}}
function showPro(reason){ensureModal();$('#v12ProReason').textContent=reason||'Diese Funktion ist für VocabFast Pro reserviert.';$('#v12ProModal').classList.add('open')}
function badge(el){if(!el||el.querySelector?.('.v12-pro-tag'))return;const tag=document.createElement('span');tag.className='v12-pro-tag';tag.textContent='PRO';el.appendChild(tag)}
function markLocked(el){if(!el)return;el.dataset.v12ProLocked='1';el.setAttribute('aria-disabled','true');el.title='VocabFast Pro erforderlich';if(el.matches('button,.btn'))el.style.opacity='.72'}
function clearLocked(){$$('[data-v12-pro-locked="1"]').forEach(el=>{delete el.dataset.v12ProLocked;el.removeAttribute('aria-disabled');if(el.title==='VocabFast Pro erforderlich')el.removeAttribute('title');if(el.matches('button,.btn'))el.style.opacity=''});$$('.v12-pro-tag').forEach(x=>x.remove())}
function decorate(){if(!me)return;if(isPro()){clearLocked();return}const pdf=$('#mainNav button[data-view="pdf"]');if(pdf)badge(pdf);const test=$('#v8TestNav,#mainNav button[data-view="test"]');if(test)badge(test);const csv=$('#exportLearn');if(csv)badge(csv);const ai=$('#autoGenerateTopic');if(ai)badge(ai);$$('.v8-mini-test').forEach(badge);$$('.v9-preview-cert,.v9-download-cert').forEach(badge);$$(GATED_SELECTOR).forEach(markLocked);const card=$('#v8PlanCard');if(card&&!card.querySelector('.v12-free-note'))card.insertAdjacentHTML('beforeend','<div class="v12-free-note"><strong>VocabFast Free</strong><span>Grundfunktionen bleiben frei. PDF, KI-Fachwortlisten, Kapiteltests, Kompetenztests/Urkunden und CSV sind Pro-Funktionen.</span></div>')}
function reasonFor(target){if(target.matches('[data-view="pdf"],#pdfInput,.filebtn,#selectAllPdf,#deleteSelectedPdf,#deleteAllPdf'))return 'PDF-Bibliothek, PDF-Upload und PDF-Analyse sind VocabFast-Pro-Funktionen.';if(target.id==='autoGenerateTopic')return 'Die automatische KI-Fachworterstellung ist eine VocabFast-Pro-Funktion.';if(target.classList.contains('v8-mini-test'))return 'Der 20-Fragen-Kapiteltest mit dauerhafter Bewertung ist eine VocabFast-Pro-Funktion.';if(target.id==='exportLearn')return 'Der CSV-Export ist eine VocabFast-Pro-Funktion.';if(target.matches('.v9-preview-cert,.v9-download-cert,#v9CertDownload'))return 'Kompetenzurkunden und deren PDF-Download gehören zu VocabFast Pro.';if(target.id==='v8TestNav'||target.dataset.view==='test'||target.id==='v8StartGrammarTest'||target.id==='v8StartVocabTest')return '50-Fragen-Kompetenztests und Urkunden sind VocabFast-Pro-Funktionen.';return 'Diese Funktion ist für VocabFast Pro reserviert.'}
function lockClick(e){if(!me||isPro())return;const target=e.target.closest(GATED_SELECTOR);if(!target)return;e.preventDefault();e.stopImmediatePropagation();showPro(reasonFor(target))}
function forceAccountStart(){const b=$('#mainNav button[data-view="account"]');if(b){b.click();return}$$('.view').forEach(v=>v.classList.toggle('active',v.id==='view-account'));$$('#mainNav button').forEach(x=>x.classList.toggle('active',x.dataset.view==='account'));window.scrollTo({top:0,behavior:'instant'})}
async function start(){await loadMe();forceAccountStart();decorate();document.addEventListener('click',lockClick,true);document.addEventListener('click',e=>{if(e.target.closest('[data-view="account"],[data-view="grammar"],[data-view="topics"],[data-view="words"],[data-view="progress"]'))setTimeout(decorate,120)},true);setTimeout(decorate,400);setTimeout(decorate,1200)}
window.addEventListener('load',start);
})();
