(() => {
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
let me=null;
async function loadMe(){try{const r=await fetch('/api/me',{credentials:'same-origin'}),d=await r.json();me=d.user||null;return me}catch{return null}}
function isPro(){return me?.effectivePlan==='pro'}
function ensureModal(){if($('#v12ProModal'))return;document.body.insertAdjacentHTML('beforeend',`<div id="v12ProModal" class="v12-pro-modal"><div class="v12-pro-card"><div class="v12-pro-badge">VOCABFAST PRO</div><h2>Diese Funktion gehört zu Pro</h2><p id="v12ProReason">Mit Pro schaltest du zusätzliche Lern- und Prüfungsfunktionen frei.</p><div class="v12-pro-list"><span>PDF-Bibliothek & PDF-Analyse</span><span>KI-Fachwortlisten für eigene Themen</span><span>20-Fragen-Grammatik-Kapiteltests</span><span>50-Fragen-Kompetenztests & Urkunden</span><span>CSV-Export deiner Wortlisten</span></div><button class="btn primary" id="v12ProClose">Verstanden</button></div></div>`);$('#v12ProClose').onclick=()=>$('#v12ProModal').classList.remove('open');$('#v12ProModal').onclick=e=>{if(e.target.id==='v12ProModal')e.currentTarget.classList.remove('open')}}
function showPro(reason){ensureModal();$('#v12ProReason').textContent=reason||'Diese Funktion ist für VocabFast Pro reserviert.';$('#v12ProModal').classList.add('open')}
function badge(el){if(!el||el.querySelector?.('.v12-pro-tag'))return;const tag=document.createElement('span');tag.className='v12-pro-tag';tag.textContent='PRO';el.appendChild(tag)}
function decorate(){if(!me||isPro())return;const pdf=$('#mainNav button[data-view="pdf"]');if(pdf)badge(pdf);const test=$('#v8TestNav,#mainNav button[data-view="test"]');if(test)badge(test);const csv=$('#exportLearn');if(csv)badge(csv);const ai=$('#autoGenerateTopic');if(ai)badge(ai);$$('.v8-mini-test').forEach(badge);const card=$('#v8PlanCard');if(card&&!card.querySelector('.v12-free-note'))card.insertAdjacentHTML('beforeend','<div class="v12-free-note"><strong>Free</strong><span>Grundfunktionen bleiben frei. PDF, KI-Fachwortlisten, Kapiteltests, Zertifikatstests und CSV sind Pro.</span></div>')}
function lockClick(e){if(!me||isPro())return;const target=e.target.closest('#mainNav button[data-view="pdf"],#v8TestNav,#mainNav button[data-view="test"],#autoGenerateTopic,#exportLearn,.v8-mini-test,#v8StartGrammarTest,#v8StartVocabTest');if(!target)return;e.preventDefault();e.stopImmediatePropagation();let reason='Diese Funktion ist für VocabFast Pro reserviert.';if(target.matches('[data-view="pdf"]'))reason='PDF-Bibliothek, Upload und PDF-Analyse sind Pro-Funktionen.';else if(target.id==='autoGenerateTopic')reason='Die automatische KI-Fachworterstellung ist eine Pro-Funktion.';else if(target.classList.contains('v8-mini-test'))reason='Der 20-Fragen-Kapiteltest mit dauerhafter Bewertung ist eine Pro-Funktion.';else if(target.id==='exportLearn')reason='Der CSV-Export ist eine Pro-Funktion.';else if(target.id==='v8TestNav'||target.dataset.view==='test'||target.id==='v8StartGrammarTest'||target.id==='v8StartVocabTest')reason='Kompetenztests und Urkunden sind Pro-Funktionen.';showPro(reason)}
async function start(){await loadMe();decorate();document.addEventListener('click',lockClick,true);document.addEventListener('click',e=>{if(e.target.closest('[data-view="account"],[data-view="grammar"],[data-view="topics"],[data-view="words"]'))setTimeout(decorate,120)},true);setTimeout(decorate,500);setTimeout(decorate,1500)}
window.addEventListener('load',start);
})();
