(() => {
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const fmt=n=>Number(n||0).toLocaleString('de-DE');
let ctx=null,users=[],active=null,tab='account';
async function api(path,{method='GET',body=null}={}){const o={method,credentials:'same-origin',headers:{}};if(body!==null){o.headers['Content-Type']='application/json';o.body=JSON.stringify(body)}const r=await fetch(`/api${path}`,o);let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`Serverfehler ${r.status}`);return d}
function toast(m){const t=$('#toast');if(!t)return alert(m);t.textContent=m;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2600)}
function can(p){return !!ctx?.superadmin||ctx?.permissions?.includes(p)}
function initials(u){const s=(u.name||u.email||'?').trim(),a=s.split(/\s+/);return (a.length>1?a[0][0]+a.at(-1)[0]:s.slice(0,2)).toUpperCase()}
function tier(u){return u.effectivePlan==='pro'?'Elite':'Core'}
function mount(){const panel=$('#view-admin .panel');if(!panel||panel.dataset.v13==='1')return;panel.dataset.v13='1';panel.innerHTML=`<div class="v13-admin"><header class="v13-admin-head"><div><div class="eyebrow">Verwaltungszentrale</div><h1>VocabFast Administration</h1><p class="muted">Konten, Lernfortschritt, Prüfungen, PDFs, Elite-Zugänge und Helferrechte an einem Ort.</p></div><div class="v13-head-actions"><button class="btn" id="v13Reload">Aktualisieren</button><button class="btn primary" id="v13Create">+ Konto anlegen</button></div></header><div id="v13Stats" class="v13-stats"></div><div class="v13-layout"><aside class="v13-users"><input id="v13Search" type="search" placeholder="Name oder E-Mail suchen …" autocomplete="off"><div id="v13UserList" class="v13-user-list"></div></aside><section id="v13Workspace" class="v13-workspace"><div class="empty">Wähle links ein Konto aus.</div></section></div></div><div id="v13Modal" class="v13-modal"><div class="v13-modal-card"><div class="v13-modal-head"><h2>Neues Konto</h2><button class="btn" id="v13ModalClose">Schließen</button></div><div class="v13-form"><label>Name<input id="v13NewName"></label><label>E-Mail<input id="v13NewEmail" type="email"></label><label>Temporäres Passwort<input id="v13NewPassword" type="text" minlength="12"></label><label>Stufe<select id="v13NewPlan"><option value="free">VocabFast Core</option><option value="pro">VocabFast Elite</option></select></label></div><button class="btn primary" id="v13CreateSubmit">Konto erstellen</button></div></div>`;
 $('#v13Reload').onclick=load;$('#v13Search').oninput=renderUsers;$('#v13Create').onclick=()=>$('#v13Modal').classList.add('open');$('#v13ModalClose').onclick=()=>$('#v13Modal').classList.remove('open');$('#v13CreateSubmit').onclick=createUser;
 if(!can('accounts.manage'))$('#v13Create').style.display='none';
}
async function load(){try{ctx=await api('/admin/context');mount();const d=await api('/admin/users');users=d.users||[];renderStats();renderUsers();if(active){const found=users.find(x=>x.id===active.id);if(found)await openUser(found.id)}}catch(e){console.warn(e)}}
function renderStats(){const pro=users.filter(x=>x.effectivePlan==='pro').length,locked=users.filter(x=>x.disabled).length;$('#v13Stats').innerHTML=[['Konten',users.length],['VocabFast Elite',pro],['Gesperrt',locked],['Gesamt-XP',fmt(users.reduce((a,x)=>a+Number(x.xp||0),0))],['Wörter',fmt(users.reduce((a,x)=>a+Number(x.words||0),0))]].map(([a,b])=>`<div><span>${a}</span><strong>${b}</strong></div>`).join('')}
function renderUsers(){const q=($('#v13Search')?.value||'').toLowerCase(),box=$('#v13UserList');if(!box)return;const rows=users.filter(u=>!q||`${u.name} ${u.email}`.toLowerCase().includes(q));box.innerHTML=rows.map(u=>`<button class="v13-user ${active?.id===u.id?'active':''}" data-id="${u.id}"><span class="v13-avatar">${esc(initials(u))}</span><span><strong>${esc(u.name||u.email)}</strong><small>${esc(u.email)}</small><em>${tier(u)} · ${fmt(u.xp)} XP · ${fmt(u.words)} Wörter${u.disabled?' · GESPERRT':''}</em></span></button>`).join('')||'<div class="empty">Keine Konten gefunden.</div>';$$('.v13-user',box).forEach(b=>b.onclick=()=>openUser(b.dataset.id))}
async function openUser(id){try{const d=await api(`/admin/users/${id}`);active={...d.profile,state:d.state||{}};renderUsers();renderWorkspace()}catch(e){toast(e.message)}}
function tabs(){const items=[['account','Konto'],['progress','Fortschritt'],['tests','Prüfungen'],['pdfs','PDFs'],['rights','Helferrechte'],['security','Sicherheit']];return items.filter(([k])=>k!=='rights'||ctx?.superadmin).map(([k,l])=>`<button class="${tab===k?'active':''}" data-tab="${k}">${l}</button>`).join('')}
function renderWorkspace(){const u=active,w=$('#v13Workspace');if(!u)return;w.innerHTML=`<div class="v13-profile"><div class="v13-avatar big">${esc(initials(u))}</div><div><h2>${esc(u.name||u.email)}</h2><p>${esc(u.email)}</p><div class="v13-badges"><span>${tier(u)}</span>${u.disabled?'<span class="danger">Gesperrt</span>':''}</div></div></div><nav class="v13-tabs">${tabs()}</nav><div id="v13Tab"></div>`;$$('.v13-tabs button',w).forEach(b=>b.onclick=()=>{tab=b.dataset.tab;renderWorkspace()});renderTab()}
function renderTab(){const box=$('#v13Tab');if(tab==='account')accountTab(box);if(tab==='progress')progressTab(box);if(tab==='tests')testsTab(box);if(tab==='pdfs')pdfsTab(box);if(tab==='rights')rightsTab(box);if(tab==='security')securityTab(box)}
function accountTab(box){box.innerHTML=`<div class="v13-card"><h3>Kontodaten</h3><div class="v13-form"><label>Name<input id="aName" value="${esc(active.name||'')}"></label><label>E-Mail<input id="aEmail" value="${esc(active.email||'')}"></label><label>Stufe<select id="aPlan"><option value="free" ${active.plan!=='pro'?'selected':''}>VocabFast Core</option><option value="pro" ${active.plan==='pro'?'selected':''}>VocabFast Elite</option></select></label><label>Elite bis (optional)<input id="aUntil" type="date" value="${active.proUntil?new Date(active.proUntil).toISOString().slice(0,10):''}"></label><label class="full">Admin-Notiz<textarea id="aNote" rows="4">${esc(active.adminNote||'')}</textarea></label><label class="check full"><input id="aDisabled" type="checkbox" ${active.disabled?'checked':''}> Konto sperren</label></div><button class="btn primary" id="aSave">Änderungen speichern</button></div>`;if(!can('users.edit')&&!can('plans.manage'))$('#aSave').disabled=true;$('#aSave').onclick=async()=>{try{const body={};if(can('users.edit'))Object.assign(body,{name:$('#aName').value,email:$('#aEmail').value,adminNote:$('#aNote').value,disabled:$('#aDisabled').checked});if(can('plans.manage'))Object.assign(body,{plan:$('#aPlan').value,proUntil:$('#aUntil').value?new Date($('#aUntil').value+'T23:59:59').toISOString():null});await api(`/admin/users/${active.id}`,{method:'PUT',body});toast('Kontodaten gespeichert');await load()}catch(e){toast(e.message)}}}
async function progressTab(box){box.innerHTML='<div class="empty">Fortschritt wird geladen …</div>';try{const d=await api(`/admin/users/${active.id}/progress`),s=d.stats||{};box.innerHTML=`<div class="v13-card"><h3>Fortschritt direkt bearbeiten</h3><div class="v13-metrics"><label>XP<input id="pXp" type="number" min="0" value="${Number(s.xp)||0}"></label><label>Vokabel beantwortet<input id="pVA" type="number" min="0" value="${Number(s.vocabAnswered)||0}"></label><label>Vokabel richtig<input id="pVC" type="number" min="0" value="${Number(s.vocabCorrect)||0}"></label><label>Grammatik beantwortet<input id="pGA" type="number" min="0" value="${Number(s.grammarAnswered)||0}"></label><label>Grammatik richtig<input id="pGC" type="number" min="0" value="${Number(s.grammarCorrect)||0}"></label></div><div class="v13-summary"><span>${fmt(d.learningCount)} gespeicherte Wörter</span><span>${fmt(d.testCount)} Prüfungen</span></div><button class="btn primary" id="pSave">Fortschritt speichern</button></div>`;$('#pSave').disabled=!can('progress.edit');$('#pSave').onclick=async()=>{try{await api(`/admin/users/${active.id}/progress`,{method:'PUT',body:{xp:+$('#pXp').value,vocabAnswered:+$('#pVA').value,vocabCorrect:+$('#pVC').value,grammarAnswered:+$('#pGA').value,grammarCorrect:+$('#pGC').value}});toast('Fortschritt gespeichert');await load()}catch(e){toast(e.message)}}}catch(e){box.innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
async function testsTab(box){box.innerHTML='<div class="empty">Prüfungen werden geladen …</div>';try{const d=await api(`/admin/users/${active.id}/tests`),tests=d.tests||[],scores=d.grammarScores||{};box.innerHTML=`<div class="v13-card"><div class="v13-section-head"><div><h3>Prüfungen & Urkunden</h3><p class="muted">Einzelne Einträge löschen oder komplette Bereiche zurücksetzen.</p></div><button class="btn danger" id="tClear">Alle Prüfungen & Urkunden löschen</button></div><div class="v13-list">${tests.length?tests.map((t,i)=>`<div class="v13-test"><div><strong>${esc(t.title||'Test')}</strong><small>${esc(t.kind||'')} · ${Number(t.percent)||0}% · ${t.passed?'bestanden':'nicht bestanden'}</small></div><button class="btn" data-del="${i}">Löschen</button></div>`).join(''):'<div class="empty">Keine Prüfungen vorhanden.</div>'}</div></div><div class="v13-card"><div class="v13-section-head"><h3>Grammatikbewertungen</h3><button class="btn danger" id="gClear">Alle zurücksetzen</button></div><div class="v13-list">${Object.entries(scores).map(([k,v])=>`<div class="v13-test"><strong>${esc(k)}</strong><span>${Number(v.percent)||0}%</span></div>`).join('')||'<div class="empty">Keine Bewertungen.</div>'}</div></div>`;const editable=can('tests.edit');$('#tClear').disabled=!editable;$('#gClear').disabled=!editable;$('#tClear').onclick=()=>updateTests({action:'clearTests'});$('#gClear').onclick=()=>updateTests({action:'clearGrammar'});$$('[data-del]',box).forEach(b=>{b.disabled=!editable;b.onclick=()=>{tests.splice(+b.dataset.del,1);updateTests({tests})}})}catch(e){box.innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
async function updateTests(body){if(!confirm('Diese Änderung wirklich durchführen?'))return;try{await api(`/admin/users/${active.id}/tests`,{method:'PUT',body});toast('Prüfungsdaten aktualisiert');testsTab($('#v13Tab'))}catch(e){toast(e.message)}}
async function pdfsTab(box){box.innerHTML='<div class="empty">PDFs werden geladen …</div>';try{const d=await api(`/admin/users/${active.id}/pdfs`),rows=d.pdfs||[];box.innerHTML=`<div class="v13-card"><div class="v13-section-head"><div><h3>PDF-Bibliothek</h3><p class="muted">Direkt herunterladen oder löschen.</p></div>${can('pdfs.manage')?'<button class="btn danger" id="pdfClear">Alle PDFs löschen</button>':''}</div><div class="v13-list">${rows.length?rows.map(p=>`<div class="v13-pdf" data-id="${esc(p.id)}"><span class="v13-pdf-icon">PDF</span><div><strong>${esc(p.name||'Dokument.pdf')}</strong><small>${new Date(p.created||Date.now()).toLocaleString('de-DE')} · ${Math.round(Number(p.size||0)/1024)} KB</small></div><button class="btn dl">Download</button>${can('pdfs.manage')?'<button class="btn danger del">Löschen</button>':''}</div>`).join(''):'<div class="empty">Keine PDFs gespeichert.</div>'}</div></div>`;$$('.v13-pdf .dl',box).forEach(b=>b.onclick=async()=>{const row=b.closest('.v13-pdf'),r=await fetch(`/api/admin/users/${active.id}/pdfs/${row.dataset.id}/file`,{credentials:'same-origin'});if(!r.ok)return toast('Download fehlgeschlagen');const blob=await r.blob(),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=row.querySelector('strong').textContent;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});$$('.v13-pdf .del',box).forEach(b=>b.onclick=async()=>{if(!confirm('PDF löschen?'))return;await api(`/admin/users/${active.id}/pdfs/${b.closest('.v13-pdf').dataset.id}`,{method:'DELETE'});toast('PDF gelöscht');pdfsTab(box)});$('#pdfClear')?.addEventListener('click',async()=>{if(!confirm('Alle PDFs dieses Kontos löschen?'))return;await api(`/admin/users/${active.id}/pdfs`,{method:'DELETE'});pdfsTab(box)})}catch(e){box.innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
async function rightsTab(box){if(!ctx?.superadmin){box.innerHTML='<div class="empty">Nur der Superadmin kann Helferrechte vergeben.</div>';return}const d=await api(`/admin/users/${active.id}/permissions`),cur=new Set(d.permissions||[]),opts=[['users.read','Benutzer ansehen'],['users.edit','Kontodaten bearbeiten'],['progress.edit','Fortschritt bearbeiten'],['tests.edit','Prüfungen & Urkunden bearbeiten'],['pdfs.manage','PDFs verwalten'],['plans.manage','Elite-Zugänge verwalten'],['security.manage','Passwörter & Sitzungen verwalten'],['accounts.manage','Konten erstellen/löschen']];box.innerHTML=`<div class="v13-card"><h3>Administrative Sonderrechte</h3><p class="muted">Gib Helfern nur die Rechte, die sie wirklich benötigen.</p><div class="v13-rights">${opts.map(([v,l])=>`<label><input type="checkbox" value="${v}" ${cur.has(v)?'checked':''}><span><strong>${l}</strong><small>${v}</small></span></label>`).join('')}</div><button class="btn primary" id="rSave">Rechte speichern</button></div>`;$('#rSave').onclick=async()=>{const permissions=$$('.v13-rights input:checked').map(x=>x.value);await api(`/admin/users/${active.id}/permissions`,{method:'PUT',body:{permissions}});toast('Helferrechte gespeichert')}}
function securityTab(box){box.innerHTML=`<div class="v13-card"><h3>Kontohilfe & Sicherheit</h3><label>Temporäres Passwort<input id="sPw" type="password" minlength="12" placeholder="mindestens 12 Zeichen"></label><div class="v13-actions"><button class="btn" id="sReset">Temporäres Passwort setzen</button><button class="btn" id="sSessions">Alle Sitzungen abmelden</button>${can('accounts.manage')?'<button class="btn danger" id="sDelete">Konto endgültig löschen</button>':''}</div></div>`;$('#sReset').disabled=!can('security.manage');$('#sSessions').disabled=!can('security.manage');$('#sReset').onclick=async()=>{try{await api(`/admin/users/${active.id}/password`,{method:'POST',body:{password:$('#sPw').value}});toast('Temporäres Passwort gesetzt')}catch(e){toast(e.message)}};$('#sSessions').onclick=async()=>{if(!confirm('Alle Sitzungen beenden?'))return;await api(`/admin/users/${active.id}/sessions`,{method:'DELETE'});toast('Sitzungen beendet')};$('#sDelete')?.addEventListener('click',async()=>{if(!confirm('Konto endgültig löschen?'))return;if(!confirm('Diese Aktion kann nicht rückgängig gemacht werden. Fortfahren?'))return;await api(`/admin/users/${active.id}`,{method:'DELETE'});active=null;toast('Konto gelöscht');load()})}
async function createUser(){try{const name=$('#v13NewName').value.trim(),email=$('#v13NewEmail').value.trim(),password=$('#v13NewPassword').value,plan=$('#v13NewPlan').value;if(password.length<12)throw new Error('Temporäres Passwort muss mindestens 12 Zeichen haben.');const r=await fetch('/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,email,password})}),d=await r.json();if(!r.ok)throw new Error(d.error||'Konto konnte nicht erstellt werden.');const id=d.user?.id;if(!id)throw new Error('Benutzer-ID fehlt.');await api(`/admin/users/${id}/password`,{method:'POST',body:{password}});if(plan==='pro')await api(`/admin/users/${id}`,{method:'PUT',body:{plan:'pro',proUntil:null}});$('#v13Modal').classList.remove('open');toast('Konto erstellt');load()}catch(e){toast(e.message)}}
async function boot(){try{ctx=await api('/admin/context');mount();load()}catch{}setTimeout(boot,1800)}
window.addEventListener('load',()=>setTimeout(boot,250));
})();
