(() => {
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let me=null;
async function api(path,{method='GET',body=null}={}){const o={method,credentials:'same-origin',headers:{}};if(body!==null){o.headers['Content-Type']='application/json';o.body=JSON.stringify(body)}const r=await fetch(`/api${path}`,o);let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`Serverfehler ${r.status}`);return d}
function isElite(){return me?.effectivePlan==='pro'||me?.tier==='elite'}
function toast(m){const t=$('#toast');if(!t)return alert(m);t.textContent=m;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2800)}
function ensureUpgradeModal(){if($('#v13UpgradeModal'))return;document.body.insertAdjacentHTML('beforeend',`<div id="v13UpgradeModal" class="v13-upgrade-modal"><div class="v13-upgrade-card"><span class="v13-elite-badge">VOCABFAST ELITE</span><h2>Mehr aus VocabFast herausholen</h2><p>Mit VocabFast Elite bekommst du PDF-Lernen, KI-Fachwortlisten, große Grammatiktests, Kompetenztests, Urkunden und Exportfunktionen.</p><div class="v13-elite-benefits"><span>PDF-Bibliothek & Analyse</span><span>KI-Fachwortgenerator</span><span>20- und 50-Fragen-Tests</span><span>Urkunden & Kompetenznachweise</span><span>CSV-Export</span></div><button class="btn primary" id="v13Subscribe">VocabFast Elite monatlich abonnieren</button><button class="btn" id="v13UpgradeClose">Später</button><p id="v13BillingHint" class="muted tiny"></p></div></div>`);$('#v13UpgradeClose').onclick=()=>$('#v13UpgradeModal').classList.remove('open');$('#v13Subscribe').onclick=checkout}
function openUpgrade(){ensureUpgradeModal();$('#v13UpgradeModal').classList.add('open')}
async function checkout(){const hint=$('#v13BillingHint');try{hint.textContent='Checkout wird geöffnet …';const d=await api('/billing/checkout',{method:'POST'});location.href=d.checkoutUrl}catch(e){hint.textContent=e.message}}
function lockSurface(sel,label){const el=$(sel);if(!el||el.dataset.v13Lock==='1')return;el.dataset.v13Lock='1';el.classList.add('v13-elite-locked');el.insertAdjacentHTML('beforeend',`<div class="v13-elite-overlay"><span class="v13-elite-badge">ELITE</span><strong>${esc(label)}</strong><p>Diese Funktion gehört zu VocabFast Elite.</p><button class="btn primary">Auf VocabFast Elite upgraden</button></div>`);$('.v13-elite-overlay button',el).onclick=openUpgrade}
function lockButton(btn){if(!btn||btn.dataset.v13Lock==='1')return;btn.dataset.v13Lock='1';btn.disabled=true;btn.classList.add('v13-inline-locked');const u=document.createElement('button');u.className='btn v13-inline-upgrade';u.textContent='Elite';u.onclick=openUpgrade;btn.after(u)}
function applyTierUi(){if(!me)return;const badge=$('#v8PlanBadge');if(badge){badge.textContent=isElite()?'ELITE':'CORE';badge.classList.remove('v8-hidden')}const plan=$('#v8PlanText');if(plan)plan.textContent=isElite()?'VocabFast Elite':'VocabFast Core';if(isElite())return;lockSurface('#view-pdf .panel','PDF-Bibliothek & PDF-Lernen');lockSurface('#view-test .panel','Kompetenztests & Urkunden');for(const b of $$('button')){const t=b.textContent.trim();if(/20-Fragen-Kapiteltest|50-Fragen|automatisch füllen|CSV/i.test(t))lockButton(b)}for(const b of $$('.v9-download-cert,.v9-preview-cert,.v8-certificate-download'))lockButton(b)}
async function activateStaff(){if(!me?.staffPermissions?.length||$('#v8AdminNav')||sessionStorage.getItem('vf_staff_try')==='1')return;sessionStorage.setItem('vf_staff_try','1');try{await api('/staff/activate',{method:'POST'});location.reload()}catch{}}
function certPrint(t,name){const areas=(t.areas||[]).map(a=>`<li>${esc(a)}</li>`).join(''),w=window.open('','_blank','noopener,noreferrer,width=900,height=1100');if(!w)return toast('Pop-up wurde blockiert.');w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>VocabFast Urkunde</title><style>@page{size:A4 portrait;margin:0}*{box-sizing:border-box}body{margin:0;background:#dfe7ee;font-family:Arial,sans-serif;color:#132231}.sheet{width:210mm;min-height:297mm;margin:auto;background:#f8fbfd;position:relative;overflow:hidden}.head{height:72mm;background:#0d1822;color:white;padding:22mm 18mm 14mm;border-left:5mm solid #83ef2d}.brand{letter-spacing:.22em;color:#d9ae40;font-weight:900;font-size:14pt}.head h1{font-size:30pt;margin:11mm 0 3mm}.head p{color:#bacbd8}.body{padding:15mm 18mm}.label{font-size:8pt;letter-spacing:.13em;color:#ae8424;font-weight:900}.name{font-size:25pt;font-weight:900;margin:4mm 0 8mm}.title{background:#132331;color:white;border-radius:4mm;padding:5mm 6mm;font-size:16pt;font-weight:900}.score{display:grid;grid-template-columns:1fr 1fr 1fr;gap:4mm;margin:7mm 0}.score div{border:1px solid #cbd7e0;border-radius:4mm;padding:5mm;background:white}.score div:first-child{background:#10202d;color:#9cff55;border-left:3mm solid #83ef2d}.score small{display:block;text-transform:uppercase;color:#7c91a4;font-size:7pt}.score strong{display:block;font-size:20pt;margin-top:2mm}.areas{border:1px solid #cbd7e0;border-radius:4mm;padding:6mm;background:white}.areas h3{margin-top:0}.areas li{margin:2mm 0}.foot{position:absolute;left:18mm;right:18mm;bottom:14mm;border-top:1px solid #cbd7e0;padding-top:5mm;display:flex;justify-content:space-between;color:#63798c;font-size:8pt}.no-print{position:fixed;right:20px;top:20px}@media print{body{background:white}.sheet{margin:0}.no-print{display:none}}</style></head><body><button class="no-print" onclick="print()">Drucken / als PDF speichern</button><main class="sheet"><header class="head"><div class="brand">VOCABFAST</div><h1>KOMPETENZURKUNDE</h1><p>Professioneller digitaler Kompetenznachweis</p></header><section class="body"><div class="label">AUSGESTELLT FÜR</div><div class="name">${esc(name)}</div><p>Diese Urkunde bestätigt das erfolgreiche Bestehen der VocabFast-Kompetenzprüfung.</p><div class="title">${esc(t.title||'VocabFast Kompetenztest')}</div><div class="score"><div><small>Ergebnis</small><strong>${Number(t.percent)||0}%</strong></div><div><small>Richtig</small><strong>${Number(t.correct)||0}/${Number(t.total)||0}</strong></div><div><small>Status</small><strong>Bestanden</strong></div></div><div class="areas"><h3>Tatsächlich geprüfte Bereiche</h3><ul>${areas||'<li>Geprüfte Inhalte laut Testprotokoll</li>'}</ul></div></section><footer class="foot"><span>${new Date(t.date||Date.now()).toLocaleDateString('de-DE')}</span><span>${esc(t.certId||t.id||'VocabFast')}</span><span>VocabFast Kompetenznachweis</span></footer></main></body></html>`);w.document.close()}
async function renderAllCertificates(){const host=$('#v9CertificateArchive')||$('#v8CertificateArchive');if(!host)return;try{const s=await api('/state'),tests=Array.isArray(s.state?.testHistory)?s.state.testHistory:[],certs=tests.filter(t=>t?.passed),name=me?.name||me?.email||'VocabFast Nutzer';host.innerHTML=certs.length?certs.map((t,i)=>`<article class="v13-cert" data-i="${i}"><div><span class="v13-elite-badge">URKUNDE</span><h3>${esc(t.title||'Kompetenztest')}</h3><p>${esc((t.areas||[]).join(', '))}</p><small>${new Date(t.date||Date.now()).toLocaleDateString('de-DE')} · ${Number(t.percent)||0}%</small></div><button class="btn primary v13-cert-open">${isElite()?'Öffnen / PDF':'Elite erforderlich'}</button></article>`).join(''):'<div class="empty">Noch keine bestandenen Urkunden vorhanden.</div>';$$('.v13-cert',host).forEach(card=>$('.v13-cert-open',card).onclick=()=>isElite()?certPrint(certs[+card.dataset.i],name):openUpgrade())}catch{}}
async function boot(){ensureUpgradeModal();try{const d=await api('/me');me=d.user||null;if(me){await activateStaff();applyTierUi();renderAllCertificates()}}catch{}setTimeout(()=>{applyTierUi();renderAllCertificates()},1200)}
window.addEventListener('load',()=>setTimeout(boot,350));document.addEventListener('click',e=>{if(e.target.closest('[data-view="pdf"],[data-view="test"],[data-view="progress"],[data-view="grammar"]'))setTimeout(()=>{applyTierUi();renderAllCertificates()},180)},true);new MutationObserver(()=>{clearTimeout(window.__v13ui);window.__v13ui=setTimeout(()=>{applyTierUi();renderAllCertificates()},250)}).observe(document.documentElement,{childList:true,subtree:true});
})();
