import type { Lesson } from '../types';

type Card={title:string;subtitle:string;de:string;hr:string;meaning:string;concept:string;choices:string[]};
type Unit={id:string;number:number;title:string;subtitle:string;cards:Card[]};

const units:Unit[]=[
  {id:'hr-a2-u1',number:5,title:'Planovi i iskustva',subtitle:'Über Pläne, Erlebnisse und zeitliche Abläufe sprechen.',cards:[
    {title:'Wochenendpläne',subtitle:'Vorhaben natürlich ankündigen.',de:'Am Wochenende werde ich meine Freunde in Zagreb besuchen.',hr:'Za vikend ću posjetiti prijatelje u Zagrebu.',meaning:'Am Wochenende werde ich meine Freunde in Zagreb besuchen.',concept:'hr.a2.future-plan',choices:['Za vikend ću posjetiti prijatelje u Zagrebu.','Jučer sam bio u Zagrebu.','Svaki dan radim do pet.','Možda pada kiša.']},
    {title:'Vergangenheit erzählen',subtitle:'Ein Erlebnis kurz berichten.',de:'Gestern sind wir ans Meer gefahren und haben dort zu Mittag gegessen.',hr:'Jučer smo išli na more i tamo ručali.',meaning:'Gestern sind wir ans Meer gefahren und haben dort zu Mittag gegessen.',concept:'hr.a2.past-experience',choices:['Jučer smo išli na more i tamo ručali.','Sutra idemo na more.','More je danas hladno.','Ručak je u podne.']},
    {title:'Zeitliche Reihenfolge',subtitle:'Ereignisse sinnvoll verbinden.',de:'Zuerst trinken wir einen Kaffee, danach gehen wir einkaufen.',hr:'Prvo ćemo popiti kavu, a zatim idemo u kupovinu.',meaning:'Zuerst trinken wir einen Kaffee, danach gehen wir einkaufen.',concept:'hr.a2.sequence',choices:['Prvo ćemo popiti kavu, a zatim idemo u kupovinu.','Kava je bila preskupa.','Kupujem samo kruh.','Nisam pio kavu.']},
    {title:'Erfahrungen vergleichen',subtitle:'Vorlieben begründen.',de:'Ich war schon zweimal in Split, aber Dubrovnik gefällt mir besser.',hr:'Već sam dva puta bio u Splitu, ali Dubrovnik mi se više sviđa.',meaning:'Ich war schon zweimal in Split, aber Dubrovnik gefällt mir besser.',concept:'hr.a2.comparison-experience',choices:['Već sam dva puta bio u Splitu, ali Dubrovnik mi se više sviđa.','Split je dva sata udaljen.','Nikad nisam bio na moru.','Dubrovnik je manji hotel.']}
  ]},
  {id:'hr-a2-u2',number:6,title:'Problemi i rješenja',subtitle:'Probleme erklären, höflich reklamieren und Lösungen vereinbaren.',cards:[
    {title:'Hotelproblem erklären',subtitle:'Ein Problem klar beschreiben.',de:'Die Klimaanlage in meinem Zimmer funktioniert nicht. Können Sie sie bitte prüfen?',hr:'Klima-uređaj u mojoj sobi ne radi. Možete li ga, molim vas, provjeriti?',meaning:'Die Klimaanlage in meinem Zimmer funktioniert nicht. Können Sie sie bitte prüfen?',concept:'hr.a2.hotel-problem',choices:['Klima-uređaj u mojoj sobi ne radi. Možete li ga, molim vas, provjeriti?','Soba je spremna za vas.','Želim rezervirati stol.','Klimu koristim kod kuće.']},
    {title:'Im Restaurant reklamieren',subtitle:'Höflich auf einen Fehler hinweisen.',de:'Entschuldigung, ich glaube, das ist nicht das Gericht, das ich bestellt habe.',hr:'Oprostite, mislim da ovo nije jelo koje sam naručio.',meaning:'Entschuldigung, ich glaube, das ist nicht das Gericht, das ich bestellt habe.',concept:'hr.a2.restaurant-complaint',choices:['Oprostite, mislim da ovo nije jelo koje sam naručio.','Jelo je bilo izvrsno.','Naručit ću isto jelo.','Račun je na stolu.']},
    {title:'Alternative erfragen',subtitle:'Nach einer anderen Lösung fragen.',de:'Gibt es vielleicht einen späteren Bus, wenn wir diesen verpassen?',hr:'Postoji li možda kasniji autobus ako propustimo ovaj?',meaning:'Gibt es vielleicht einen späteren Bus, wenn wir diesen verpassen?',concept:'hr.a2.alternative',choices:['Postoji li možda kasniji autobus ako propustimo ovaj?','Autobus je već stigao.','Ne volim putovati autobusom.','Stanica je lijevo.']},
    {title:'Lösung bestätigen',subtitle:'Eine Vereinbarung absichern.',de:'In Ordnung, dann treffen wir uns um halb sieben vor dem Hotel.',hr:'U redu, onda se nalazimo u pola sedam ispred hotela.',meaning:'In Ordnung, dann treffen wir uns um halb sieben vor dem Hotel.',concept:'hr.a2.arrangement',choices:['U redu, onda se nalazimo u pola sedam ispred hotela.','Hotel otvara u sedam.','Ne znam gdje je hotel.','Jučer smo bili u hotelu.']}
  ]},
  {id:'hr-a2-u3',number:7,title:'Posao i svakodnevica',subtitle:'Arbeit, Termine, Aufgaben und Alltag genauer beschreiben.',cards:[
    {title:'Arbeitsaufgabe erklären',subtitle:'Eine aktuelle Aufgabe beschreiben.',de:'Diese Woche arbeite ich an einem neuen Projekt und habe viele Besprechungen.',hr:'Ovaj tjedan radim na novom projektu i imam mnogo sastanaka.',meaning:'Diese Woche arbeite ich an einem neuen Projekt und habe viele Besprechungen.',concept:'hr.a2.work-project',choices:['Ovaj tjedan radim na novom projektu i imam mnogo sastanaka.','Projekt je završio prošle godine.','Ne radim vikendom.','Sastanak traje pet minuta.']},
    {title:'Termin verschieben',subtitle:'Höflich einen anderen Zeitpunkt vorschlagen.',de:'Könnten wir den Termin auf Donnerstagvormittag verschieben?',hr:'Bismo li mogli pomaknuti sastanak na četvrtak ujutro?',meaning:'Könnten wir den Termin auf Donnerstagvormittag verschieben?',concept:'hr.a2.reschedule',choices:['Bismo li mogli pomaknuti sastanak na četvrtak ujutro?','Četvrtak je moj slobodan dan.','Sastanak je bio jučer.','Ujutro pijem čaj.']},
    {title:'Grund nennen',subtitle:'Eine Entscheidung einfach begründen.',de:'Ich fahre heute mit dem Zug, weil mein Auto in der Werkstatt ist.',hr:'Danas idem vlakom jer je moj auto u servisu.',meaning:'Ich fahre heute mit dem Zug, weil mein Auto in der Werkstatt ist.',concept:'hr.a2.reason',choices:['Danas idem vlakom jer je moj auto u servisu.','Vlak je skuplji od auta.','Servis je pokraj kolodvora.','Auto je nov.']},
    {title:'Häufigkeit beschreiben',subtitle:'Gewohnheiten differenzierter ausdrücken.',de:'Normalerweise koche ich zu Hause, aber zwei- oder dreimal pro Woche esse ich auswärts.',hr:'Obično kuham kod kuće, ali dva ili tri puta tjedno jedem vani.',meaning:'Normalerweise koche ich zu Hause, aber zwei- oder dreimal pro Woche esse ich auswärts.',concept:'hr.a2.frequency',choices:['Obično kuham kod kuće, ali dva ili tri puta tjedno jedem vani.','Danas neću kuhati.','Restoran je zatvoren.','Kuhinja je mala.']}
  ]},
  {id:'hr-a2-u4',number:8,title:'Mišljenja i odluke',subtitle:'Meinungen, Vergleiche und einfache Empfehlungen ausdrücken.',cards:[
    {title:'Meinung äußern',subtitle:'Eine persönliche Einschätzung formulieren.',de:'Meiner Meinung nach ist diese Route schöner, obwohl sie etwas länger dauert.',hr:'Po mom mišljenju, ova je ruta ljepša iako traje malo duže.',meaning:'Meiner Meinung nach ist diese Route schöner, obwohl sie etwas länger dauert.',concept:'hr.a2.opinion',choices:['Po mom mišljenju, ova je ruta ljepša iako traje malo duže.','Ruta počinje kod hotela.','Ne znam koliko traje.','Jučer smo hodali dugo.']},
    {title:'Vor- und Nachteil',subtitle:'Zwei Möglichkeiten vergleichen.',de:'Das Apartment ist günstiger, aber das Hotel liegt näher am Zentrum.',hr:'Apartman je jeftiniji, ali hotel je bliže centru.',meaning:'Das Apartment ist günstiger, aber das Hotel liegt näher am Zentrum.',concept:'hr.a2.pro-con',choices:['Apartman je jeftiniji, ali hotel je bliže centru.','Hotel je zatvoren.','Apartman ima dvije sobe.','Centar je vrlo star.']},
    {title:'Empfehlung geben',subtitle:'Einen praktischen Rat formulieren.',de:'Wenn du nur einen Tag hast, würde ich früh am Morgen losfahren.',hr:'Ako imaš samo jedan dan, preporučio bih da kreneš rano ujutro.',meaning:'Wenn du nur einen Tag hast, würde ich früh am Morgen losfahren.',concept:'hr.a2.recommendation',choices:['Ako imaš samo jedan dan, preporučio bih da kreneš rano ujutro.','Jutro je bilo hladno.','Put traje jedan dan.','Nisam još krenuo.']},
    {title:'Unsicherheit ausdrücken',subtitle:'Vorsichtig und natürlich antworten.',de:'Ich bin mir nicht sicher, aber ich glaube, dass das Museum sonntags geöffnet ist.',hr:'Nisam siguran, ali mislim da je muzej otvoren nedjeljom.',meaning:'Ich bin mir nicht sicher, aber ich glaube, dass das Museum sonntags geöffnet ist.',concept:'hr.a2.uncertainty',choices:['Nisam siguran, ali mislim da je muzej otvoren nedjeljom.','Muzej je vrlo velik.','Nedjeljom ne radim.','Bio sam u muzeju.']}
  ]}
];

const allCards=units.flatMap(unit=>unit.cards);
function tokens(value:string){return value.replace(/([,.!?;:])/g,' $1 ').replace(/\s+/g,' ').trim().split(' ').reverse();}
function lesson(unit:Unit,card:Card,index:number):Lesson{
  const id=`${unit.id}-l${index+1}`;
  const distractors=allCards.filter(other=>other!==card).slice((index*3)%Math.max(1,allCards.length-3)).map(other=>other.meaning).slice(0,3);
  return {id,courseId:'multi-hr',level:'A2',unitId:unit.id,title:card.title,subtitle:card.subtitle,estimatedMinutes:11,newConcepts:[card.concept],exercises:[
    {id:`${id}-e1`,type:'multiple-choice',instruction:'Wähle die natürlichste kroatische Formulierung.',prompt:card.de,choices:card.choices,answer:card.hr,conceptIds:[card.concept],difficulty:2,xp:8,explanation:'Achte auf Satzbau, Verbform und die typische kroatische Redewendung.'},
    {id:`${id}-e2`,type:'translation',instruction:'Übersetze den Gedanken in natürliches Kroatisch.',prompt:card.subtitle,sourceText:card.de,acceptedAnswers:[card.hr],conceptIds:[card.concept],difficulty:2,xp:10},
    {id:`${id}-e3`,type:'sentence-build',instruction:'Baue den kroatischen Satz in der richtigen Reihenfolge.',prompt:card.de,tokens:tokens(card.hr),answer:card.hr,conceptIds:[card.concept],difficulty:2,xp:9},
    {id:`${id}-e4`,type:'listening',instruction:'Höre den Satz und wähle die passende Bedeutung.',prompt:'Was wird gesagt?',speech:card.hr,choices:[card.meaning,...distractors],answer:card.meaning,conceptIds:[card.concept],difficulty:2,xp:9},
    {id:`${id}-e5`,type:'dictation',instruction:'Schreibe den gehörten kroatischen Satz.',prompt:'Höre genau auf Endungen und Wortstellung.',speech:card.hr,acceptedAnswers:[card.hr],conceptIds:[card.concept],difficulty:2,xp:11},
    {id:`${id}-e6`,type:'speaking',instruction:'Sprich den Satz auf Kroatisch.',prompt:card.de,speech:card.hr,acceptedAnswers:[card.hr],conceptIds:[card.concept],difficulty:2,xp:12}
  ]};
}

export const croatianA2Units=units.map(unit=>({id:unit.id,number:unit.number,title:unit.title,subtitle:unit.subtitle,lessons:unit.cards.map((card,index)=>lesson(unit,card,index))}));
