import type { Lesson } from '../types';
import type { CourseLevel, CourseUnit, CefrLevel } from './index';

type LessonSpec={title:string;scenario:string;objective:string;grammar:string;phrases:string[]};
type UnitSpec={title:string;subtitle:string;lessons:LessonSpec[]};

const L=(title:string,scenario:string,objective:string,grammar:string,...phrases:string[]):LessonSpec=>({title,scenario,objective,grammar,phrases});
const U=(title:string,subtitle:string,...lessons:LessonSpec[]):UnitSpec=>({title,subtitle,lessons});

const syllabus:Record<Exclude<CefrLevel,'C2'>,UnitSpec[]>={
A1:[
 U('Kennenlernen','Begrüßen, vorstellen und einfache persönliche Informationen austauschen.',
  L('Sich vorstellen','Du lernst eine neue Person kennen.','Name, Herkunft und Sprache nennen.','sein · heißen · einfache W-Fragen','Hallo, ich heiße Anna.','Ich komme aus Österreich.','Ich spreche ein bisschen Englisch.','Wie heißen Sie?'),
  L('Persönliche Angaben','Du füllst ein Formular aus oder sprichst an einer Rezeption.','Adresse, Telefonnummer und Alter verständlich nennen.','Zahlen · Possessivformen · Fragewörter','Meine Telefonnummer ist 0660 123456.','Ich bin dreiundzwanzig Jahre alt.','Meine Adresse ist Hauptstraße 12.','Können Sie das bitte wiederholen?')),
 U('Alltag & Zeit','Tagesablauf, Uhrzeiten, Termine und einfache Pläne.',
  L('Mein Tagesablauf','Du erzählst, was du an einem normalen Tag machst.','Gewohnheiten in einfacher Reihenfolge beschreiben.','Präsens · Zeitangaben · zuerst/dann','Ich stehe um sechs Uhr auf.','Um acht Uhr beginne ich zu arbeiten.','Mittags esse ich meistens etwas Kleines.','Am Abend lerne ich eine Stunde.'),
  L('Zeit & Termin','Du vereinbarst einen einfachen Termin.','Nach Uhrzeit und Verfügbarkeit fragen.','Uhrzeit · am/um · können','Wie spät ist es?','Passt Ihnen Dienstag um zehn Uhr?','Ich kann am Nachmittag.','Können wir den Termin verschieben?')),
 U('Essen & Einkaufen','Bestellen, bezahlen, Preise verstehen und einfache Wünsche äußern.',
  L('Im Café','Du bestellst etwas und bezahlst.','Höflich bestellen und nach der Rechnung fragen.','möchten · bitte · Mengen','Ich hätte gern einen Kaffee und ein Wasser.','Ohne Zucker, bitte.','Was kostet das zusammen?','Die Rechnung, bitte.'),
  L('Im Geschäft','Du suchst ein Produkt oder eine Größe.','Nach Preis, Farbe und Verfügbarkeit fragen.','dieser/diese · haben · brauchen','Haben Sie das in einer größeren Größe?','Ich suche eine schwarze Jacke.','Kann ich das anprobieren?','Ich nehme es.')),
 U('Unterwegs','Orientierung, Verkehrsmittel und einfache Reisesituationen.',
  L('Nach dem Weg fragen','Du suchst einen Ort in einer fremden Stadt.','Richtung verstehen und nachfragen.','wo · links/rechts · geradeaus','Entschuldigung, wo ist der Bahnhof?','Gehen Sie geradeaus und dann nach links.','Ist es weit von hier?','Können Sie es auf der Karte zeigen?'),
  L('Bus, Zug & Taxi','Du kaufst ein Ticket oder nimmst ein Taxi.','Ziel, Abfahrt und Fahrpreis klären.','nach/zu · wann · wie viel','Eine Fahrkarte nach Graz, bitte.','Wann fährt der nächste Zug?','Fährt dieser Bus ins Zentrum?','Bitte bringen Sie mich zu diesem Hotel.')),
 U('Hotel & Hilfe','Einchecken, Probleme erklären und grundlegende Hilfe bekommen.',
  L('Im Hotel','Du checkst ein und fragst nach wichtigen Informationen.','Reservierung und Zimmerwünsche nennen.','haben · für · mit/ohne','Ich habe eine Reservierung auf den Namen Steiner.','Ist das Frühstück inklusive?','Wo ist mein Zimmer?','Könnte ich bitte ein ruhiges Zimmer bekommen?'),
  L('Wenn etwas nicht funktioniert','Im Zimmer oder unterwegs gibt es ein einfaches Problem.','Ein Problem benennen und um Hilfe bitten.','nicht funktionieren · brauchen · bitte','Die Klimaanlage funktioniert nicht.','Ich brauche Hilfe.','Können Sie jemanden schicken?','Mein Schlüssel funktioniert nicht.')),
 U('Gesundheit & Sicherheit','Einfache Beschwerden, Notfälle und wichtige Rückfragen.',
  L('Beim Arzt','Du beschreibst ein einfaches gesundheitliches Problem.','Schmerzort und Dauer nennen.','haben · seit · weh tun','Ich habe Kopfschmerzen.','Mein Rücken tut weh.','Seit gestern habe ich Fieber.','Ich nehme keine Medikamente.'),
  L('Notfall & Verständigung','Du brauchst dringend Hilfe oder verstehst etwas nicht.','Hilfe holen und Kommunikation verlangsamen.','Imperativ höflich · bitte · nicht verstehen','Rufen Sie bitte einen Arzt.','Ich verstehe nicht.','Sprechen Sie bitte langsamer.','Wo ist die nächste Polizeistation?'))
],
A2:[
 U('Erfahrungen & Vergangenheit','Über Erlebnisse, Wochenenden und Reisen berichten.',
  L('Was gestern passiert ist','Du erzählst einem Freund von deinem Tag.','Ereignisse in zeitlicher Reihenfolge beschreiben.','Vergangenheit · dann/danach/später','Gestern habe ich länger gearbeitet als geplant.','Danach habe ich Freunde getroffen.','Wir sind gemeinsam essen gegangen.','Am Ende war ich sehr müde, aber zufrieden.'),
  L('Reiseerfahrung','Du berichtest über eine frühere Reise.','Erlebnisse, Orte und Eindrücke beschreiben.','Vergangenheit · schon/noch nie · weil','Letztes Jahr war ich zum ersten Mal in Italien.','Die Reise war schön, weil das Wetter perfekt war.','Wir haben viele kleine Orte besucht.','Ich würde gern noch einmal dorthin fahren.')),
 U('Pläne & Organisation','Zukunft, Verabredungen und praktische Organisation.',
  L('Wochenende planen','Du planst etwas mit Freunden.','Vorschläge machen und Alternativen anbieten.','Zukunft · wollen · könnten','Wollen wir am Samstag wandern gehen?','Wenn das Wetter schlecht ist, könnten wir ins Museum gehen.','Ich kann erst ab zwei Uhr.','Lass uns am Freitag noch einmal schreiben.'),
  L('Termin verschieben','Ein beruflicher oder privater Termin passt nicht.','Begründung geben und Ersatztermin finden.','müssen · deshalb · passt es','Leider kann ich den Termin morgen nicht wahrnehmen.','Ich muss länger arbeiten.','Wäre Donnerstag am Vormittag möglich?','Danke für Ihr Verständnis.')),
 U('Probleme auf Reisen','Verspätung, verlorenes Gepäck und Buchungsprobleme lösen.',
  L('Verspätung & Anschluss','Dein Zug oder Flug ist verspätet.','Informationen erfragen und Optionen klären.','wenn · noch · nächster','Mein Zug hat vierzig Minuten Verspätung.','Erreiche ich meinen Anschluss trotzdem?','Wann fährt die nächste Verbindung?','Muss ich ein neues Ticket kaufen?'),
  L('Gepäck & Buchung','Etwas fehlt oder eine Reservierung stimmt nicht.','Problem konkret erklären und Lösung verlangen.','fehlen · gebucht haben · eigentlich','Mein Koffer ist nicht angekommen.','Ich habe ein Doppelzimmer gebucht, aber dieses Zimmer hat nur ein Bett.','Könnten Sie die Buchung bitte prüfen?','Welche Lösung können Sie mir anbieten?')),
 U('Arbeit & Lernen','Über Aufgaben, Fähigkeiten und Lernfortschritt sprechen.',
  L('Im Team','Du stimmst Aufgaben mit Kollegen ab.','Aufgaben verteilen und Status mitteilen.','sollen · schon/noch · bis','Ich kümmere mich um den ersten Teil.','Kannst du den Bericht bis morgen prüfen?','Ich bin mit meiner Aufgabe fast fertig.','Wir sollten uns später kurz abstimmen.'),
  L('Etwas lernen','Du beschreibst Ziele und Schwierigkeiten beim Lernen.','Fortschritt und Lernstrategien erklären.','seit · besser werden · noch','Ich lerne seit sechs Monaten diese Sprache.','Beim Verstehen bin ich schon viel besser geworden.','Beim Sprechen brauche ich noch mehr Übung.','Ich versuche jeden Tag ein bisschen zu lernen.')),
 U('Gesundheit & Service','Beschwerden genauer erklären und Dienstleistungen nutzen.',
  L('Apotheke & Arzt','Du brauchst Rat zu Beschwerden oder Medikamenten.','Symptome, Dauer und Einschränkungen beschreiben.','seitdem · beim/wenn · dürfen','Seit drei Tagen habe ich starken Husten.','Beim Atmen tut meine Brust etwas weh.','Kann ich dieses Medikament zusammen mit anderen Tabletten nehmen?','Wie oft soll ich es einnehmen?'),
  L('Reklamation','Ein Produkt oder eine Dienstleistung ist nicht in Ordnung.','Sachlich reklamieren und eine Lösung erfragen.','funktionieren · zurückgeben · lieber','Ich habe dieses Gerät gestern gekauft, aber es funktioniert nicht.','Ich habe den Kassenbon dabei.','Kann ich es umtauschen oder zurückgeben?','Ich hätte lieber eine Rückerstattung.')),
 U('Meinung & Empfehlung','Vorlieben begründen und einfache Ratschläge geben.',
  L('Eine Empfehlung geben','Jemand fragt dich nach Restaurant, Ort oder Aktivität.','Empfehlung mit einfachen Gründen geben.','würde · weil · besonders','Ich würde dieses Restaurant empfehlen, weil das Essen frisch ist.','Am Wochenende ist es dort allerdings ziemlich voll.','Reserviere am besten vorher einen Tisch.','Wenn du lokale Küche magst, passt es sehr gut.'),
  L('Zustimmen & widersprechen','Du sprichst über Alltag oder Freizeit.','Meinung höflich ausdrücken und begründen.','ich finde · meiner Meinung nach · aber','Ich finde die Idee grundsätzlich gut.','Ich sehe das etwas anders.','Für mich ist der Preis zu hoch.','Vielleicht können wir einen Kompromiss finden.')),
 U('Telefon & Nachrichten','Am Telefon, per Nachricht und E-Mail klar kommunizieren.',
  L('Telefonieren','Du rufst bei einer Firma oder Praxis an.','Anliegen nennen, verbinden lassen und Informationen notieren.','könnte ich · bezüglich · erreichbar','Guten Tag, ich rufe wegen meines Termins an.','Könnte ich bitte mit Frau Berger sprechen?','Wann ist sie wieder erreichbar?','Könnten Sie ihr eine Nachricht hinterlassen?'),
  L('Kurze E-Mail','Du schreibst eine höfliche Alltags- oder Arbeitsnachricht.','Anrede, Anliegen und Abschluss formulieren.','höfliche Bitten · Bezug nehmen','Vielen Dank für Ihre Nachricht.','Ich möchte kurz bestätigen, dass der Termin für mich passt.','Bitte schicken Sie mir noch die genaue Adresse.','Mit freundlichen Grüßen.'))
],
B1:[
 U('Erzählen & Erklären','Zusammenhängend berichten, Ursachen erklären und Details verbinden.',
  L('Eine unerwartete Situation','Du erzählst ausführlicher von einem Problem oder Erlebnis.','Ereignisse strukturieren und Reaktionen beschreiben.','obwohl · während · plötzlich · schließlich','Während ich zum Flughafen unterwegs war, bekam ich die Nachricht, dass mein Flug gestrichen wurde.','Zuerst wusste ich nicht, was ich tun sollte.','Obwohl die Warteschlange sehr lang war, blieb das Personal freundlich.','Schließlich bekam ich einen Platz auf einem späteren Flug.'),
  L('Warum etwas passiert ist','Du erklärst Ursachen und Folgen.','Zusammenhänge verständlich darstellen.','deshalb · dadurch · weil · aus diesem Grund','Das Projekt hat sich verzögert, weil wichtige Informationen gefehlt haben.','Dadurch konnten wir erst später mit der Arbeit beginnen.','Wir haben den Ablauf deshalb geändert.','Aus diesem Grund sollte das Problem beim nächsten Mal nicht wieder auftreten.')),
 U('Meinungen & Diskussion','Standpunkt erklären, Beispiele nennen und auf andere reagieren.',
  L('Eine Meinung begründen','Du diskutierst ein bekanntes gesellschaftliches oder berufliches Thema.','Standpunkt mit Gründen und Beispielen stützen.','einerseits/andererseits · meiner Ansicht nach','Meiner Ansicht nach bringt Homeoffice viele Vorteile, wenn die Zusammenarbeit gut organisiert ist.','Einerseits spart man Zeit, andererseits fehlt manchmal der direkte Austausch.','Ich habe selbst erlebt, dass klare Absprachen dabei besonders wichtig sind.','Deshalb würde ich ein gemischtes Modell bevorzugen.'),
  L('Höflich widersprechen','Du bist anderer Meinung, willst aber konstruktiv bleiben.','Widerspruch abschwächen und Alternative anbieten.','ich verstehe den Punkt · allerdings · stattdessen','Ich verstehe deinen Punkt, sehe die Situation aber etwas anders.','Der Vorschlag ist interessant, allerdings halte ich den Zeitplan für zu knapp.','Stattdessen könnten wir die wichtigsten Aufgaben zuerst erledigen.','Wäre das für dich eine mögliche Lösung?')),
 U('Beruf & Zusammenarbeit','Besprechungen, Statusupdates, Probleme und Entscheidungen.',
  L('Status im Meeting','Du berichtest kurz über deinen Arbeitsstand.','Fortschritt, Risiko und nächste Schritte klar nennen.','bisher · derzeit · als Nächstes','Bisher liegen wir im Zeitplan.','Derzeit warten wir noch auf die Rückmeldung des Kunden.','Das größte Risiko ist die kurze Testphase.','Als Nächstes wollen wir die offenen Punkte priorisieren.'),
  L('Ein Problem lösen','Im Team läuft etwas nicht wie geplant.','Problem definieren, Optionen vergleichen und Aufgabe vereinbaren.','falls · entweder/oder · zuständig sein','Falls die Lieferung heute nicht kommt, müssen wir den Plan ändern.','Wir können entweder verschieben oder mit einer kleineren Menge starten.','Ich kläre sofort, welche Option möglich ist.','Wer übernimmt danach die Information an den Kunden?')),
 U('Reise & Behörden','Komplexere Reiseprobleme, Dokumente und formelle Anliegen.',
  L('Bei einer Behörde','Du brauchst eine Auskunft oder musst Unterlagen nachreichen.','Anliegen präzise erklären und nach Anforderungen fragen.','bezüglich · erforderlich · nachreichen','Ich habe eine Frage bezüglich meines Antrags.','Welche Unterlagen sind noch erforderlich?','Kann ich das fehlende Dokument online nachreichen?','Bis wann muss alles vollständig eingereicht sein?'),
  L('Reiseproblem verhandeln','Buchung, Mietwagen oder Unterkunft entspricht nicht der Vereinbarung.','Sachlich erklären und angemessene Lösung verlangen.','vereinbart · entsprechen · erwarten','Das Fahrzeug entspricht leider nicht der gebuchten Kategorie.','In meiner Bestätigung ist ausdrücklich ein größeres Modell angegeben.','Ich brauche genügend Platz für vier Personen und Gepäck.','Welche gleichwertige Alternative können Sie mir anbieten?')),
 U('Gesundheit & Wohlbefinden','Symptome differenziert beschreiben und Empfehlungen verstehen.',
  L('Beschwerden genau schildern','Du erklärst einem Arzt Verlauf und Auslöser.','Zeitlicher Verlauf, Stärke und mögliche Auslöser nennen.','seitdem · zunehmend · insbesondere','Die Beschwerden haben vor etwa einer Woche begonnen.','Seitdem sind die Schmerzen zunehmend stärker geworden.','Insbesondere bei Bewegung merke ich sie deutlich.','In Ruhe wird es meistens besser.'),
  L('Rat verstehen','Du bekommst eine Empfehlung und willst sicher sein, sie richtig verstanden zu haben.','Anweisungen zusammenfassen und rückfragen.','wenn ich Sie richtig verstehe · sollte','Wenn ich Sie richtig verstehe, soll ich mich einige Tage schonen.','Darf ich trotzdem leichte Bewegung machen?','Woran merke ich, dass ich wiederkommen sollte?','Gibt es etwas, das ich unbedingt vermeiden muss?')),
 U('Medien & Information','Nachrichten zusammenfassen, Quellen vergleichen und Unsicherheit ausdrücken.',
  L('Eine Nachricht zusammenfassen','Du erklärst jemandem kurz, worum es in einem Bericht geht.','Kernaussage und wichtigste Details wiedergeben.','laut dem Bericht · dabei geht es um','Laut dem Bericht plant die Stadt neue Regeln für den Verkehr.','Dabei geht es vor allem darum, den öffentlichen Verkehr attraktiver zu machen.','Ein Teil der Bevölkerung unterstützt die Pläne.','Andere kritisieren vor allem die zusätzlichen Kosten.'),
  L('Information prüfen','Zwei Quellen sagen nicht genau dasselbe.','Unsicherheit und Quellenlage ausdrücken.','offenbar · angeblich · bestätigt','In sozialen Medien wird behauptet, dass die Veranstaltung abgesagt wurde.','Auf der offiziellen Website steht dazu allerdings noch nichts.','Offenbar gibt es noch keine endgültige Entscheidung.','Ich würde warten, bis die Information offiziell bestätigt ist.')),
 U('Beziehungen & Konflikte','Missverständnisse klären, Gefühle erklären und Kompromisse finden.',
  L('Missverständnis klären','Eine Aussage wurde anders verstanden als gemeint.','Absicht erklären und Missverständnis auflösen.','so war das nicht gemeint · eigentlich','Ich glaube, meine Nachricht ist anders angekommen, als ich sie gemeint habe.','Ich wollte dich nicht kritisieren.','Eigentlich wollte ich nur erklären, warum ich besorgt war.','Es tut mir leid, wenn das unhöflich geklungen hat.'),
  L('Kompromiss finden','Zwei Personen wollen unterschiedliche Dinge.','Bedürfnisse erklären und gemeinsamen Plan entwickeln.','für mich wäre wichtig · könnten wir','Für mich wäre wichtig, dass wir nicht zu spät zurückkommen.','Ich verstehe aber, dass du länger bleiben möchtest.','Könnten wir uns auf eine feste Uhrzeit einigen?','Dann wissen beide Seiten, woran sie sind.'))
],
B2:[
 U('Argumentieren & Abwägen','Komplexere Standpunkte differenziert entwickeln und Gegenargumente aufnehmen.',
  L('Vor- und Nachteile abwägen','Du diskutierst eine Entscheidung mit mehreren Folgen.','Argumente gewichten und zu einem begründeten Fazit kommen.','zwar/jedoch · dennoch · unter der Voraussetzung','Die Lösung wäre zwar teurer, könnte langfristig jedoch deutlich effizienter sein.','Ein wesentlicher Vorteil ist die größere Flexibilität.','Dagegen spricht, dass die Umstellung zunächst viel Zeit benötigt.','Unter der Voraussetzung, dass wir genügend Ressourcen haben, würde ich die Änderung trotzdem empfehlen.'),
  L('Auf ein Gegenargument reagieren','Jemand stellt deine Position infrage.','Einwände anerkennen, einordnen und präzise antworten.','berechtigter Einwand · zugleich · entscheidend ist','Das ist ein berechtigter Einwand.','Zugleich sollten wir berücksichtigen, dass die aktuelle Lösung ebenfalls erhebliche Risiken hat.','Entscheidend ist aus meiner Sicht nicht nur der Preis, sondern auch die Zuverlässigkeit.','Deshalb würde ich beide Faktoren gemeinsam bewerten.')),
 U('Verhandeln & Überzeugen','Interessen klären, Bedingungen aushandeln und tragfähige Vereinbarungen finden.',
  L('Bedingungen verhandeln','Du verhandelst Preis, Termin oder Leistungsumfang.','Prioritäten setzen und Zugeständnisse formulieren.','sofern · im Gegenzug · unter diesen Bedingungen','Wir könnten dem früheren Termin zustimmen, sofern der Leistungsumfang unverändert bleibt.','Beim Preis haben wir nur wenig Spielraum.','Im Gegenzug könnten wir eine längere Laufzeit anbieten.','Unter diesen Bedingungen wäre eine Einigung für uns möglich.'),
  L('Eine Lösung verkaufen','Du willst andere von einer Idee überzeugen.','Nutzen, Einwand und konkrete Wirkung verbinden.','dadurch · insbesondere · im Vergleich zu','Der größte Vorteil dieser Lösung liegt in der einfacheren Bedienung.','Dadurch reduzieren wir den Schulungsaufwand deutlich.','Insbesondere neue Mitarbeiter könnten schneller produktiv arbeiten.','Im Vergleich zur bisherigen Lösung sparen wir außerdem mehrere manuelle Schritte.')),
 U('Professionelle Kommunikation','Meetings, Präsentationen, Feedback und formelle Texte.',
  L('Präsentieren & Fragen beantworten','Du stellst ein Thema vor und reagierst spontan auf Rückfragen.','Strukturieren, hervorheben und Unsicherheit professionell behandeln.','zunächst · hervorheben · nach aktuellem Stand','Zunächst möchte ich kurz erklären, welche Ziele wir mit dem Projekt verfolgen.','Besonders hervorheben möchte ich die deutliche Verbesserung der Reaktionszeit.','Zu diesem Punkt liegen uns noch nicht alle Daten vor.','Nach aktuellem Stand erwarten wir die endgültigen Ergebnisse nächste Woche.'),
  L('Konstruktives Feedback','Du gibst differenziertes Feedback zu einer Leistung.','Stärken anerkennen und konkrete Verbesserung vorschlagen.','was gut funktioniert · noch klarer wäre','Was besonders gut funktioniert, ist die klare Struktur.','An einigen Stellen könnte die Begründung noch konkreter sein.','Hilfreich wäre zum Beispiel ein praktisches Beispiel nach jedem Hauptpunkt.','Dann wäre die Argumentation für das Publikum noch leichter nachzuvollziehen.')),
 U('Komplexe Probleme','Mehrere Ursachen, Risiken und Handlungsoptionen erklären.',
  L('Ursachen analysieren','Ein Problem hat nicht nur einen Grund.','Mehrere Faktoren gewichten und Zusammenhänge erklären.','nicht allein · vielmehr · zusätzlich','Die Verzögerung lässt sich nicht allein mit einem technischen Problem erklären.','Vielmehr sind mehrere Faktoren gleichzeitig zusammengekommen.','Zusätzlich waren die Zuständigkeiten nicht eindeutig geklärt.','Dadurch wurden wichtige Entscheidungen mehrfach verschoben.'),
  L('Krisensituation koordinieren','Unter Zeitdruck müssen Informationen klar und priorisiert werden.','Lage, Priorität und nächste Schritte knapp formulieren.','Vorrang hat · solange · sobald','Vorrang hat jetzt die Sicherheit der betroffenen Personen.','Solange wir keine bestätigten Informationen haben, kommunizieren wir nur gesicherte Fakten.','Das Technikteam prüft parallel die Ursache.','Sobald neue Erkenntnisse vorliegen, geben wir ein aktualisiertes Lagebild.')),
 U('Medien & Gesellschaft','Rhetorik, Perspektiven und Wirkung von Informationen analysieren.',
  L('Medienbeitrag analysieren','Du beurteilst nicht nur Inhalt, sondern auch Darstellung.','Framing, Auswahl und Wirkung beschreiben.','auffällig ist · vermittelt den Eindruck · lässt offen','Auffällig ist, dass der Beitrag fast ausschließlich kritische Stimmen zeigt.','Dadurch vermittelt er den Eindruck, die Ablehnung sei deutlich größer als sie möglicherweise ist.','Die statistischen Hintergründe werden nur kurz erwähnt.','Offen bleibt deshalb, wie repräsentativ die gezeigten Beispiele tatsächlich sind.'),
  L('Unterschiedliche Perspektiven','Mehrere gesellschaftliche Interessen stehen im Konflikt.','Positionen fair darstellen und Unterschiede erklären.','aus Sicht von · während · hingegen','Aus Sicht der Anwohner steht vor allem die Lebensqualität im Vordergrund.','Unternehmen betonen hingegen die wirtschaftlichen Folgen.','Die Stadt versucht, beide Interessen miteinander zu verbinden.','Der Konflikt entsteht also weniger durch unterschiedliche Fakten als durch unterschiedliche Prioritäten.')),
 U('Beziehungen & Führung','Schwierige Gespräche, Erwartungen und Verantwortung professionell handhaben.',
  L('Schwieriges Gespräch führen','Du musst ein sensibles Problem direkt ansprechen.','Beobachtung, Wirkung und Erwartung trennen.','mir ist aufgefallen · das führt dazu · ich wünsche mir','Mir ist aufgefallen, dass mehrere Aufgaben zuletzt ohne Rückmeldung liegen geblieben sind.','Das führt dazu, dass andere im Team sehr kurzfristig reagieren müssen.','Mir ist wichtig zu verstehen, woran das liegt.','Ich wünsche mir, dass wir künftig früher Bescheid geben, wenn etwas nicht rechtzeitig fertig wird.'),
  L('Verantwortung übernehmen','Ein Fehler ist passiert und du kommunizierst damit professionell.','Verantwortung, Korrektur und Prävention verbinden.','wir hätten · inzwischen · künftig','Wir hätten die Änderung früher kommunizieren müssen.','Dafür übernehme ich die Verantwortung.','Inzwischen haben wir den Fehler korrigiert und die betroffenen Personen informiert.','Künftig führen wir vor solchen Änderungen eine zusätzliche Kontrolle durch.')),
 U('Technik & Fachliches','Komplexe Abläufe verständlich erklären und Rückfragen präzise beantworten.',
  L('Einen Prozess erklären','Du erklärst einen technischen oder organisatorischen Ablauf.','Schritte, Abhängigkeiten und Zweck klar darstellen.','zunächst · anschließend · Voraussetzung','Zunächst werden die eingehenden Daten automatisch geprüft.','Anschließend werden nur vollständige Datensätze an das nächste System übertragen.','Voraussetzung dafür ist, dass alle Pflichtfelder korrekt ausgefüllt sind.','Dieser Schritt verhindert, dass fehlerhafte Daten später manuell korrigiert werden müssen.'),
  L('Fachfrage verständlich beantworten','Eine Person ohne Spezialwissen fragt nach Details.','Fachbegriff erklären und auf das Wesentliche reduzieren.','vereinfacht gesagt · damit ist gemeint · konkret bedeutet das','Vereinfacht gesagt beschreibt der Begriff, wie zuverlässig ein System unter Belastung arbeitet.','Damit ist nicht nur die maximale Leistung gemeint.','Entscheidend ist vielmehr, ob die Leistung auch über längere Zeit stabil bleibt.','Konkret bedeutet das, dass wir nicht nur einen kurzen Spitzentest durchführen.'))
],
C1:[
 U('Nuance & Register','Sehr präzise formulieren und Sprache an Situation und Beziehung anpassen.',
  L('Formell oder direkt','Du formulierst dieselbe Botschaft je nach Kontext unterschiedlich.','Register bewusst steuern und Wirkung einschätzen.','Abschwächung · Nominalstil · indirekte Bitte','Ich möchte Sie bitten, die Entscheidung noch einmal zu prüfen.','Aus meiner Sicht wäre eine erneute Bewertung sinnvoll.','Ich halte die derzeitige Lösung für schwer nachvollziehbar.','Unter den gegebenen Umständen wäre eine Anpassung aus meiner Sicht angemessen.'),
  L('Feine Bedeutungsunterschiede','Ähnliche Aussagen haben unterschiedliche Stärke oder Haltung.','Sicherheit, Distanz und Bewertung präzise markieren.','offenbar · vermutlich · zweifellos · meines Erachtens','Offenbar wurde die Information intern bereits weitergegeben.','Vermutlich liegt die Ursache in einer Kombination mehrerer Faktoren.','Es spricht vieles dafür, dass die Maßnahme Wirkung zeigt.','Meines Erachtens wäre es dennoch verfrüht, daraus eine endgültige Schlussfolgerung zu ziehen.')),
 U('Diplomatie & Konflikt','Spannungen entschärfen, Kritik vermitteln und schwierige Positionen vertreten.',
  L('Diplomatisch widersprechen','Du widersprichst einer einflussreichen Person, ohne unnötig zu eskalieren.','Respekt signalisieren und dennoch klar bleiben.','ich kann nachvollziehen · gleichzeitig sehe ich · aus meiner Sicht','Ich kann nachvollziehen, warum dieser Ansatz auf den ersten Blick attraktiv wirkt.','Gleichzeitig sehe ich einige Risiken, die wir nicht unterschätzen sollten.','Insbesondere die langfristigen Auswirkungen sind aus meiner Sicht noch nicht ausreichend geklärt.','Ich würde daher vorschlagen, die Entscheidung an zusätzliche Kriterien zu knüpfen.'),
  L('Zwischen Positionen vermitteln','Zwei Seiten reden aneinander vorbei.','Interessen herausarbeiten und gemeinsame Basis formulieren.','wenn ich beide Seiten richtig verstehe · gemeinsam ist','Wenn ich beide Seiten richtig verstehe, besteht Einigkeit über das Ziel, aber nicht über den Weg dorthin.','Der einen Seite ist vor allem Geschwindigkeit wichtig, der anderen Planungssicherheit.','Gemeinsam ist beiden Positionen, dass unnötige Risiken vermieden werden sollen.','Darauf könnten wir einen Kompromiss aufbauen.')),
 U('Strategie & Entscheidungen','Komplexe Optionen unter Unsicherheit bewerten und Empfehlungen formulieren.',
  L('Strategische Empfehlung','Du bereitest eine Entscheidung für Führungskräfte vor.','Optionen verdichten, Risiken benennen und Empfehlung begründen.','in Anbetracht · spricht dafür/dagegen · unter Abwägung','In Anbetracht der aktuellen Marktlage wäre eine schrittweise Einführung weniger riskant.','Für eine sofortige Umstellung spricht zwar der schnellere Nutzen.','Dagegen stehen jedoch erhebliche operative Risiken.','Unter Abwägung beider Seiten empfehle ich daher ein gestuftes Vorgehen.'),
  L('Entscheidung unter Unsicherheit','Wichtige Daten fehlen, trotzdem muss gehandelt werden.','Unsicherheit transparent machen und robuste Entscheidungskriterien setzen.','selbst wenn · unabhängig davon · entscheidungsrelevant','Wir können derzeit nicht sicher vorhersagen, wie sich die Nachfrage entwickelt.','Selbst wenn das optimistische Szenario nicht eintritt, sollte die Lösung wirtschaftlich tragfähig bleiben.','Entscheidungsrelevant ist daher vor allem, wie flexibel wir später reagieren können.','Unabhängig davon sollten wir klare Kriterien für einen Kurswechsel definieren.')),
 U('Synthese & komplexe Information','Mehrere Quellen, Argumente und Perspektiven zu einem klaren Gesamtbild verbinden.',
  L('Mehrere Quellen zusammenführen','Du fasst verschiedene Berichte für andere zusammen.','Übereinstimmungen, Unterschiede und offene Fragen synthetisieren.','während Quelle A · übereinstimmend · unklar bleibt','Während die erste Analyse vor allem wirtschaftliche Vorteile hervorhebt, betont die zweite die sozialen Folgen.','Übereinstimmend stellen beide Quellen fest, dass kurzfristig hohe Investitionen nötig sind.','Unterschiedlich bewerten sie jedoch, wie schnell sich diese Investitionen auszahlen.','Unklar bleibt, welche Annahmen den jeweiligen Prognosen zugrunde liegen.'),
  L('Komplexes Thema erklären','Du erklärst ein schwieriges Thema für ein gemischtes Publikum.','Komplexität reduzieren, ohne wesentliche Nuancen zu verlieren.','vereinfacht dargestellt · entscheidend ist · daraus folgt nicht automatisch','Vereinfacht dargestellt geht es darum, Entscheidungen auf Basis unvollständiger Informationen zu treffen.','Entscheidend ist dabei, Unsicherheit nicht mit Unwissen gleichzusetzen.','Auch gute Daten beseitigen nicht jedes Risiko.','Daraus folgt nicht automatisch, dass jede Entscheidung gleich unsicher ist.')),
 U('Rhetorik & Wirkung','Implizite Botschaften, rhetorische Strategien und Wortwahl analysieren.',
  L('Rhetorische Strategie erkennen','Du analysierst eine Rede, Werbung oder Debatte.','Wirkung von Wortwahl und Struktur beschreiben.','der Sprecher stellt dar · erzeugt den Eindruck · lenkt Aufmerksamkeit','Der Sprecher stellt die Entscheidung als alternativlos dar.','Durch die wiederholte Verwendung von Sicherheitsbegriffen erzeugt er den Eindruck unmittelbarer Dringlichkeit.','Gleichzeitig werden mögliche Nachteile nur am Rand erwähnt.','Dadurch wird die Aufmerksamkeit gezielt auf ein bestimmtes Risiko gelenkt.'),
  L('Implizite Bedeutung verstehen','Nicht alles wird direkt ausgesprochen.','Andeutungen, Distanz und Unterton erfassen.','zwischen den Zeilen · deutet an · ohne ausdrücklich zu sagen','Zwischen den Zeilen deutet die Antwort an, dass intern Zweifel bestehen.','Die Formulierung wirkt bewusst vorsichtig.','Ohne ausdrücklich zu widersprechen, stellt sie die bisherige Darstellung infrage.','Gerade diese Zurückhaltung macht die Aussage politisch interessant.')),
 U('Professionelle Exzellenz','Präsentationen, Executive Summaries und hochrangige Kommunikation.',
  L('Executive Summary','Du musst ein langes Thema für Entscheider auf wenige Punkte reduzieren.','Kernaussage, Bedeutung, Risiko und Empfehlung verdichten.','Kernpunkt · wesentlich ist · daraus ergibt sich','Der Kernpunkt ist, dass die Nachfrage wächst, die vorhandene Kapazität jedoch kaum noch Spielraum bietet.','Wesentlich ist deshalb nicht nur die Frage nach zusätzlichen Ressourcen, sondern auch nach effizienteren Abläufen.','Das größte kurzfristige Risiko liegt in möglichen Engpässen.','Daraus ergibt sich die Empfehlung, Kapazität und Prozessoptimierung parallel anzugehen.'),
  L('Spontane Fragerunde','Nach einer Präsentation kommen kritische Rückfragen.','Zeit gewinnen, Frage präzisieren und fundiert antworten.','wenn ich Ihre Frage richtig verstehe · dazu zwei Punkte · soweit wir wissen','Wenn ich Ihre Frage richtig verstehe, geht es Ihnen vor allem um die langfristige Finanzierung.','Dazu würde ich zwei Punkte unterscheiden.','Erstens sind die laufenden Kosten bereits relativ gut abschätzbar.','Bei den langfristigen Einsparungen arbeiten wir dagegen noch mit mehreren Szenarien.')),
 U('Kulturelle & soziale Feinheiten','Kommunikationsstile, Erwartungen und Missverständnisse reflektieren.',
  L('Kulturelle Unterschiede erklären','Unterschiedliche Normen führen zu Missverständnissen.','Verhalten beschreiben, ohne vorschnell zu bewerten.','kann als · wird häufig anders interpretiert · hängt vom Kontext ab','Direkte Kritik kann in manchen Kontexten als effizient und ehrlich gelten.','In anderen Situationen wird dieselbe Formulierung möglicherweise als unnötig hart interpretiert.','Wie eine Aussage wirkt, hängt daher stark von Beziehung und Erwartung ab.','Es ist sinnvoll, zunächst nach der beabsichtigten Bedeutung zu fragen.'),
  L('Soziale Signale lesen','Du reagierst auf subtile Zustimmung, Zurückhaltung oder Ablehnung.','Unsichere soziale Signale vorsichtig interpretieren.','klingt zunächst · könnte darauf hindeuten · sicher ist nur','Die Antwort klingt zunächst positiv, bleibt aber auffällig unverbindlich.','Das könnte darauf hindeuten, dass noch Vorbehalte bestehen.','Sicher ist nur, dass noch keine klare Zusage gegeben wurde.','Ich würde deshalb konkret nach dem nächsten Entscheidungsschritt fragen.'))
]};

const levelMeta:Record<Exclude<CefrLevel,'C2'>,{title:string;descriptor:string;goal:string}>={
 A1:{title:'Grundlagen',descriptor:'Sicher durch einfache Alltagssituationen',goal:'Grundbedürfnisse ausdrücken, kurze Gespräche führen und in Reise- und Alltagssituationen handlungsfähig sein.'},
 A2:{title:'Alltag',descriptor:'Selbstständig in vertrauten Situationen',goal:'Erfahrungen, Pläne und Probleme erklären und typische Dienstleistungen, Reisen und Gespräche selbstständig bewältigen.'},
 B1:{title:'Selbstständig',descriptor:'Zusammenhängend sprechen und Probleme lösen',goal:'Erlebnisse strukturiert erzählen, Meinungen begründen und in Beruf, Reise und Alltag flexibel reagieren.'},
 B2:{title:'Sicher & differenziert',descriptor:'Komplexe Themen wirksam behandeln',goal:'Argumentieren, verhandeln, präsentieren und anspruchsvollere berufliche und gesellschaftliche Situationen präzise bewältigen.'},
 C1:{title:'Fortgeschritten',descriptor:'Nuance, Register & professionelle Wirkung',goal:'Komplexe Inhalte spontan, präzise und adressatengerecht ausdrücken, implizite Bedeutung verstehen und anspruchsvoll vermitteln.'}
};

const languageNames:Record<string,string>={hr:'Kroatisch',sl:'Slowenisch',es:'Spanisch',fr:'Französisch',de:'Deutsch',it:'Italienisch',pt:'Portugiesisch',nl:'Niederländisch',pl:'Polnisch',cs:'Tschechisch',tr:'Türkisch',el:'Griechisch',ru:'Russisch',uk:'Ukrainisch',zh:'Chinesisch',ja:'Japanisch',ko:'Koreanisch',ar:'Arabisch'};

function dynamicLesson(language:string,level:Exclude<CefrLevel,'C2'>,unit:UnitSpec,unitIndex:number,spec:LessonSpec,lessonIndex:number):Lesson{
 const id=`${language}-${level.toLowerCase()}-rw-u${unitIndex+1}-l${lessonIndex+1}`;
 return{id,courseId:`multi-${language}`,level,unitId:`${language}-${level.toLowerCase()}-rw-u${unitIndex+1}`,title:spec.title,subtitle:spec.objective,estimatedMinutes:10,newConcepts:[`realworld.${level.toLowerCase()}.${unitIndex+1}.${lessonIndex+1}`],exercises:[],dynamic:{scenario:spec.scenario,objective:spec.objective,grammarFocus:spec.grammar,phrases:spec.phrases}};
}

export function multilingualCefrLevel(language:string,level:Exclude<CefrLevel,'C2'>):CourseLevel{
 const name=languageNames[language]??language.toUpperCase();
 const units:CourseUnit[]=syllabus[level].map((unit,unitIndex)=>({id:`${language}-${level.toLowerCase()}-rw-u${unitIndex+1}`,number:unitIndex+1,title:unit.title,subtitle:unit.subtitle,lessons:unit.lessons.map((lesson,lessonIndex)=>dynamicLesson(language,level,unit,unitIndex,lesson,lessonIndex))}));
 const meta=levelMeta[level];
 return{id:level,title:meta.title,descriptor:meta.descriptor,goal:`${meta.goal} Der Lernpfad trainiert ${name} mit realen Situationen, Hören, Sprechen und aktiver Produktion.`,units,productionTargetUnits:units.length};
}

export function multilingualCefrLevels(language:string):CourseLevel[]{return(['A1','A2','B1','B2','C1'] as const).map(level=>multilingualCefrLevel(language,level));}
export const multilingualCefrLanguages=Object.keys(languageNames);
