import type { Lesson } from '../types';

type Level='B2'|'C1'|'C2';
type Blueprint={
  level:Level;unit:number;lesson:number;unitTitle:string;unitSubtitle:string;title:string;subtitle:string;goal:string;
  german:string;english:string;gapSentence:string;gapChoices:string[];gapAnswer:string;listening:string;listeningMeaning:string;conceptId:string;
};

const blueprints:Blueprint[]=[
  {level:'B2',unit:3,lesson:1,unitTitle:'Meetings & Verhandlungen',unitSubtitle:'Positionen differenziert vertreten, Risiken abwägen, verhandeln und Entscheidungen sauber festhalten.',title:'Höflich widersprechen',subtitle:'Zustimmen, einschränken und einen Gegenpunkt professionell formulieren.',goal:'Einen sachlichen Einwand äußern, ohne die Gesprächsebene zu verschlechtern.',german:'Ich verstehe den Ansatz, bin aber nicht überzeugt, dass der Zeitplan realistisch ist.',english:'I understand the approach, but I am not convinced that the timeline is realistic.',gapSentence:'I can see your point; ___, I still have concerns about the timeline.',gapChoices:['however','therefore','unless','despite'],gapAnswer:'however',listening:'That is a fair point, although I think we may be underestimating the implementation risk.',listeningMeaning:'Das ist ein berechtigter Punkt, obwohl wir das Umsetzungsrisiko meiner Meinung nach möglicherweise unterschätzen.',conceptId:'cefr.b2.tactful-disagreement'},
  {level:'B2',unit:3,lesson:2,unitTitle:'Meetings & Verhandlungen',unitSubtitle:'Positionen differenziert vertreten, Risiken abwägen, verhandeln und Entscheidungen sauber festhalten.',title:'Risiken abwägen',subtitle:'Wahrscheinlichkeit, Auswirkung und Gegenmaßnahmen präzise beschreiben.',goal:'Ein Risiko mit einer realistischen Gegenmaßnahme verbinden.',german:'Selbst wenn die Verzögerung unwahrscheinlich ist, wären die Folgen erheblich.',english:'Even if the delay is unlikely, the consequences would be significant.',gapSentence:'The risk is relatively low, but its potential ___ is high.',gapChoices:['impact','incident','impression','occasion'],gapAnswer:'impact',listening:'We can reduce the exposure by testing the change with a smaller group first.',listeningMeaning:'Wir können das Risiko verringern, indem wir die Änderung zuerst mit einer kleineren Gruppe testen.',conceptId:'cefr.b2.risk-language'},
  {level:'B2',unit:3,lesson:3,unitTitle:'Meetings & Verhandlungen',unitSubtitle:'Positionen differenziert vertreten, Risiken abwägen, verhandeln und Entscheidungen sauber festhalten.',title:'Eine Lösung verhandeln',subtitle:'Interessen erkennen, Bedingungen formulieren und Kompromisse anbieten.',goal:'Einen konkreten Kompromiss mit einer Bedingung anbieten.',german:'Wir könnten dem früheren Termin zustimmen, sofern der Umfang reduziert wird.',english:'We could agree to the earlier deadline provided that the scope is reduced.',gapSentence:'We can accept the proposal ___ you can guarantee delivery by Friday.',gapChoices:['provided that','despite','whereas','in case of'],gapAnswer:'provided that',listening:'If you can be flexible on the price, we may be able to commit to a longer contract.',listeningMeaning:'Wenn Sie beim Preis flexibel sein können, könnten wir uns möglicherweise auf einen längeren Vertrag festlegen.',conceptId:'cefr.b2.negotiation-conditions'},
  {level:'B2',unit:3,lesson:4,unitTitle:'Meetings & Verhandlungen',unitSubtitle:'Positionen differenziert vertreten, Risiken abwägen, verhandeln und Entscheidungen sauber festhalten.',title:'Entscheidungen festhalten',subtitle:'Ergebnisse, Verantwortlichkeiten und nächste Schritte eindeutig zusammenfassen.',goal:'Nach einem Meeting eine Entscheidung präzise zusammenfassen.',german:'Wir haben vereinbart, dass Maria den Entwurf überarbeitet und ihn bis Dienstag verteilt.',english:'We agreed that Maria would revise the draft and circulate it by Tuesday.',gapSentence:'To ___, we will keep the current scope and review the budget next week.',gapChoices:['summarise','summarising','summary','summarised'],gapAnswer:'summarise',listening:'Before we close, let me confirm the three actions we have agreed on.',listeningMeaning:'Bevor wir schließen, lassen Sie mich die drei vereinbarten Maßnahmen bestätigen.',conceptId:'cefr.b2.meeting-outcomes'},

  {level:'C1',unit:3,lesson:1,unitTitle:'Nuance & Leadership',unitSubtitle:'Unsicherheit kalibrieren, Perspektiven neu rahmen und anspruchsvolle Stakeholder-Kommunikation steuern.',title:'Aussagen kalibrieren',subtitle:'Sicherheit und Unsicherheit bewusst abstufen, statt zu übertreiben.',goal:'Eine belastbare, aber vorsichtige Schlussfolgerung formulieren.',german:'Die Daten deuten auf eine Verbesserung hin, reichen jedoch noch nicht für eine eindeutige Schlussfolgerung aus.',english:'The data point to an improvement, although they are not yet sufficient to support a definitive conclusion.',gapSentence:'The evidence ___ to suggest that the change is working, but further data are needed.',gapChoices:['appears','proves','guarantees','certifies'],gapAnswer:'appears',listening:'At this stage, the results are encouraging rather than conclusive.',listeningMeaning:'Zum jetzigen Zeitpunkt sind die Ergebnisse ermutigend, aber nicht abschließend.',conceptId:'cefr.c1.hedging-evidence'},
  {level:'C1',unit:3,lesson:2,unitTitle:'Nuance & Leadership',unitSubtitle:'Unsicherheit kalibrieren, Perspektiven neu rahmen und anspruchsvolle Stakeholder-Kommunikation steuern.',title:'Ein Problem neu rahmen',subtitle:'Von Schuldzuweisung zu Ursachen, Optionen und nächstem Schritt wechseln.',goal:'Eine festgefahrene Diskussion konstruktiv neu ausrichten.',german:'Statt zu fragen, wer schuld ist, sollten wir klären, welche Annahme sich als falsch erwiesen hat.',english:'Rather than asking who is to blame, we should identify which assumption proved to be wrong.',gapSentence:'Rather than ___ on blame, we should look at the conditions that led to the failure.',gapChoices:['focusing','focus','focused','to focus'],gapAnswer:'focusing',listening:'The more useful question is not who made the mistake, but why the process failed to catch it.',listeningMeaning:'Die hilfreichere Frage ist nicht, wer den Fehler gemacht hat, sondern warum der Prozess ihn nicht erkannt hat.',conceptId:'cefr.c1.reframing'},
  {level:'C1',unit:3,lesson:3,unitTitle:'Nuance & Leadership',unitSubtitle:'Unsicherheit kalibrieren, Perspektiven neu rahmen und anspruchsvolle Stakeholder-Kommunikation steuern.',title:'Stakeholder-Update',subtitle:'Komplexen Fortschritt für Führungskräfte knapp, transparent und handlungsorientiert darstellen.',goal:'Ein kritisches Status-Update mit Auswirkung und Maßnahme formulieren.',german:'Der Meilenstein verschiebt sich voraussichtlich um eine Woche; die Kundenfreigabe ist davon derzeit nicht betroffen.',english:'The milestone is likely to slip by one week; at present, this is not expected to affect the customer launch.',gapSentence:'The delay is not expected to have a material ___ on the launch date.',gapChoices:['impact','impacting','implication to','affect'],gapAnswer:'impact',listening:'We have contained the immediate issue and are now validating whether any downstream dependencies are affected.',listeningMeaning:'Wir haben das unmittelbare Problem eingegrenzt und prüfen nun, ob nachgelagerte Abhängigkeiten betroffen sind.',conceptId:'cefr.c1.executive-status'},
  {level:'C1',unit:3,lesson:4,unitTitle:'Nuance & Leadership',unitSubtitle:'Unsicherheit kalibrieren, Perspektiven neu rahmen und anspruchsvolle Stakeholder-Kommunikation steuern.',title:'Kritische Kommunikation',subtitle:'Schlechte Nachrichten klar vermitteln und gleichzeitig Handlungsfähigkeit zeigen.',goal:'Ein ernstes Problem transparent und lösungsorientiert kommunizieren.',german:'Wir haben einen Fehler identifiziert, der einen Teil der Ergebnisse beeinflusst; die betroffenen Daten werden derzeit erneut geprüft.',english:'We have identified an error affecting part of the results, and the relevant data are currently being reviewed again.',gapSentence:'We are taking steps to establish the full ___ of the issue before drawing further conclusions.',gapChoices:['extent','extension','amountness','width'],gapAnswer:'extent',listening:'I do not want to minimise the issue, but we now have a clear process for validating and correcting the affected results.',listeningMeaning:'Ich möchte das Problem nicht herunterspielen, aber wir haben nun einen klaren Prozess zur Prüfung und Korrektur der betroffenen Ergebnisse.',conceptId:'cefr.c1.crisis-communication'},

  {level:'C2',unit:3,lesson:1,unitTitle:'Präzision & Stil',unitSubtitle:'Feinste Bedeutungsunterschiede, diplomatische Distanz und rhetorische Wirkung bewusst kontrollieren.',title:'Position ohne Übertreibung',subtitle:'Starke Aussagen so formulieren, dass Evidenz und Sicherheit exakt zusammenpassen.',goal:'Eine anspruchsvolle These präzise begrenzen.',german:'Die Ergebnisse widerlegen die Hypothese nicht, stellen jedoch eine ihrer zentralen Annahmen erheblich in Frage.',english:'The findings do not disprove the hypothesis, but they do call one of its central assumptions into serious question.',gapSentence:'The evidence does not invalidate the model outright; it does, however, ___ doubt on a key assumption.',gapChoices:['cast','throw','place up','make'],gapAnswer:'cast',listening:'The argument remains plausible, albeit considerably less compelling once these limitations are taken into account.',listeningMeaning:'Das Argument bleibt plausibel, wirkt jedoch deutlich weniger überzeugend, sobald diese Einschränkungen berücksichtigt werden.',conceptId:'cefr.c2.calibrated-stance'},
  {level:'C2',unit:3,lesson:2,unitTitle:'Präzision & Stil',unitSubtitle:'Feinste Bedeutungsunterschiede, diplomatische Distanz und rhetorische Wirkung bewusst kontrollieren.',title:'Diplomatische Distanz',subtitle:'Kritik so formulieren, dass sie präzise bleibt, ohne unnötig konfrontativ zu wirken.',goal:'Eine scharfe Kritik diplomatisch und eindeutig ausdrücken.',german:'Der Vorschlag ist ambitioniert, lässt jedoch wesentliche operative Einschränkungen weitgehend außer Acht.',english:'The proposal is ambitious, but it largely overlooks several material operational constraints.',gapSentence:'The analysis is useful, though it arguably ___ the practical difficulties involved.',gapChoices:['understates','underwrites','underscores completely','undergoes'],gapAnswer:'understates',listening:'I would hesitate to endorse the recommendation without a more explicit treatment of the assumptions on which it depends.',listeningMeaning:'Ich würde zögern, die Empfehlung zu unterstützen, solange die zugrunde liegenden Annahmen nicht ausdrücklicher behandelt werden.',conceptId:'cefr.c2.diplomatic-critique'},
  {level:'C2',unit:3,lesson:3,unitTitle:'Präzision & Stil',unitSubtitle:'Feinste Bedeutungsunterschiede, diplomatische Distanz und rhetorische Wirkung bewusst kontrollieren.',title:'Mehrdeutigkeit auflösen',subtitle:'Unklare Bezüge, implizite Annahmen und mögliche Fehlinterpretationen erkennen.',goal:'Eine potenziell mehrdeutige Aussage präzisieren.',german:'Die Formulierung lässt offen, ob sich die Einschränkung auf die Methode oder auf die Schlussfolgerung bezieht.',english:'The wording leaves it unclear whether the limitation applies to the method or to the conclusion.',gapSentence:'The sentence is ___ in that the reference of “this limitation” is not explicit.',gapChoices:['ambiguous','ambivalent only','equivalent','arbitrary'],gapAnswer:'ambiguous',listening:'A more precise formulation would make the scope of the qualification explicit rather than leaving it to inference.',listeningMeaning:'Eine präzisere Formulierung würde den Geltungsbereich der Einschränkung ausdrücklich machen, statt ihn der Schlussfolgerung zu überlassen.',conceptId:'cefr.c2.ambiguity-control'},
  {level:'C2',unit:3,lesson:4,unitTitle:'Präzision & Stil',unitSubtitle:'Feinste Bedeutungsunterschiede, diplomatische Distanz und rhetorische Wirkung bewusst kontrollieren.',title:'Komplexe Synthese',subtitle:'Mehrere widersprüchliche Perspektiven zu einer belastbaren Gesamtaussage verbinden.',goal:'Uneinheitliche Evidenz in einer ausgewogenen Schlussfolgerung zusammenführen.',german:'Insgesamt sprechen die Quellen für denselben allgemeinen Trend, unterscheiden sich jedoch sowohl hinsichtlich seiner Stärke als auch seiner Ursachen.',english:'Taken as a whole, the sources point to the same broad trend, while differing both on its magnitude and on the mechanisms that may explain it.',gapSentence:'Taken together, the studies are broadly consistent on direction, but less so on the ___ of the effect.',gapChoices:['magnitude','magnification','majority','measurement only'],gapAnswer:'magnitude',listening:'The most defensible conclusion is therefore a qualified one: the pattern is robust, but its interpretation remains contested.',listeningMeaning:'Die am besten vertretbare Schlussfolgerung ist daher eine eingeschränkte: Das Muster ist robust, seine Interpretation bleibt jedoch umstritten.',conceptId:'cefr.c2.synthesis-precision'}
];

const difficulty:Record<Level,4|5>={B2:4,C1:5,C2:5};
const baseXp:Record<Level,number>={B2:12,C1:14,C2:16};
function tokenize(value:string){return value.replace(/([,.!?;:])/g,' $1 ').replace(/\s+/g,' ').trim().split(' ');}
function scramble(value:string){const parts=tokenize(value);const cut=Math.max(2,Math.floor(parts.length*.58));return [...parts.slice(cut),...parts.slice(0,cut)];}
function peers(bp:Blueprint){return blueprints.filter(item=>item.level===bp.level&&item!==bp);}
function makeLesson(bp:Blueprint):Lesson{
  const id=`en-${bp.level.toLowerCase()}-u${bp.unit}-l${bp.lesson}`,conceptIds=[bp.conceptId],xp=baseXp[bp.level];
  const alternatives=peers(bp).slice(0,3),sentenceChoices=[bp.english,...alternatives.map(item=>item.english)].slice(0,4),meaningChoices=[bp.listeningMeaning,...alternatives.map(item=>item.listeningMeaning)].slice(0,4);
  return {id,courseId:'de-en',level:bp.level,unitId:`en-${bp.level.toLowerCase()}-u${bp.unit}`,title:bp.title,subtitle:bp.subtitle,estimatedMinutes:11,newConcepts:conceptIds,exercises:[
    {id:`${id}-e1`,type:'multiple-choice',instruction:'Wähle die präziseste englische Entsprechung.',prompt:bp.german,choices:sentenceChoices,answer:bp.english,conceptIds,difficulty:difficulty[bp.level],xp,explanation:`Trainingsziel: ${bp.goal}`},
    {id:`${id}-e2`,type:'translation',instruction:'Übertrage die Aussage idiomatisch und registergerecht ins Englische.',prompt:bp.goal,sourceText:bp.german,acceptedAnswers:[bp.english],conceptIds,difficulty:difficulty[bp.level],xp:xp+2},
    {id:`${id}-e3`,type:'sentence-build',instruction:'Rekonstruiere die vollständige Formulierung.',prompt:bp.german,tokens:scramble(bp.english),answer:bp.english,conceptIds,difficulty:difficulty[bp.level],xp:xp+2},
    {id:`${id}-e4`,type:'fill-gap',instruction:'Wähle die lexikalisch und stilistisch passendste Ergänzung.',prompt:bp.goal,sentence:bp.gapSentence,choices:bp.gapChoices,answer:bp.gapAnswer,conceptIds,difficulty:difficulty[bp.level],xp},
    {id:`${id}-e5`,type:'listening',instruction:'Höre auf Haltung, Einschränkung und Kernaussage.',prompt:'Wähle die treffendste Bedeutung.',speech:bp.listening,choices:meaningChoices,answer:bp.listeningMeaning,conceptIds,difficulty:difficulty[bp.level],xp:xp+3},
    {id:`${id}-e6`,type:'dictation',instruction:'Schreibe die Aussage möglichst präzise auf.',prompt:'Achte besonders auf kleine Wörter, die die Aussage abschwächen oder begrenzen.',speech:bp.listening,acceptedAnswers:[bp.listening],conceptIds,difficulty:difficulty[bp.level],xp:xp+4},
    {id:`${id}-e7`,type:'speaking',instruction:'Sprich die Formulierung kontrolliert und natürlich.',prompt:bp.goal,speech:bp.english,acceptedAnswers:[bp.english],conceptIds,difficulty:difficulty[bp.level],xp:xp+4},
    {id:`${id}-e8`,type:'multiple-choice',instruction:'Welche Formulierung erfüllt das kommunikative Ziel am präzisesten?',prompt:bp.goal,choices:sentenceChoices,answer:bp.english,conceptIds,difficulty:difficulty[bp.level],xp:xp+2}
  ]};
}
function unitFor(level:Level){const unit=3,items=blueprints.filter(item=>item.level===level),first=items[0];return {id:`en-${level.toLowerCase()}-u${unit}`,number:unit,title:first.unitTitle,subtitle:first.unitSubtitle,lessons:items.map(makeLesson)};}
export const englishB2ReleaseUnits=[unitFor('B2')];
export const englishC1ReleaseUnits=[unitFor('C1')];
export const englishC2ReleaseUnits=[unitFor('C2')];
