import workerV4 from './worker-v4.js';

const ADMIN_COOKIE='vf_admin';
const USER_COOKIE='vf_session';
const ADMIN_SESSION_HOURS=12;
const USER_SESSION_DAYS=30;
const PASSWORD_ITERATIONS=100000;
const API_VERSION='vocabfast-v5-admin-tests';
const TEST_MODEL='@cf/google/gemma-4-26b-a4b-it';
const enc=new TextEncoder();

function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-VocabFast-API':API_VERSION,...headers}})}
function clean(v,max=200){return String(v??'').trim().replace(/\s+/g,' ').slice(0,max)}
function normalizeEmail(v){return String(v||'').trim().toLowerCase()}
function parseCookies(req){const out={};for(const p of (req.headers.get('Cookie')||'').split(';')){const i=p.indexOf('=');if(i>0)out[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())}return out}
function secureCookie(req){return new URL(req.url).protocol==='https:'?'; Secure':''}
function cookie(name,value,req,maxAge,sameSite='Strict'){return `${name}=${encodeURIComponent(value)}; Path=/; HttpOnly; SameSite=${sameSite}${secureCookie(req)}; Max-Age=${maxAge}`}
function urlB64(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
function standardB64(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s)}
function fromB64(s){return Uint8Array.from(atob(String(s||'')),c=>c.charCodeAt(0))}
function rand(n=32){return urlB64(crypto.getRandomValues(new Uint8Array(n)))}
async function hexHash(v){const h=new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(String(v))));return [...h].map(x=>x.toString(16).padStart(2,'0')).join('')}
function safeEqual(a,b){a=String(a??'');b=String(b??'');if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0}
function bucket(env){if(!env?.PDFS?.get||!env?.PDFS?.put)throw Object.assign(new Error('R2 ist nicht verbunden.'),{status:503});return env.PDFS}
async function getJson(b,k){const o=await b.get(k);if(!o)return null;try{return JSON.parse(await o.text())}catch{return null}}
async function putJson(b,k,v){await b.put(k,JSON.stringify(v),{httpMetadata:{contentType:'application/json; charset=utf-8'}})}
async function listKeys(b,prefix){const out=[];let cursor;do{const page=await b.list({prefix,cursor,limit:1000});for(const x of page.objects||[])out.push(x.key);cursor=page.truncated?page.cursor:undefined}while(cursor);return out}
async function deleteKeys(b,keys){for(let i=0;i<keys.length;i+=1000){const part=keys.slice(i,i+1000);if(part.length)await b.delete(part)}}
async function body(req){try{return await req.json()}catch{return {}}}
const profileKey=id=>`accounts/profiles/${id}.json`;
const stateKey=id=>`accounts/state/${id}.json`;
const userSessionKey=(id,h)=>`accounts/sessions/${id}/${h}.json`;
const adminSessionKey=h=>`admin/sessions/${h}.json`;
const emailKey=async email=>`accounts/emails/${await hexHash(normalizeEmail(email))}.json`;

async function derivePassword(password,salt,iterations=PASSWORD_ITERATIONS){const key=await crypto.subtle.importKey('raw',enc.encode(String(password)),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt,iterations},key,256);return standardB64(new Uint8Array(bits))}
async function verifyPassword(profile,password){const salt=profile?.passwordSalt??profile?.password_salt,hash=profile?.passwordHash??profile?.password_hash,iterations=Number(profile?.passwordIterations??profile?.password_iterations??PASSWORD_ITERATIONS);if(!salt||!hash||iterations>100000)return false;try{return safeEqual(await derivePassword(password,fromB64(salt),iterations),hash)}catch{return false}}
function effectivePlan(p){if(p?.plan!=='pro')return 'free';if(!p.proUntil)return 'pro';const t=Date.parse(p.proUntil);return Number.isFinite(t)&&t>Date.now()?'pro':'free'}
function publicProfile(p){if(!p)return null;return {id:p.id,email:p.email,name:p.name||'',createdAt:p.createdAt||0,disabled:!!p.disabled,adminNote:p.adminNote||'',plan:p.plan==='pro'?'pro':'free',effectivePlan:effectivePlan(p),proUntil:p.proUntil||null,mustChangePassword:!!p.mustChangePassword}}

async function regularUser(req,env){const raw=parseCookies(req)[USER_COOKIE];if(!raw)return null;const dot=raw.indexOf('.');if(dot<1)return null;const id=raw.slice(0,dot),token=raw.slice(dot+1);if(!/^[0-9a-f-]{20,60}$/i.test(id)||token.length<20)return null;const b=bucket(env),h=await hexHash(token),s=await getJson(b,userSessionKey(id,h));if(!s||Number(s.expiresAt)<=Date.now())return null;const p=await getJson(b,profileKey(id));return p?{profile:p,tokenHash:h}:null}
async function createUserSession(b,id,req){const token=rand(),h=await hexHash(token),now=Date.now();await putJson(b,userSessionKey(id,h),{userId:id,createdAt:now,expiresAt:now+USER_SESSION_DAYS*86400000});return cookie(USER_COOKIE,`${id}.${token}`,req,USER_SESSION_DAYS*86400,'Lax')}
async function augmentedMe(req,env){const u=await regularUser(req,env);return json({user:u?publicProfile(u.profile):null})}
async function changeOwnPassword(req,env){const u=await regularUser(req,env);if(!u)return json({error:'Bitte zuerst anmelden.'},401);const x=await body(req),current=String(x.currentPassword||''),next=String(x.newPassword||'');if(next.length<12)return json({error:'Das neue Passwort muss mindestens 12 Zeichen lang sein.'},400);if(!(await verifyPassword(u.profile,current)))return json({error:'Das aktuelle Passwort ist falsch.'},401);const salt=crypto.getRandomValues(new Uint8Array(16));u.profile.passwordSalt=standardB64(salt);u.profile.passwordHash=await derivePassword(next,salt);u.profile.passwordIterations=PASSWORD_ITERATIONS;u.profile.passwordAlgo='PBKDF2-SHA256';u.profile.mustChangePassword=false;const b=bucket(env);await putJson(b,profileKey(u.profile.id),u.profile);await deleteKeys(b,await listKeys(b,`accounts/sessions/${u.profile.id}/`));const setCookie=await createUserSession(b,u.profile.id,req);return json({ok:true,user:publicProfile(u.profile)},200,{'Set-Cookie':setCookie})}

async function adminSession(req,env){const raw=parseCookies(req)[ADMIN_COOKIE];if(!raw)return null;const h=await hexHash(raw),b=bucket(env),s=await getJson(b,adminSessionKey(h));if(!s||s.expiresAt<=Date.now())return null;return {username:'admin',createdAt:s.createdAt,expiresAt:s.expiresAt}}
async function requireAdmin(req,env){const a=await adminSession(req,env);if(!a)throw Object.assign(new Error('Admin-Anmeldung erforderlich.'),{status:401,code:'ADMIN_REQUIRED'});return a}
async function adminLogin(req,env){const x=await body(req),username=clean(x.username,40),password=String(x.password||''),expectedUser=String(env.ADMIN_USERNAME||'admin');if(username!==expectedUser)return json({error:'Admin-Zugangsdaten sind falsch.'},401);if(!env.ADMIN_PASSWORD)return json({error:'Admin-Passwort ist in Cloudflare noch nicht als Secret eingerichtet.',code:'ADMIN_SECRET_MISSING'},503);if(!safeEqual(password,String(env.ADMIN_PASSWORD)))return json({error:'Admin-Zugangsdaten sind falsch.'},401);const token=rand(),h=await hexHash(token),now=Date.now();await putJson(bucket(env),adminSessionKey(h),{createdAt:now,expiresAt:now+ADMIN_SESSION_HOURS*3600000});return json({ok:true,admin:{username:expectedUser}},200,{'Set-Cookie':cookie(ADMIN_COOKIE,token,req,ADMIN_SESSION_HOURS*3600)})}
async function adminLogout(req,env){const raw=parseCookies(req)[ADMIN_COOKIE];if(raw)await bucket(env).delete(adminSessionKey(await hexHash(raw))).catch(()=>{});return json({ok:true},200,{'Set-Cookie':cookie(ADMIN_COOKIE,'',req,0)})}
async function usersList(req,env){await requireAdmin(req,env);const b=bucket(env),keys=await listKeys(b,'accounts/profiles/'),users=[];for(const k of keys){const p=await getJson(b,k);if(!p?.id)continue;const s=await getJson(b,stateKey(p.id))||{};users.push({...publicProfile(p),words:Array.isArray(s.learning)?s.learning.length:0,xp:Number(s.stats?.xp||0),grammarAnswered:Number(s.stats?.grammarAnswered||0),vocabAnswered:Number(s.stats?.vocabAnswered||0)});}users.sort((a,z)=>(z.createdAt||0)-(a.createdAt||0));return json({users})}
async function userDetail(req,env,id){await requireAdmin(req,env);const b=bucket(env),p=await getJson(b,profileKey(id));if(!p)return json({error:'Konto nicht gefunden.'},404);const s=await getJson(b,stateKey(id))||{};const pdfCount=(await listKeys(b,`pdfmeta/${id}/`)).length;return json({profile:publicProfile(p),state:s,pdfCount})}
async function updateAdminUser(req,env,id){await requireAdmin(req,env);const b=bucket(env),p=await getJson(b,profileKey(id));if(!p)return json({error:'Konto nicht gefunden.'},404);const x=await body(req);if('name'in x)p.name=clean(x.name,60);if('disabled'in x)p.disabled=!!x.disabled;if('adminNote'in x)p.adminNote=clean(x.adminNote,500);if('plan'in x)p.plan=x.plan==='pro'?'pro':'free';if('proUntil'in x){const v=clean(x.proUntil,40);p.proUntil=v&&Number.isFinite(Date.parse(v))?new Date(v).toISOString():null}if('email'in x){const next=normalizeEmail(x.email);if(!/^\S+@\S+\.\S+$/.test(next))return json({error:'Ungültige E-Mail-Adresse.'},400);if(next!==normalizeEmail(p.email)){const existing=await getJson(b,await emailKey(next));if(existing?.userId&&existing.userId!==id)return json({error:'Diese E-Mail wird bereits verwendet.'},409);await b.delete(await emailKey(p.email));await putJson(b,await emailKey(next),{userId:id,email:next});p.email=next}}await putJson(b,profileKey(id),p);return json({profile:publicProfile(p)})}
async function updateAdminState(req,env,id){await requireAdmin(req,env);const b=bucket(env);if(!(await getJson(b,profileKey(id))))return json({error:'Konto nicht gefunden.'},404);const x=await body(req),next=x.state??x,text=JSON.stringify(next);if(text.length>5_000_000)return json({error:'Lernstand ist zu groß.'},413);await putJson(b,stateKey(id),next);return json({ok:true})}
async function revokeSessions(req,env,id){await requireAdmin(req,env);const b=bucket(env);await deleteKeys(b,await listKeys(b,`accounts/sessions/${id}/`));return json({ok:true})}
async function deleteAdminUser(req,env,id){await requireAdmin(req,env);const b=bucket(env),p=await getJson(b,profileKey(id));if(!p)return json({error:'Konto nicht gefunden.'},404);const prefixes=[`accounts/sessions/${id}/`,`pdfmeta/${id}/`,`pdfs/${id}/`],keys=[];for(const prefix of prefixes)keys.push(...await listKeys(b,prefix));keys.push(profileKey(id),stateKey(id),await emailKey(p.email));await deleteKeys(b,keys);return json({ok:true})}
async function resetPassword(req,env,id){await requireAdmin(req,env);const x=await body(req),password=String(x.password||'');if(password.length<12)return json({error:'Temporäres Passwort muss mindestens 12 Zeichen haben.'},400);const b=bucket(env),p=await getJson(b,profileKey(id));if(!p)return json({error:'Konto nicht gefunden.'},404);const salt=crypto.getRandomValues(new Uint8Array(16));p.passwordSalt=standardB64(salt);p.passwordHash=await derivePassword(password,salt);p.passwordIterations=PASSWORD_ITERATIONS;p.passwordAlgo='PBKDF2-SHA256';p.mustChangePassword=true;await putJson(b,profileKey(id),p);await deleteKeys(b,await listKeys(b,`accounts/sessions/${id}/`));return json({ok:true,mustChangePassword:true})}
async function blockDisabledLogin(req,env){const x=await body(req.clone()),email=normalizeEmail(x.email);if(!email)return null;const b=bucket(env),idx=await getJson(b,await emailKey(email));if(!idx?.userId)return null;const p=await getJson(b,profileKey(idx.userId));return p?.disabled?json({error:'Dieses Konto wurde vom Administrator vorübergehend gesperrt.',code:'ACCOUNT_DISABLED'},403):null}

function extractJsonArray(text){const raw=String(text||'').replace(/```(?:json)?/gi,'').replace(/```/g,'').trim();try{const x=JSON.parse(raw);return Array.isArray(x)?x:Array.isArray(x?.questions)?x.questions:[]}catch{}const a=raw.indexOf('['),z=raw.lastIndexOf(']');if(a>=0&&z>a)try{return JSON.parse(raw.slice(a,z+1))}catch{}return []}
function normalizeQ(q){if(!q||typeof q!=='object')return null;const text=clean(q.text??q.question,260),answer=clean(q.answer,120),topic=clean(q.topic,120),level=clean(q.level,3).toUpperCase(),explanation=clean(q.explanation,300),options=Array.isArray(q.options)?q.options.map(x=>clean(x,120)).filter(Boolean):[];if(!text||!answer||options.length<3||!options.includes(answer))return null;return {text,answer,options:[...new Set(options)].slice(0,4),topic,level:/^(A1|A2|B1|B2|C1|C2)$/.test(level)?level:'B2',explanation}}
async function authenticated(req,env){return !!(await regularUser(req,env))}
async function grammarTest(req,env){if(!(await authenticated(req,env)))return json({error:'Bitte zuerst anmelden.'},401);if(!env.AI?.run)return json({error:'Workers AI ist für Übungs-/Prüfungsgenerierung nicht verfügbar.'},503);const x=await body(req),areas=Array.isArray(x.areas)?x.areas.map(v=>clean(v,120)).filter(Boolean).slice(0,20):[],levels=Array.isArray(x.levels)?x.levels.map(v=>clean(v,3).toUpperCase()).filter(v=>/^(A1|A2|B1|B2|C1|C2)$/.test(v)):[],count=Math.max(5,Math.min(50,Number(x.count)||50)),practice=x.mode==='practice';if(!areas.length&&!levels.length)return json({error:'Bitte mindestens einen Grammatikbereich auswählen.'},400);const prompt=`Erstelle ${count} unterschiedliche Englisch-Grammatik-${practice?'Übungsfragen':'Prüfungsfragen'} für einen deutschsprachigen Lernenden. Orientierung an typischen CEFR-Aufgabenformaten, aber KEIN offizieller Cambridge/IELTS/TOEFL-Test. CEFR-Stufen: ${levels.join(', ')||'gemischt'}. Grammatikbereiche: ${areas.join('; ')||'alle passenden Bereiche'}. Keine doppelten oder nahezu identischen Sätze. Mischung aus Lückentext, Fehlererkennung, Satzwahl und Meaning-in-context. Antworte ausschließlich als JSON-Array mit Objekten {"text":"...","answer":"...","options":["...","...","...","..."],"topic":"genau geprüfter Grammatikbereich","level":"A1|A2|B1|B2|C1|C2","explanation":"kurze Begründung"}. answer muss exakt in options enthalten sein.`;try{const r=await env.AI.run(TEST_MODEL,{prompt,max_tokens:12000,temperature:.25});const arr=extractJsonArray(r?.response??r?.result?.response??r?.text).map(normalizeQ).filter(Boolean),seen=new Map();for(const q of arr)if(!seen.has(q.text.toLowerCase()))seen.set(q.text.toLowerCase(),q);const qs=[...seen.values()].slice(0,count);if(qs.length<count)return json({error:`Die KI hat nur ${qs.length} verwertbare eindeutige Fragen erzeugt. Bitte erneut starten.`,code:'TEST_INCOMPLETE'},502);return json({questions:qs,model:TEST_MODEL,disclaimer:'CEFR-orientierte VocabFast-Aufgaben, kein offizieller externer Sprachtest.'})}catch(e){console.error(e);return json({error:'Die Grammatikfragen konnten gerade nicht erzeugt werden.'},503)}}

export default{async fetch(request,env){const path=new URL(request.url).pathname;try{
  if(path==='/api/admin/login'&&request.method==='POST')return adminLogin(request,env);
  if(path==='/api/admin/logout'&&request.method==='POST')return adminLogout(request,env);
  if(path==='/api/admin/me'&&request.method==='GET'){const a=await adminSession(request,env);return json({admin:a})}
  if(path==='/api/admin/users'&&request.method==='GET')return usersList(request,env);
  const m=path.match(/^\/api\/admin\/users\/([^/]+)(?:\/(state|password|sessions))?$/);if(m){const id=m[1],sub=m[2];if(request.method==='GET'&&!sub)return userDetail(request,env,id);if(request.method==='PUT'&&!sub)return updateAdminUser(request,env,id);if(request.method==='PUT'&&sub==='state')return updateAdminState(request,env,id);if(request.method==='POST'&&sub==='password')return resetPassword(request,env,id);if(request.method==='DELETE'&&sub==='sessions')return revokeSessions(request,env,id);if(request.method==='DELETE'&&!sub)return deleteAdminUser(request,env,id)}
  if(path==='/api/tests/grammar/generate'&&request.method==='POST')return grammarTest(request,env);
  if(path==='/api/account/password'&&request.method==='POST')return changeOwnPassword(request,env);
  if(path==='/api/me'&&request.method==='GET')return augmentedMe(request,env);
  if(path==='/api/auth/login'&&request.method==='POST'){const blocked=await blockDisabledLogin(request,env);if(blocked)return blocked}
  return workerV4.fetch(request,env);
}catch(e){console.error('v5 error',e?.stack||e);return json({error:e?.message||'Interner Serverfehler.',code:e?.code},e?.status||500)}}};
