import workerV10 from './worker-v10.js';

const USER_COOKIE='vf_session',ADMIN_COOKIE='vf_admin',enc=new TextEncoder();
const MOD_CAPS=['report','comment','document'];
function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-VocabFast-API':'vocabfast-v16.1-moderation',...headers}})}
function cookies(req){const out={};for(const p of (req.headers.get('Cookie')||'').split(';')){const i=p.indexOf('=');if(i>0)out[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())}return out}
async function sha(v){const b=new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(String(v))));return [...b].map(x=>x.toString(16).padStart(2,'0')).join('')}
function bucket(env){if(!env?.PDFS?.get||!env?.PDFS?.put||!env?.PDFS?.list)throw Object.assign(new Error('R2 ist nicht verbunden.'),{status:503});return env.PDFS}
async function getJson(b,k){const o=await b.get(k);if(!o)return null;try{return JSON.parse(await o.text())}catch{return null}}
async function putJson(b,k,v){await b.put(k,JSON.stringify(v),{httpMetadata:{contentType:'application/json; charset=utf-8'}})}
async function body(req){try{return await req.json()}catch{return {}}}
function cleanText(v,max=4000){return String(v??'').replace(/\0/g,'').trim().slice(0,max)}
function randId(prefix='mod'){const a=crypto.getRandomValues(new Uint8Array(8));return `${prefix}_${Date.now().toString(36)}_${[...a].map(x=>x.toString(16).padStart(2,'0')).join('')}`}
async function currentUser(req,env){const raw=cookies(req)[USER_COOKIE];if(!raw)return null;const dot=raw.indexOf('.');if(dot<1)return null;const id=raw.slice(0,dot),token=raw.slice(dot+1);if(!id||token.length<20)return null;const b=bucket(env),s=await getJson(b,`accounts/sessions/${id}/${await sha(token)}.json`);if(!s||Number(s.expiresAt)<=Date.now())return null;const profile=await getJson(b,`accounts/profiles/${id}.json`);return profile?{profile}:null}
async function adminContext(req,env){const raw=cookies(req)[ADMIN_COOKIE];if(!raw)return null;const b=bucket(env),s=await getJson(b,`admin/sessions/${await sha(raw)}.json`);if(!s||Number(s.expiresAt)<=Date.now())return null;if(!s.staffUserId)return {superadmin:true,name:'Superadmin'};return {superadmin:false,staffUserId:s.staffUserId}}
function moderatorSettings(p){const m=p?.moderator&&typeof p.moderator==='object'?p.moderator:{},enabled=!!m.enabled;return {enabled,capabilities:enabled?[...MOD_CAPS]:[],note:cleanText(m.note,500),grantedAt:m.grantedAt||null,grantedBy:m.grantedBy||null}}
async function actor(req,env){const admin=await adminContext(req,env);if(admin?.superadmin)return {kind:'admin',id:'superadmin',name:'Superadmin',superadmin:true,capabilities:[...MOD_CAPS]};const u=await currentUser(req,env);if(!u)return null;const settings=moderatorSettings(u.profile);if(!settings.enabled)return null;return {kind:'moderator',id:u.profile.id,name:u.profile.name||u.profile.email||'Moderator',superadmin:false,capabilities:[...MOD_CAPS]}}
function requireCap(a,cap){if(!a)throw Object.assign(new Error('Moderator- oder Adminberechtigung erforderlich.'),{status:401});if(a.superadmin)return;if(!a.capabilities.includes(cap))throw Object.assign(new Error('Für diese Moderationsfunktion fehlt dir die Freigabe.'),{status:403,code:'MODERATOR_CAPABILITY_REQUIRED'})}
async function moderatorAdmin(req,env,id){const admin=await adminContext(req,env);if(!admin?.superadmin)throw Object.assign(new Error('Nur der Superadmin darf die Moderatorrolle vergeben.'),{status:403});const b=bucket(env),key=`accounts/profiles/${id}.json`,p=await getJson(b,key);if(!p)return json({error:'Konto nicht gefunden.'},404);if(req.method==='GET')return json({moderator:moderatorSettings(p)});const x=await body(req),enabled=!!x.enabled;p.moderator={enabled,capabilities:enabled?[...MOD_CAPS]:[],note:cleanText(x.note,500),grantedAt:enabled?(p.moderator?.grantedAt||new Date().toISOString()):null,grantedBy:enabled?'superadmin':null};await putJson(b,key,p);return json({ok:true,moderator:moderatorSettings(p)})}
async function listIssues(env){const b=bucket(env),out=[];let cursor;do{const page=await b.list({prefix:'moderation/issues/',cursor,limit:500});for(const o of page.objects||[]){const d=await getJson(b,o.key);if(d)out.push(d)}cursor=page.truncated?page.cursor:null}while(cursor);return out.sort((a,z)=>String(z.updatedAt||z.createdAt).localeCompare(String(a.updatedAt||a.createdAt))).slice(0,500)}
async function moderationContext(req,env){const a=await actor(req,env);if(!a)return json({enabled:false},200);const issues=await listIssues(env);return json({enabled:true,role:a.superadmin?'admin':'moderator',capabilities:a.capabilities,openCount:issues.filter(x=>x.status!=='done'&&x.status!=='rejected').length})}
async function moderationIssues(req,env){const a=await actor(req,env);if(!a)return json({error:'Moderator- oder Adminberechtigung erforderlich.'},401);if(req.method==='GET')return json({issues:await listIssues(env)});requireCap(a,'report');const x=await body(req),title=cleanText(x.title,140),description=cleanText(x.description,5000),category=['Fehler','Inhalt','Bedienung','Verbesserung','Dokumentation'].includes(x.category)?x.category:'Verbesserung';if(title.length<4||description.length<8)return json({error:'Bitte Titel und Beschreibung vollständig ausfüllen.'},400);const now=new Date().toISOString(),id=randId('issue'),issue={id,title,description,category,page:cleanText(x.page,500),priority:['niedrig','normal','hoch','kritisch'].includes(x.priority)?x.priority:'normal',status:'open',createdAt:now,updatedAt:now,createdBy:{id:a.id,name:a.name,kind:a.kind},comments:[]};await putJson(bucket(env),`moderation/issues/${id}.json`,issue);return json({ok:true,issue},201)}
async function oneIssue(req,env,id,action){const a=await actor(req,env);if(!a)return json({error:'Moderator- oder Adminberechtigung erforderlich.'},401);const b=bucket(env),key=`moderation/issues/${id}.json`,issue=await getJson(b,key);if(!issue)return json({error:'Beanstandung nicht gefunden.'},404);if(action==='comments'&&req.method==='POST'){requireCap(a,'comment');const x=await body(req),text=cleanText(x.text,3000);if(text.length<2)return json({error:'Kommentar ist zu kurz.'},400);issue.comments=Array.isArray(issue.comments)?issue.comments:[];issue.comments.push({id:randId('comment'),text,createdAt:new Date().toISOString(),author:{id:a.id,name:a.name,kind:a.kind}});issue.comments=issue.comments.slice(-250);issue.updatedAt=new Date().toISOString();await putJson(b,key,issue);return json({ok:true,issue})}if(req.method==='PATCH'){if(!a.superadmin)return json({error:'Nur der Superadmin darf Status und Priorität ändern.'},403);const x=await body(req);if(['open','review','planned','done','rejected'].includes(x.status))issue.status=x.status;if(['niedrig','normal','hoch','kritisch'].includes(x.priority))issue.priority=x.priority;if('adminNote'in x)issue.adminNote=cleanText(x.adminNote,3000);issue.updatedAt=new Date().toISOString();await putJson(b,key,issue);return json({ok:true,issue})}return json({error:'Nicht unterstützte Moderationsaktion.'},405)}

export default {async fetch(req,env){const path=new URL(req.url).pathname;try{
  let m=path.match(/^\/api\/admin\/users\/([^/]+)\/moderator$/);if(m&&(req.method==='GET'||req.method==='PUT'))return await moderatorAdmin(req,env,decodeURIComponent(m[1]));
  if(path==='/api/moderation/context'&&req.method==='GET')return await moderationContext(req,env);
  if(path==='/api/moderation/issues'&&(req.method==='GET'||req.method==='POST'))return await moderationIssues(req,env);
  m=path.match(/^\/api\/moderation\/issues\/([^/]+)(?:\/(comments))?$/);if(m&&(req.method==='POST'||req.method==='PATCH'))return await oneIssue(req,env,decodeURIComponent(m[1]),m[2]||'issue');
  return workerV10.fetch(req,env);
}catch(e){console.error('v16 moderation error',e);return json({error:e?.message||'Interner Serverfehler.',code:e?.code},e?.status||500)}}};
