import workerV4 from './worker-v4.js';

const ADMIN_COOKIE='vf_admin';
const ADMIN_SESSION_HOURS=12;
const API_VERSION='vocabfast-v5-admin-tests';
const TEST_MODEL='@cf/google/gemma-4-26b-a4b-it';

const enc=new TextEncoder();
function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-VocabFast-API':API_VERSION,...headers}})}
function clean(v,max=200){return String(v??'').trim().replace(/\s+/g,' ').slice(0,max)}
function parseCookies(req){const out={};for(const p of (req.headers.get('Cookie')||'').split(';')){const i=p.indexOf('=');if(i>0)out[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())}return out}
function secureCookie(req){return new URL(req.url).protocol==='https:'?'; Secure':''}
function cookie(name,value,req,maxAge){return `${name}=${encodeURIComponent(value)}; Path=/; HttpOnly; SameSite=Strict${secureCookie(req)}; Max-Age=${maxAge}`}
function b64(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
function rand(n=32){return b64(crypto.getRandomValues(new Uint8Array(n)))}
async function hexHash(v){const h=new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(String(v))));return [...h].map(x=>x.toString(16).padStart(2,'0')).join('')}
function safeEqual(a,b){a=String(a??'');b=String(b??'');if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0}
function bucket(env){if(!env?.PDFS?.get||!env?.PDFS?.put)throw Object.assign(new Error('R2 ist nicht verbunden.'),{status:503});return env.PDFS}
async function getJson(b,k){const o=await b.get(k);if(!o)return null;try{return JSON.parse(await o.text())}catch{return null}}
async function putJson(b,k,v){await b.put(k,JSON.stringify(v),{httpMetadata:{contentType:'application/json; charset=utf-8'}})}
async function listKeys(b,prefix){const out=[];let cursor;do{const page=await b.list({prefix,cursor,limit:1000});for(const x of page.objects||[])out.push(x.key);cursor=page.truncated?page.cursor:undefined}while(cursor);return out}
async function deleteKeys(b,keys){for(let i=0;i<keys.length;i+=1000){const part=keys.slice(i,i+1000);if(part.length)await b.delete(part)}}
async function body(req){try{return await req.json()}catch{return {}}}
const profileKey=id=>`accounts/profiles/${id}.json`;
const stateKey=id=>`accounts/state/${id}.json`;
const adminSessionKey=h=>`admin/sessions/${h}.json`;
const emailKey=async email=>`accounts/emails/${await hexHash(String(email||'').trim().toLowerCase())}.json`;

async function adminSession(req,env){const raw=parseCookies(req)[ADMIN_COOKIE];if(!raw)return null;const h=await hexHash(raw),b=bucket(env),s=await getJson(b,adminSessionKey(h));if(!s||s.expiresAt<=Date.now())return null;return {username:'admin',createdAt:s.createdAt,expiresAt:s.expiresAt}}
async function requireAdmin(req,env){const a=await adminSession(req,env);if(!a)throw Object.assign(new Error('Admin-Anmeldung erforderlich.'),{status:401,code:'ADMIN_REQUIRED'});return a}
async function adminLogin(req,env){const x=await body(req),username=clean(x.username,40),password=String(x.password||'');if(username!=='admin')return json({error:'Admin-Zugangsdaten sind falsch.'},401);if(!env.ADMIN_PASSWORD)return json({error:'Admin-Passwort ist in Cloudflare noch nicht als Secret eingerichtet.',code:'ADMIN_SECRET_MISSING'},503);if(!safeEqual(password,String(env.ADMIN_PASSWORD)))return json({error:'Admin-Zugangsdaten sind falsch.'},401);const token=rand(),h=await hexHash(token),now=Date.now();await putJson(bucket(env),adminSessionKey(h),{createdAt:now,expiresAt:now+ADMIN_SESSION_HOURS*3600000});return json({ok:true,admin:{username:'admin'}},200,{'Set-Cookie':cookie(ADMIN_COOKIE,token,req,ADMIN_SESSION_HOURS*3600)})}
async function adminLogout(req,env){const raw=parseCookies(req)[ADMIN_COOKIE];if(raw)await bucket(env).delete(adminSessionKey(await hexHash(raw))).catch(()=>{});return json({ok:true},200,{'Set-Cookie':cookie(ADMIN_COOKIE,'',req,0)})}
function publicProfile(p){if(!p)return null;return {id:p.id,email:p.email,name:p.name||'',createdAt:p.createdAt||0,disabled:!!p.disabled,adminNote:p.adminNote||''}}
async function usersList(req,env){await requireAdmin(req,env);const b=bucket(env),keys=await listKeys(b,'accounts/profiles/'),users=[];for(const k of keys){const p=await getJson(b,k);if(!p?.id)continue;const s=await getJson(b,stateKey(p.id))||{};users.push({...publicProfile(p),words:Array.isArray(s.learning)?s.learning.length:0,xp:Number(s.stats?.xp||0),grammarAnswered:Number(s.stats?.grammarAnswered||0),vocabAnswered:Number(s.stats?.vocabAnswered||0)});}users.sort((a,z)=>(z.createdAt||0)-(a.createdAt||0));return json({users})}
async function userDetail(req,env,id){await requireAdmin(req,env);const b=bucket(env),p=await getJson(b,profileKey(id));if(!p)return json({error:'Konto nicht gefunden.'},404);const s=await getJson(b,stateKey(id))||{};const pdfCount=(await listKeys(b,`pdfmeta/${id}/`)).length;return json({profile:publicProfile(p),state:s,pdfCount})}
async function updateAdminUser(req,env,id){await requireAdmin(req,env);const b=bucket(env),p=await getJson(b,profileKey(id));if(!p)return json({error:'Konto nicht gefunden.'},404);const x=await body(req);if('name'in x)p.name=clean(x.name,60);if('disabled'in x)p.disabled=!!x.disabled;if('adminNote'in x)p.adminNote=clean(x.adminNote,500);await putJson(b,profileKey(id),p);return json({profile:publicProfile(p)})}
async function updateAdminState(req,env,id){await requireAdmin(req,env);const b=bucket(env);if(!(await getJson(b,profileKey(id))))return json({error:'Konto nicht gefunden.'},404);const x=await body(req);const text=JSON.stringify(x.state??x);if(text.length>5_000_000)return json({error:'Lernstand ist zu groß.'},413);await putJson(b,stateKey(id),x.state??x);return json({ok:true})}
async function deleteAdminUser(req,env,id){await requireAdmin(req,env);const b=bucket(env),p=await getJson(b,profileKey(id));if(!p)return json({error:'Konto nicht gefunden.'},404);const prefixes=[`accounts/sessions/${id}/`,`pdfmeta/${id}/`,`pdfs/${id}/`],keys=[];for(const prefix of prefixes)keys.push(...await listKeys(b,prefix));keys.push(profileKey(id),stateKey(id),await emailKey(p.email));await deleteKeys(b,keys);return json({ok:true})}
async function hashPassword(password,salt,iterations=100000){const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt,iterations},key,256);return b64(new Uint8Array(bits)).replaceAll('-','+').replaceAll('_','/');}
function standardB64(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s)}
async function resetPassword(req,env,id){await requireAdmin(req,env);const x=await body(req),password=String(x.password||'');if(password.length<12)return json({error:'Temporäres Passwort muss mindestens 12 Zeichen haben.'},400);const b=bucket(env),p=await getJson(b,profileKey(id));if(!p)return json({error:'Konto nicht gefunden.'},404);const salt=crypto.getRandomValues(new Uint8Array(16));const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt,iterations:100000},key,256);p.passwordSalt=standardB64(salt);p.passwordHash=standardB64(new Uint8Array(bits));p.passwordIterations=100000;p.passwordAlgo='PBKDF2-SHA256';await putJson(b,profileKey(id),p);await deleteKeys(b,await listKeys(b,`accounts/sessions/${id}/`));return json({ok:true})}
async function blockDisabledLogin(req,env){const clone=req.clone(),x=await body(clone),email=String(x.email||'').trim().toLowerCase();if(!email)return null;const b=bucket(env),idx=await getJson(b,await emailKey(email));if(!idx?.userId)return null;const p=await getJson(b,profileKey(idx.userId));return p?.disabled?json({error:'Dieses Konto wurde vom Administrator vorübergehend gesperrt.',code:'ACCOUNT_DISABLED'},403):null}

function extractJsonArray(text){const raw=String(text||'').replace(/```(?:json)?/gi,'').replace(/```/g,'').trim();try{const x=JSON.parse(raw);return Array.isArray(x)?x:Array.isArray(x?.questions)?x.questions:[]}catch{}const a=raw.indexOf('['),z=raw.lastIndexOf(']');if(a>=0&&z>a)try{return JSON.parse(raw.slice(a,z+1))}catch{}return []}
function normalizeQ(q){if(!q||typeof q!=='object')return null;const text=clean(q.text??q.question,260),answer=clean(q.answer,120),topic=clean(q.topic,120),level=clean(q.level,3).toUpperCase(),explanation=clean(q.explanation,300),options=Array.isArray(q.options)?q.options.map(x=>clean(x,120)).filter(Boolean):[];if(!text||!answer||options.length<3||!options.includes(answer))return null;return {text,answer,options:[...new Set(options)].slice(0,4),topic,level:/^(A1|A2|B1|B2|C1|C2)$/.test(level)?level:'B2',explanation}}
async function grammarTest(req,env){const forwarded=new Request(new URL('/api/me',req.url),{headers:{Cookie:req.headers.get('Cookie')||''}});const me=await workerV4.fetch(forwarded,env);let u=null;try{u=(await me.json()).user}catch{}if(!u)return json({error:'Bitte zuerst anmelden.'},401);if(!env.AI?.run)return json({error:'Workers AI ist für Prüfungsgenerierung nicht verfügbar.'},503);const x=await body(req),areas=Array.isArray(x.areas)?x.areas.map(v=>clean(v,120)).filter(Boolean).slice(0,20):[],levels=Array.isArray(x.levels)?x.levels.map(v=>clean(v,3).toUpperCase()).filter(v=>/^(A1|A2|B1|B2|C1|C2)$/.test(v)):[];if(!areas.length&&!levels.length)return json({error:'Bitte mindestens einen Grammatikbereich auswählen.'},400);const prompt=`Erstelle einen anspruchsvollen Englisch-Grammatik-Kompetenztest für einen deutschsprachigen Lernenden. Orientierung: typische CEFR-Aufgabenformate, aber KEIN offizieller Cambridge/IELTS/TOEFL-Test. Geprüfte CEFR-Stufen: ${levels.join(', ')||'gemischt'}. Geprüfte Grammatikbereiche: ${areas.join('; ')||'alle passenden Bereiche'}. Erzeuge GENAU 50 unterschiedliche Multiple-Choice-Fragen. Keine doppelten Sätze und keine nahezu identischen Varianten. Mischung aus Lückentext, Fehlererkennung, Satzwahl und Register/Meaning-in-context. Antworte ausschließlich als JSON-Array mit Objekten {"text":"...","answer":"...","options":["...","...","...","..."],"topic":"genau geprüfter Grammatikbereich","level":"A1|A2|B1|B2|C1|C2","explanation":"kurze Begründung"}. answer muss exakt in options enthalten sein.`;try{const r=await env.AI.run(TEST_MODEL,{prompt,max_tokens:12000,temperature:.25});const arr=extractJsonArray(r?.response??r?.result?.response??r?.text).map(normalizeQ).filter(Boolean);const seen=new Map();for(const q of arr){const k=q.text.toLowerCase();if(!seen.has(k))seen.set(k,q)}const qs=[...seen.values()].slice(0,50);if(qs.length<50)return json({error:`Die KI hat nur ${qs.length} verwertbare eindeutige Fragen erzeugt. Bitte erneut starten.`,code:'TEST_INCOMPLETE'},502);return json({questions:qs,model:TEST_MODEL,disclaimer:'CEFR-orientierter VocabFast-Kompetenztest, kein offizieller externer Sprachtest.'})}catch(e){console.error(e);return json({error:'Der 50-Fragen-Grammatiktest konnte gerade nicht erzeugt werden.'},503)}}

export default{async fetch(request,env){const path=new URL(request.url).pathname;try{
  if(path==='/api/admin/login'&&request.method==='POST')return adminLogin(request,env);
  if(path==='/api/admin/logout'&&request.method==='POST')return adminLogout(request,env);
  if(path==='/api/admin/me'&&request.method==='GET'){const a=await adminSession(request,env);return json({admin:a})}
  if(path==='/api/admin/users'&&request.method==='GET')return usersList(request,env);
  const m=path.match(/^\/api\/admin\/users\/([^/]+)(?:\/(state|password))?$/);if(m){const id=m[1],sub=m[2];if(request.method==='GET'&&!sub)return userDetail(request,env,id);if(request.method==='PUT'&&!sub)return updateAdminUser(request,env,id);if(request.method==='PUT'&&sub==='state')return updateAdminState(request,env,id);if(request.method==='POST'&&sub==='password')return resetPassword(request,env,id);if(request.method==='DELETE'&&!sub)return deleteAdminUser(request,env,id)}
  if(path==='/api/tests/grammar/generate'&&request.method==='POST')return grammarTest(request,env);
  if(path==='/api/auth/login'&&request.method==='POST'){const blocked=await blockDisabledLogin(request,env);if(blocked)return blocked}
  return workerV4.fetch(request,env);
}catch(e){console.error('v5 error',e?.stack||e);return json({error:e?.message||'Interner Serverfehler.',code:e?.code},e?.status||500)}}};
