import workerV8 from './worker-v8.js';

const USER_COOKIE='vf_session',enc=new TextEncoder();
const ACTIVE=new Set(['active','trialing','past_due']);
function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-VocabFast-API':'vocabfast-v14-stripe',...headers}})}
function cookies(req){const out={};for(const p of (req.headers.get('Cookie')||'').split(';')){const i=p.indexOf('=');if(i>0)out[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())}return out}
async function sha(v){const b=new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(String(v))));return [...b].map(x=>x.toString(16).padStart(2,'0')).join('')}
function bucket(env){if(!env?.PDFS?.get||!env?.PDFS?.put)throw Object.assign(new Error('R2 ist nicht verbunden.'),{status:503});return env.PDFS}
async function getJson(b,k){const o=await b.get(k);if(!o)return null;try{return JSON.parse(await o.text())}catch{return null}}
async function putJson(b,k,v){await b.put(k,JSON.stringify(v),{httpMetadata:{contentType:'application/json; charset=utf-8'}})}
async function currentUser(req,env){const raw=cookies(req)[USER_COOKIE];if(!raw)return null;const dot=raw.indexOf('.');if(dot<1)return null;const id=raw.slice(0,dot),token=raw.slice(dot+1);if(!id||token.length<20)return null;const b=bucket(env),s=await getJson(b,`accounts/sessions/${id}/${await sha(token)}.json`);if(!s||Number(s.expiresAt)<=Date.now())return null;const profile=await getJson(b,`accounts/profiles/${id}.json`);return profile?{profile}:null}
function effectiveTier(p){if(p?.plan!=='pro')return 'core';if(!p.proUntil)return 'elite';const t=Date.parse(p.proUntil);return Number.isFinite(t)&&t>Date.now()?'elite':'core'}
function mode(env){return String(env.STRIPE_MODE||'test').toLowerCase()==='live'?'live':'test'}
function checkoutBase(env){const m=mode(env);return String(m==='live'?(env.ELITE_CHECKOUT_URL_LIVE||env.ELITE_CHECKOUT_URL):(env.ELITE_CHECKOUT_URL_TEST||env.ELITE_CHECKOUT_URL)||'').trim()}
async function checkout(req,env){const u=await currentUser(req,env);if(!u)return json({error:'Bitte zuerst anmelden.'},401);if(effectiveTier(u.profile)==='elite')return json({error:'Dein Konto verwendet bereits VocabFast Elite.'},409);const base=checkoutBase(env);if(!base)return json({error:`VocabFast Elite ist im Stripe-${mode(env)==='live'?'Livebetrieb':'Sandbox-Modus'} noch nicht mit Checkout verbunden.`,code:'BILLING_NOT_CONFIGURED'},503);const q=new URLSearchParams({client_reference_id:u.profile.id,prefilled_email:u.profile.email||''});return json({checkoutUrl:`${base}${base.includes('?')?'&':'?'}${q.toString()}`,priceLabel:String(env.ELITE_PRICE_LABEL||'7,99 € / Monat'),mode:mode(env)})}
async function billingStatus(req,env){const u=await currentUser(req,env);if(!u)return json({error:'Bitte zuerst anmelden.'},401);const p=u.profile;return json({tier:effectiveTier(p),priceLabel:String(env.ELITE_PRICE_LABEL||'7,99 € / Monat'),mode:mode(env),subscriptionStatus:String(p.stripeSubscriptionStatus||''),paymentIssue:!!p.stripePaymentIssue,planSource:String(p.planSource||''),cancelAtPeriodEnd:!!p.stripeCancelAtPeriodEnd,currentPeriodEnd:p.stripeCurrentPeriodEnd||null})}
function safeEqual(a,b){a=String(a||'');b=String(b||'');if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0}
async function hmacHex(secret,payload){const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=new Uint8Array(await crypto.subtle.sign('HMAC',key,enc.encode(payload)));return [...sig].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function verify(req,secret){if(!secret)throw Object.assign(new Error('Stripe-Webhook-Secret fehlt in Cloudflare.'),{status:503,code:'STRIPE_WEBHOOK_SECRET_MISSING'});const raw=await req.text(),h=req.headers.get('Stripe-Signature')||'',parts=h.split(',').map(x=>x.trim()),ts=parts.find(x=>x.startsWith('t='))?.slice(2),v1=parts.filter(x=>x.startsWith('v1=')).map(x=>x.slice(3));if(!ts||!v1.length)throw Object.assign(new Error('Ungültige Stripe-Signatur.'),{status:400});if(Math.abs(Date.now()/1000-Number(ts))>600)throw Object.assign(new Error('Stripe-Signatur ist abgelaufen.'),{status:400});const expected=await hmacHex(secret,`${ts}.${raw}`);if(!v1.some(x=>safeEqual(x,expected)))throw Object.assign(new Error('Stripe-Signatur konnte nicht bestätigt werden.'),{status:400});return JSON.parse(raw)}
function endpointSecret(env,kind){if(kind==='live')return String(env.STRIPE_WEBHOOK_SECRET_LIVE||env.STRIPE_WEBHOOK_SECRET||'');if(kind==='test')return String(env.STRIPE_WEBHOOK_SECRET_TEST||env.STRIPE_WEBHOOK_SECRET||'');return String(env.STRIPE_WEBHOOK_SECRET||'')}
async function setTier(env,userId,{subscriptionId=null,customerId=null,status='active',cancelAtPeriodEnd=false,currentPeriodEnd=null}={}){if(!userId)return;const b=bucket(env),p=await getJson(b,`accounts/profiles/${userId}.json`);if(!p)return;const elite=ACTIVE.has(String(status));p.plan=elite?'pro':'free';p.proUntil=null;p.planSource='stripe';p.stripeSubscriptionStatus=String(status||'');p.stripePaymentIssue=false;p.stripeCancelAtPeriodEnd=!!cancelAtPeriodEnd;p.stripeCurrentPeriodEnd=currentPeriodEnd||null;if(subscriptionId)p.stripeSubscriptionId=subscriptionId;if(customerId)p.stripeCustomerId=customerId;await putJson(b,`accounts/profiles/${userId}.json`,p);if(subscriptionId)await putJson(b,`stripe/subscriptions/${subscriptionId}.json`,{userId,customerId,status,cancelAtPeriodEnd:!!cancelAtPeriodEnd,currentPeriodEnd:currentPeriodEnd||null,updatedAt:Date.now()});if(customerId)await putJson(b,`stripe/customers/${customerId}.json`,{userId,subscriptionId,status,updatedAt:Date.now()})}
async function webhook(req,env,kind='default'){const event=await verify(req,endpointSecret(env,kind)),type=event?.type||'',o=event?.data?.object||{},b=bucket(env);
 if(type==='checkout.session.completed'){const userId=String(o.client_reference_id||'').trim(),sub=typeof o.subscription==='string'?o.subscription:o.subscription?.id,cust=typeof o.customer==='string'?o.customer:o.customer?.id;if(userId&&sub)await setTier(env,userId,{subscriptionId:sub,customerId:cust,status:'active'})}
 else if(type.startsWith('customer.subscription.')){const sub=o.id,cust=typeof o.customer==='string'?o.customer:o.customer?.id,map=sub?await getJson(b,`stripe/subscriptions/${sub}.json`):null,cm=cust?await getJson(b,`stripe/customers/${cust}.json`):null,userId=map?.userId||cm?.userId;if(userId)await setTier(env,userId,{subscriptionId:sub,customerId:cust,status:type==='customer.subscription.deleted'?'canceled':String(o.status||'active'),cancelAtPeriodEnd:!!o.cancel_at_period_end,currentPeriodEnd:o.current_period_end?new Date(Number(o.current_period_end)*1000).toISOString():null})}
 else if(type==='invoice.payment_failed'){const sub=typeof o.subscription==='string'?o.subscription:(o.parent?.subscription_details?.subscription||null),map=sub?await getJson(b,`stripe/subscriptions/${sub}.json`):null;if(map?.userId){const p=await getJson(b,`accounts/profiles/${map.userId}.json`);if(p){p.stripePaymentIssue=true;p.stripeLastPaymentFailure=Date.now();await putJson(b,`accounts/profiles/${map.userId}.json`,p)}}}
 return json({received:true})}
export default {async fetch(req,env){const path=new URL(req.url).pathname;try{
  if(path==='/api/billing/checkout'&&req.method==='POST')return await checkout(req,env);
  if(path==='/api/billing/status'&&req.method==='GET')return await billingStatus(req,env);
  if(path==='/api/stripe/webhook/test'&&req.method==='POST')return await webhook(req,env,'test');
  if(path==='/api/stripe/webhook/live'&&req.method==='POST')return await webhook(req,env,'live');
  if(path==='/api/stripe/webhook'&&req.method==='POST')return await webhook(req,env,'default');
  return workerV8.fetch(req,env);
}catch(e){console.error('v14 stripe error',e);return json({error:e?.message||'Interner Serverfehler.',code:e?.code},e?.status||500)}}};
