import workerV7 from './worker-v7.js';

const USER_COOKIE='vf_session',ADMIN_COOKIE='vf_admin',enc=new TextEncoder();
const ALL_PERMS=['users.read','users.edit','progress.edit','tests.edit','pdfs.manage','plans.manage','security.manage','accounts.manage'];
function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-VocabFast-API':'vocabfast-v8-staff-roles',...headers}})}
function cookies(req){const out={};for(const p of (req.headers.get('Cookie')||'').split(';')){const i=p.indexOf('=');if(i>0)out[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())}return out}
async function sha(v){const b=new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(String(v))));return [...b].map(x=>x.toString(16).padStart(2,'0')).join('')}
function bucket(env){if(!env?.PDFS?.get||!env?.PDFS?.put)throw Object.assign(new Error('R2 ist nicht verbunden.'),{status:503});return env.PDFS}
async function getJson(b,k){const o=await b.get(k);if(!o)return null;try{return JSON.parse(await o.text())}catch{return null}}
async function putJson(b,k,v){await b.put(k,JSON.stringify(v),{httpMetadata:{contentType:'application/json; charset=utf-8'}})}
async function body(req){try{return await req.json()}catch{return {}}}
function cookie(name,value,req,maxAge){const secure=new URL(req.url).protocol==='https:'?'; Secure':'';return `${name}=${encodeURIComponent(value)}; Path=/; HttpOnly; SameSite=Lax${secure}; Max-Age=${maxAge}`}
function rand(n=32){const a=crypto.getRandomValues(new Uint8Array(n));let s='';for(const b of a)s+=String.fromCharCode(b);return btoa(s).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
function effectivePlan(p){if(p?.plan!=='pro')return 'core';if(!p.proUntil)return 'elite';const t=Date.parse(p.proUntil);return Number.isFinite(t)&&t>Date.now()?'elite':'core'}
async function currentUser(req,env){const raw=cookies(req)[USER_COOKIE];if(!raw)return null;const dot=raw.indexOf('.');if(dot<1)return null;const id=raw.slice(0,dot),token=raw.slice(dot+1);if(!id||token.length<20)return null;const b=bucket(env),s=await getJson(b,`accounts/sessions/${id}/${await sha(token)}.json`);if(!s||Number(s.expiresAt)<=Date.now())return null;const profile=await getJson(b,`accounts/profiles/${id}.json`);return profile?{profile}:null}
async function adminContext(req,env){const raw=cookies(req)[ADMIN_COOKIE];if(!raw)return null;const b=bucket(env),s=await getJson(b,`admin/sessions/${await sha(raw)}.json`);if(!s||Number(s.expiresAt)<=Date.now())return null;if(!s.staffUserId)return {superadmin:true,permissions:ALL_PERMS,username:'admin'};const p=await getJson(b,`accounts/profiles/${s.staffUserId}.json`);if(!p||p.disabled)return null;const permissions=Array.isArray(p.staffPermissions)?p.staffPermissions.filter(x=>ALL_PERMS.includes(x)):[];if(!permissions.length)return null;return {superadmin:false,staffUserId:p.id,name:p.name||p.email,email:p.email,permissions}}
function need(ctx,perm){if(!ctx)throw Object.assign(new Error('Admin-Anmeldung erforderlich.'),{status:401});if(ctx.superadmin)return;if(!ctx.permissions.includes(perm))throw Object.assign(new Error('Für diese Verwaltungsaktion fehlt dir die Berechtigung.'),{status:403,code:'STAFF_PERMISSION_REQUIRED'})}
async function activateStaff(req,env){const u=await currentUser(req,env);if(!u)return json({error:'Bitte zuerst anmelden.'},401);const perms=Array.isArray(u.profile.staffPermissions)?u.profile.staffPermissions.filter(x=>ALL_PERMS.includes(x)):[];if(!perms.length)return json({error:'Für dieses Konto sind keine Verwaltungsrechte freigeschaltet.'},403);const token=rand(),now=Date.now(),b=bucket(env);await putJson(b,`admin/sessions/${await sha(token)}.json`,{createdAt:now,expiresAt:now+12*3600000,staffUserId:u.profile.id});return json({ok:true,staff:{name:u.profile.name||u.profile.email,permissions:perms}},200,{'Set-Cookie':cookie(ADMIN_COOKIE,token,req,12*3600)})}
async function augmentMe(req,env){const base=await workerV7.fetch(req,env);let d={};try{d=await base.clone().json()}catch{return base}if(!d.user)return base;const u=await currentUser(req,env);if(u){d.user.tier=effectivePlan(u.profile);d.user.tierName=d.user.tier==='elite'?'VocabFast Elite':'VocabFast Core';d.user.staffPermissions=Array.isArray(u.profile.staffPermissions)?u.profile.staffPermissions.filter(x=>ALL_PERMS.includes(x)):[];d.user.staffRole=d.user.staffPermissions.length?'helper':null}return json(d,base.status)}
async function permissionEndpoint(req,env,id){const ctx=await adminContext(req,env);if(!ctx)throw Object.assign(new Error('Admin-Anmeldung erforderlich.'),{status:401});if(!ctx.superadmin)throw Object.assign(new Error('Nur der Superadmin darf Verwaltungsrechte vergeben.'),{status:403});const b=bucket(env),p=await getJson(b,`accounts/profiles/${id}.json`);if(!p)return json({error:'Konto nicht gefunden.'},404);if(req.method==='GET')return json({permissions:Array.isArray(p.staffPermissions)?p.staffPermissions:[],role:Array.isArray(p.staffPermissions)&&p.staffPermissions.length?'helper':'user'});const x=await body(req),perms=Array.isArray(x.permissions)?[...new Set(x.permissions.filter(v=>ALL_PERMS.includes(v)))]:[];p.staffPermissions=perms;p.staffRole=perms.length?'helper':null;await putJson(b,`accounts/profiles/${id}.json`,p);return json({ok:true,permissions:perms})}
async function progressEndpoint(req,env,id){const ctx=await adminContext(req,env);need(ctx,req.method==='GET'?'users.read':'progress.edit');const b=bucket(env),p=await getJson(b,`accounts/profiles/${id}.json`);if(!p)return json({error:'Konto nicht gefunden.'},404);const s=await getJson(b,`accounts/state/${id}.json`)||{};if(req.method==='GET')return json({stats:s.stats||{},learningCount:Array.isArray(s.learning)?s.learning.length:0,grammarScores:s.grammarTopicScores||{},testCount:Array.isArray(s.testHistory)?s.testHistory.length:0});const x=await body(req);s.stats={...(s.stats||{})};for(const k of ['xp','vocabAnswered','vocabCorrect','grammarAnswered','grammarCorrect','pdfUploads'])if(k in x)s.stats[k]=Math.max(0,Number(x[k])||0);if(Array.isArray(x.studyDates))s.stats.studyDates=[...new Set(x.studyDates.map(String))].slice(0,5000);await putJson(b,`accounts/state/${id}.json`,s);return json({ok:true,stats:s.stats})}
async function testsEndpoint(req,env,id){const ctx=await adminContext(req,env);need(ctx,req.method==='GET'?'users.read':'tests.edit');const b=bucket(env),p=await getJson(b,`accounts/profiles/${id}.json`);if(!p)return json({error:'Konto nicht gefunden.'},404);const s=await getJson(b,`accounts/state/${id}.json`)||{};if(req.method==='GET')return json({tests:Array.isArray(s.testHistory)?s.testHistory:[],grammarScores:s.grammarTopicScores||{}});const x=await body(req);if(x.action==='clearTests')s.testHistory=[];else if(x.action==='clearGrammar')s.grammarTopicScores={};else{if(Array.isArray(x.tests))s.testHistory=x.tests.slice(0,500);if(x.grammarScores&&typeof x.grammarScores==='object')s.grammarTopicScores=x.grammarScores}await putJson(b,`accounts/state/${id}.json`,s);return json({ok:true})}
async function enforceAdmin(req,env,path){const ctx=await adminContext(req,env);if(!ctx)throw Object.assign(new Error('Admin-Anmeldung erforderlich.'),{status:401});if(ctx.superadmin)return ctx;const method=req.method;let perm='users.read';if(/^\/api\/admin\/users\/[^/]+\/state$/.test(path))throw Object.assign(new Error('Der vollständige Roh-Lernstand ist nur für den Superadmin verfügbar.'),{status:403});if(/\/pdfs(?:\/|$)/.test(path))perm=method==='GET'?'users.read':'pdfs.manage';else if(/\/password$|\/sessions$/.test(path))perm='security.manage';else if(method==='DELETE'&&/^\/api\/admin\/users\/[^/]+$/.test(path))perm='accounts.manage';else if(method==='PUT'&&/^\/api\/admin\/users\/[^/]+$/.test(path)){const x=await body(req.clone());perm=('plan'in x||'proUntil'in x)?'plans.manage':'users.edit'}else if(method!=='GET')perm='users.edit';need(ctx,perm);return ctx}
async function billingCheckout(req,env){const u=await currentUser(req,env);if(!u)return json({error:'Bitte zuerst anmelden.'},401);if(effectivePlan(u.profile)==='elite')return json({error:'Dein Konto verwendet bereits VocabFast Elite.'},409);const url=String(env.ELITE_CHECKOUT_URL||'').trim();if(!url)return json({error:'Das monatliche VocabFast-Elite-Abo ist noch nicht mit einem Live-Stripe-Checkout verbunden.',code:'BILLING_NOT_CONFIGURED'},503);const sep=url.includes('?')?'&':'?';return json({checkoutUrl:`${url}${sep}prefilled_email=${encodeURIComponent(u.profile.email||'')}`})}

export default {async fetch(req,env){const path=new URL(req.url).pathname;try{
  if(path==='/api/me'&&req.method==='GET')return await augmentMe(req,env);
  if(path==='/api/staff/activate'&&req.method==='POST')return await activateStaff(req,env);
  if(path==='/api/admin/context'&&req.method==='GET'){const c=await adminContext(req,env);return c?json(c):json({error:'Admin-Anmeldung erforderlich.'},401)}
  if(path==='/api/billing/checkout'&&req.method==='POST')return await billingCheckout(req,env);
  let m=path.match(/^\/api\/admin\/users\/([^/]+)\/permissions$/);if(m)return await permissionEndpoint(req,env,decodeURIComponent(m[1]));
  m=path.match(/^\/api\/admin\/users\/([^/]+)\/progress$/);if(m)return await progressEndpoint(req,env,decodeURIComponent(m[1]));
  m=path.match(/^\/api\/admin\/users\/([^/]+)\/tests$/);if(m)return await testsEndpoint(req,env,decodeURIComponent(m[1]));
  if(path.startsWith('/api/admin/'))await enforceAdmin(req,env,path);
  return workerV7.fetch(req,env);
}catch(e){console.error('v8 staff/admin error',e);return json({error:e?.message||'Interner Serverfehler.',code:e?.code},e?.status||500)}}};
