import workerV9 from './worker-v9.js';

const USER_COOKIE='vf_session',enc=new TextEncoder();
const ACTIVE=new Set(['active','trialing','past_due']);
function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-VocabFast-API':'vocabfast-v15-billing',...headers}})}
function cookies(req){const out={};for(const p of (req.headers.get('Cookie')||'').split(';')){const i=p.indexOf('=');if(i>0)out[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())}return out}
async function sha(v){const b=new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(String(v))));return [...b].map(x=>x.toString(16).padStart(2,'0')).join('')}
function bucket(env){if(!env?.PDFS?.get||!env?.PDFS?.put)throw Object.assign(new Error('R2 ist nicht verbunden.'),{status:503});return env.PDFS}
async function getJson(b,k){const o=await b.get(k);if(!o)return null;try{return JSON.parse(await o.text())}catch{return null}}
async function putJson(b,k,v){await b.put(k,JSON.stringify(v),{httpMetadata:{contentType:'application/json; charset=utf-8'}})}
async function currentUser(req,env){const raw=cookies(req)[USER_COOKIE];if(!raw)return null;const dot=raw.indexOf('.');if(dot<1)return null;const id=raw.slice(0,dot),token=raw.slice(dot+1);if(!id||token.length<20)return null;const b=bucket(env),s=await getJson(b,`accounts/sessions/${id}/${await sha(token)}.json`);if(!s||Number(s.expiresAt)<=Date.now())return null;const profile=await getJson(b,`accounts/profiles/${id}.json`);return profile?{profile}:null}
function effectiveTier(p){if(p?.plan!=='pro')return 'core';if(!p.proUntil)return 'elite';const t=Date.parse(p.proUntil);return Number.isFinite(t)&&t>Date.now()?'elite':'core'}
function mode(env){return String(env.STRIPE_MODE||'test').toLowerCase()==='live'?'live':'test'}
function stripeSecret(env,m=mode(env)){return String(m==='live'?(env.STRIPE_SECRET_KEY_LIVE||env.STRIPE_SECRET_KEY):(env.STRIPE_SECRET_KEY_TEST||env.STRIPE_SECRET_KEY)||'').trim()}
function webhookSecret(env,m){return String(m==='live'?(env.STRIPE_WEBHOOK_SECRET_LIVE||env.STRIPE_WEBHOOK_SECRET):(env.STRIPE_WEBHOOK_SECRET_TEST||env.STRIPE_WEBHOOK_SECRET)||'').trim()}
function priceId(env,m=mode(env)){return String(m==='live'?(env.ELITE_PRICE_ID_LIVE||env.ELITE_PRICE_ID):(env.ELITE_PRICE_ID_TEST||env.ELITE_PRICE_ID)||'').trim()}
function paymentLink(env,m=mode(env)){return String(m==='live'?(env.ELITE_CHECKOUT_URL_LIVE||env.ELITE_CHECKOUT_URL):(env.ELITE_CHECKOUT_URL_TEST||env.ELITE_CHECKOUT_URL)||'').trim()}
function portalFallback(env,m=mode(env)){return String(m==='live'?(env.STRIPE_PORTAL_URL_LIVE||env.STRIPE_PORTAL_URL):(env.STRIPE_PORTAL_URL_TEST||env.STRIPE_PORTAL_URL)||'').trim()}
function origin(req,env){const configured=String(env.APP_ORIGIN||'').trim();if(configured){try{return new URL(configured).origin}catch{}}return new URL(req.url).origin}
async function stripePost(env,m,path,params){const key=stripeSecret(env,m);if(!key)throw Object.assign(new Error(`Stripe API-Key für ${m==='live'?'Live':'Sandbox'} fehlt in Cloudflare.`),{status:503,code:'STRIPE_SECRET_MISSING'});const form=new URLSearchParams();for(const [k,v] of Object.entries(params||{})){if(v===undefined||v===null||v==='')continue;form.set(k,String(v))}const f=env?.STRIPE_FETCH||fetch,r=await f(`https://api.stripe.com${path}`,{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/x-www-form-urlencoded'},body:form.toString()});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Object.assign(new Error(d?.error?.message||`Stripe Fehler ${r.status}`),{status:502,code:'STRIPE_API_ERROR'});return d}
async function checkout(req,env){const u=await currentUser(req,env);if(!u)return json({error:'Bitte zuerst anmelden.'},401);if(effectiveTier(u.profile)==='elite')return json({error:'Dein Konto verwendet bereits VocabFast Elite.'},409);const m=mode(env);if(m==='live'&&!webhookSecret(env,'live'))return json({error:'VocabFast Elite Live-Checkout ist vorbereitet, aber die sichere Stripe-Webhook-Verknüpfung in Cloudflare fehlt noch.',code:'LIVE_BILLING_NOT_READY'},503);const price=priceId(env,m),key=stripeSecret(env,m),base=origin(req,env),success=`${base}/?upgrade=success&session_id={CHECKOUT_SESSION_ID}`,cancel=`${base}/?upgrade=cancelled`;
 if(key&&price){const params={'mode':'subscription','success_url':success,'cancel_url':cancel,'client_reference_id':u.profile.id,'allow_promotion_codes':'true','billing_address_collection':'auto','line_items[0][price]':price,'line_items[0][quantity]':'1','metadata[vocabfast_user_id]':u.profile.id,'metadata[vocabfast_plan]':'elite','subscription_data[metadata][vocabfast_user_id]':u.profile.id,'subscription_data[metadata][vocabfast_plan]':'elite'};if(u.profile.stripeCustomerId)params.customer=u.profile.stripeCustomerId;else if(u.profile.email)params.customer_email=u.profile.email;const s=await stripePost(env,m,'/v1/checkout/sessions',params);if(!s?.url)throw Object.assign(new Error('Stripe hat keine Checkout-URL zurückgegeben.'),{status:502});return json({checkoutUrl:s.url,sessionId:s.id||null,priceLabel:String(env.ELITE_PRICE_LABEL||'7,99 € / Monat'),mode:m,provider:'checkout_session'})}
 const link=paymentLink(env,m);if(!link)return json({error:`VocabFast Elite ist im Stripe-${m==='live'?'Livebetrieb':'Sandbox-Modus'} noch nicht vollständig konfiguriert.`,code:'BILLING_NOT_CONFIGURED'},503);const q=new URLSearchParams({client_reference_id:u.profile.id,prefilled_email:u.profile.email||''});return json({checkoutUrl:`${link}${link.includes('?')?'&':'?'}${q.toString()}`,priceLabel:String(env.ELITE_PRICE_LABEL||'7,99 € / Monat'),mode:m,provider:'payment_link'})}
async function portal(req,env){const u=await currentUser(req,env);if(!u)return json({error:'Bitte zuerst anmelden.'},401);const m=mode(env),fallback=portalFallback(env,m);if(stripeSecret(env,m)&&u.profile.stripeCustomerId){const p=await stripePost(env,m,'/v1/billing_portal/sessions',{customer:u.profile.stripeCustomerId,return_url:`${origin(req,env)}/?billing=return`});if(p?.url)return json({portalUrl:p.url,mode:m,provider:'portal_session'})}if(fallback)return json({portalUrl:fallback,mode:m,provider:'portal_login'});throw Object.assign(new Error('Stripe Customer Portal ist noch nicht eingerichtet.'),{status:503,code:'PORTAL_NOT_CONFIGURED'})}
async function billingStatus(req,env){const u=await currentUser(req,env);if(!u)return json({error:'Bitte zuerst anmelden.'},401);const p=u.profile,m=mode(env);return json({tier:effectiveTier(p),priceLabel:String(env.ELITE_PRICE_LABEL||'7,99 € / Monat'),mode:m,provider:stripeSecret(env,m)&&priceId(env,m)?'checkout_session':paymentLink(env,m)?'payment_link':'unconfigured',subscriptionStatus:String(p.stripeSubscriptionStatus||''),paymentIssue:!!p.stripePaymentIssue,planSource:String(p.planSource||''),cancelAtPeriodEnd:!!p.stripeCancelAtPeriodEnd,currentPeriodEnd:p.stripeCurrentPeriodEnd||null,customerIdPresent:!!p.stripeCustomerId,managementAvailable:!!(portalFallback(env,m)||(stripeSecret(env,m)&&p.stripeCustomerId)),liveReady:m!=='live'||!!webhookSecret(env,'live')})}
function safeEqual(a,b){a=String(a||'');b=String(b||'');if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0}
async function hmacHex(secret,payload){const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=new Uint8Array(await crypto.subtle.sign('HMAC',key,enc.encode(payload)));return [...sig].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function verify(req,secret){if(!secret)throw Object.assign(new Error('Stripe-Webhook-Secret fehlt in Cloudflare.'),{status:503,code:'STRIPE_WEBHOOK_SECRET_MISSING'});const raw=await req.text(),h=req.headers.get('Stripe-Signature')||'',parts=h.split(',').map(x=>x.trim()),ts=parts.find(x=>x.startsWith('t='))?.slice(2),v1=parts.filter(x=>x.startsWith('v1=')).map(x=>x.slice(3));if(!ts||!v1.length)throw Object.assign(new Error('Ungültige Stripe-Signatur.'),{status:400});if(Math.abs(Date.now()/1000-Number(ts))>600)throw Object.assign(new Error('Stripe-Signatur ist abgelaufen.'),{status:400});const expected=await hmacHex(secret,`${ts}.${raw}`);if(!v1.some(x=>safeEqual(x,expected)))throw Object.assign(new Error('Stripe-Signatur konnte nicht bestätigt werden.'),{status:400});return JSON.parse(raw)}
function idOf(v){return typeof v==='string'?v:v?.id||null}
async function resolveUserId(b,o){const meta=String(o?.metadata?.vocabfast_user_id||'').trim();if(meta)return meta;const sub=idOf(o?.subscription)||idOf(o?.parent?.subscription_details?.subscription)||(o?.id?.startsWith?.('sub_')?o.id:null);if(sub){const map=await getJson(b,`stripe/subscriptions/${sub}.json`);if(map?.userId)return map.userId}const cust=idOf(o?.customer);if(cust){const map=await getJson(b,`stripe/customers/${cust}.json`);if(map?.userId)return map.userId}return null}
async function setTier(env,userId,{subscriptionId=null,customerId=null,status='active',cancelAtPeriodEnd=false,currentPeriodEnd=null,checkoutSessionId=null,eventId=null}={}){if(!userId)return false;const b=bucket(env),p=await getJson(b,`accounts/profiles/${userId}.json`);if(!p)return false;const s=String(status||''),isActive=ACTIVE.has(s),sameSub=!subscriptionId||!p.stripeSubscriptionId||p.stripeSubscriptionId===subscriptionId;if(isActive){p.plan='pro';p.proUntil=null;p.planSource='stripe'}else if(p.planSource==='stripe'&&sameSub){p.plan='free';p.proUntil=null}p.stripeSubscriptionStatus=s;p.stripePaymentIssue=s==='past_due'||s==='unpaid';p.stripeCancelAtPeriodEnd=!!cancelAtPeriodEnd;p.stripeCurrentPeriodEnd=currentPeriodEnd||null;if(subscriptionId)p.stripeSubscriptionId=subscriptionId;if(customerId)p.stripeCustomerId=customerId;if(checkoutSessionId)p.stripeCheckoutSessionId=checkoutSessionId;if(eventId)p.stripeLastEventId=eventId;p.stripeUpdatedAt=Date.now();await putJson(b,`accounts/profiles/${userId}.json`,p);if(subscriptionId)await putJson(b,`stripe/subscriptions/${subscriptionId}.json`,{userId,customerId,status:s,cancelAtPeriodEnd:!!cancelAtPeriodEnd,currentPeriodEnd:currentPeriodEnd||null,updatedAt:Date.now()});if(customerId)await putJson(b,`stripe/customers/${customerId}.json`,{userId,subscriptionId,status:s,updatedAt:Date.now()});return true}
async function markPaymentIssue(env,userId,issue,eventId=null){if(!userId)return;const b=bucket(env),p=await getJson(b,`accounts/profiles/${userId}.json`);if(!p)return;p.stripePaymentIssue=!!issue;if(issue)p.stripeLastPaymentFailure=Date.now();else p.stripeLastPaymentSuccess=Date.now();if(eventId)p.stripeLastEventId=eventId;await putJson(b,`accounts/profiles/${userId}.json`,p)}
async function webhook(req,env,m){const event=await verify(req,webhookSecret(env,m));if(m==='live'&&event?.livemode===false)throw Object.assign(new Error('Sandbox-Ereignis am Live-Webhook abgelehnt.'),{status:400});if(m==='test'&&event?.livemode===true)throw Object.assign(new Error('Live-Ereignis am Sandbox-Webhook abgelehnt.'),{status:400});const b=bucket(env),eventId=String(event?.id||'').trim();if(eventId){const seen=await getJson(b,`stripe/events/${m}/${eventId}.json`);if(seen)return json({received:true,duplicate:true})}const type=String(event?.type||''),o=event?.data?.object||{};
 if(type==='checkout.session.completed'){const userId=String(o.client_reference_id||o.metadata?.vocabfast_user_id||'').trim(),sub=idOf(o.subscription),cust=idOf(o.customer);if(userId&&sub)await setTier(env,userId,{subscriptionId:sub,customerId:cust,status:'active',checkoutSessionId:o.id||null,eventId})}
 else if(type.startsWith('customer.subscription.')){const sub=o.id,cust=idOf(o.customer),userId=await resolveUserId(b,o),status=type==='customer.subscription.deleted'?'canceled':String(o.status||'active'),period=o.current_period_end?new Date(Number(o.current_period_end)*1000).toISOString():null;if(userId)await setTier(env,userId,{subscriptionId:sub,customerId:cust,status,cancelAtPeriodEnd:!!o.cancel_at_period_end,currentPeriodEnd:period,eventId})}
 else if(type==='invoice.payment_failed'||type==='invoice.payment_action_required'){const userId=await resolveUserId(b,o);if(userId)await markPaymentIssue(env,userId,true,eventId)}
 else if(type==='invoice.paid'||type==='invoice.payment_succeeded'){const userId=await resolveUserId(b,o);if(userId)await markPaymentIssue(env,userId,false,eventId)}
 if(eventId)await putJson(b,`stripe/events/${m}/${eventId}.json`,{type,processedAt:Date.now()});return json({received:true})}
async function adminPlanSource(req,env,path){const clone=req.clone(),payload=await clone.json().catch(()=>({})),res=await workerV9.fetch(req,env);if(!res.ok||!('plan' in payload))return res;const id=decodeURIComponent(path.match(/^\/api\/admin\/users\/([^/]+)$/)?.[1]||'');if(!id)return res;const b=bucket(env),p=await getJson(b,`accounts/profiles/${id}.json`);if(p){p.planSource='admin';p.adminPlanUpdatedAt=Date.now();await putJson(b,`accounts/profiles/${id}.json`,p)}return res}
export default {async fetch(req,env){const path=new URL(req.url).pathname;try{
 if(path==='/api/billing/checkout'&&req.method==='POST')return await checkout(req,env);
 if(path==='/api/billing/portal'&&req.method==='POST')return await portal(req,env);
 if(path==='/api/billing/status'&&req.method==='GET')return await billingStatus(req,env);
 if(path==='/api/stripe/webhook/test'&&req.method==='POST')return await webhook(req,env,'test');
 if(path==='/api/stripe/webhook/live'&&req.method==='POST')return await webhook(req,env,'live');
 if(/^\/api\/admin\/users\/[^/]+$/.test(path)&&req.method==='PUT')return await adminPlanSource(req,env,path);
 return workerV9.fetch(req,env);
}catch(e){console.error('v15 billing error',e);return json({error:e?.message||'Interner Serverfehler.',code:e?.code},e?.status||500)}}};
