import {rm,mkdir,copyFile,readFile,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
const root=resolve(import.meta.dirname,'..'),dist=resolve(root,'dist');
const files=['index.html','styles.css','app.js','vocab-data.js','grammar-data.js','level-index.js','ui-overrides.js','v4-features.js','v4-features.css','practice-grammar-v6.js','grammar-topic-scores-v7.js','exam-admin-v8.js','exam-admin-v8.css','v9-polish.js','v9-polish.css','v9-observer-guard.js','v9-observer-restore.js'];
await rm(dist,{recursive:true,force:true});await mkdir(dist,{recursive:true});
for(const f of files)await copyFile(resolve(root,f),resolve(dist,f));
const indexPath=resolve(dist,'index.html');
let html=await readFile(indexPath,'utf8');
if(!html.includes('level-index.js'))html=html.replace('<script src="app.js"></script>','<script src="level-index.js"></script>\n<script src="app.js"></script>');
if(!html.includes('ui-overrides.js'))html=html.replace('</body>','  <script src="ui-overrides.js"></script>\n</body>');
if(!html.includes('v4-features.css'))html=html.replace('</head>','  <link rel="stylesheet" href="v4-features.css">\n</head>');
if(!html.includes('v4-features.js'))html=html.replace('</body>','  <script src="v4-features.js"></script>\n</body>');
if(!html.includes('practice-grammar-v6.js'))html=html.replace('</body>','  <script src="practice-grammar-v6.js"></script>\n</body>');
if(!html.includes('grammar-topic-scores-v7.js'))html=html.replace('</body>','  <script src="grammar-topic-scores-v7.js"></script>\n</body>');
if(!html.includes('exam-admin-v8.css'))html=html.replace('</head>','  <link rel="stylesheet" href="exam-admin-v8.css">\n</head>');
if(!html.includes('exam-admin-v8.js'))html=html.replace('</body>','  <script src="exam-admin-v8.js"></script>\n</body>');
if(!html.includes('v9-polish.css'))html=html.replace('</head>','  <link rel="stylesheet" href="v9-polish.css">\n</head>');
if(!html.includes('v9-polish.js'))html=html.replace('</body>','  <script src="v9-polish.js"></script>\n</body>');
if(!html.includes('v9-observer-guard.js'))html=html.replace('<script src="v9-polish.js"></script>','<script src="v9-observer-guard.js"></script>\n  <script src="v9-polish.js"></script>\n  <script src="v9-observer-restore.js"></script>');
await writeFile(indexPath,html);
console.log(`VocabFast build complete: ${files.length} public files -> dist/`);
