import type { Lesson } from './types';
import type { CefrLevel } from './curriculum';

export type GrammarTopic = {
  id:string;
  level:CefrLevel;
  title:string;
  subtitle:string;
  rule:string;
  examples:{ english:string; german:string }[];
  mistake:string;
  correct:string;
  promptGerman:string;
  targetEnglish:string;
  gapSentence:string;
  gapChoices:string[];
  gapAnswer:string;
};

export const grammarTopics: GrammarTopic[] = [
  {id:'a1-be',level:'A1',title:'To be',subtitle:'am · is · are',rule:'Mit „to be“ beschreibst du Identität, Zustand und Herkunft. Nach I steht am, nach he/she/it is und nach you/we/they are.',examples:[{english:'I am from Austria.',german:'Ich komme aus Österreich.'},{english:'They are ready.',german:'Sie sind bereit.'}],mistake:'I is tired.',correct:'I am tired.',promptGerman:'Wir sind heute müde.',targetEnglish:'We are tired today.',gapSentence:'She ___ from London.',gapChoices:['is','are','am','be'],gapAnswer:'is'},
  {id:'a1-present-simple',level:'A1',title:'Present Simple',subtitle:'Gewohnheiten & Fakten',rule:'Das Present Simple beschreibt Routinen, Gewohnheiten und allgemeine Fakten. Bei he/she/it erhält das Verb meist -s.',examples:[{english:'I work in IT.',german:'Ich arbeite in der IT.'},{english:'She works on Mondays.',german:'Sie arbeitet montags.'}],mistake:'He work every day.',correct:'He works every day.',promptGerman:'Er spricht jeden Tag Englisch.',targetEnglish:'He speaks English every day.',gapSentence:'My brother ___ in Vienna.',gapChoices:['lives','live','living','is live'],gapAnswer:'lives'},
  {id:'a1-articles',level:'A1',title:'Artikel',subtitle:'a · an · the',rule:'A/an steht bei einer nicht näher bestimmten einzelnen Sache. „An“ steht vor einem Vokallaut. „The“ verweist auf etwas Bestimmtes oder bereits Bekanntes.',examples:[{english:'I need a ticket.',german:'Ich brauche ein Ticket.'},{english:'The ticket is on the table.',german:'Das Ticket liegt auf dem Tisch.'}],mistake:'I have a apple.',correct:'I have an apple.',promptGerman:'Ich möchte einen Kaffee.',targetEnglish:'I would like a coffee.',gapSentence:'She has ___ umbrella.',gapChoices:['an','a','the a','one an'],gapAnswer:'an'},

  {id:'a2-past-simple',level:'A2',title:'Past Simple',subtitle:'Abgeschlossene Vergangenheit',rule:'Das Past Simple beschreibt abgeschlossene Handlungen zu einem vergangenen Zeitpunkt. Regelmäßige Verben enden auf -ed, unregelmäßige Formen müssen gelernt werden.',examples:[{english:'We visited London last year.',german:'Wir besuchten letztes Jahr London.'},{english:'I went home early.',german:'Ich ging früh nach Hause.'}],mistake:'I have visited him yesterday.',correct:'I visited him yesterday.',promptGerman:'Wir haben gestern einen Film gesehen.',targetEnglish:'We watched a film yesterday.',gapSentence:'I ___ the email yesterday.',gapChoices:['sent','send','have sent','sending'],gapAnswer:'sent'},
  {id:'a2-present-perfect',level:'A2',title:'Present Perfect',subtitle:'Erfahrung & Ergebnis bis heute',rule:'Have/has + past participle verbindet Vergangenheit und Gegenwart. Typisch sind Erfahrungen ohne konkreten Zeitpunkt oder Ergebnisse, die jetzt relevant sind.',examples:[{english:'I have been to London twice.',german:'Ich war zweimal in London.'},{english:'She has already finished.',german:'Sie ist bereits fertig.'}],mistake:'I have seen him yesterday.',correct:'I saw him yesterday.',promptGerman:'Ich habe diese Stadt noch nie besucht.',targetEnglish:'I have never visited this city.',gapSentence:'Have you ever ___ sushi?',gapChoices:['tried','try','trying','tries'],gapAnswer:'tried'},
  {id:'a2-first-conditional',level:'A2',title:'First Conditional',subtitle:'Reale Bedingungen',rule:'If + Present Simple, will + Grundform beschreibt eine reale oder wahrscheinliche Bedingung in der Zukunft.',examples:[{english:'If it rains, we will stay inside.',german:'Wenn es regnet, bleiben wir drinnen.'},{english:'If you call me, I will help.',german:'Wenn du mich anrufst, helfe ich.'}],mistake:'If it will rain, we stay home.',correct:'If it rains, we will stay home.',promptGerman:'Wenn der Zug zu spät ist, nehme ich den Bus.',targetEnglish:'If the train is late, I will take the bus.',gapSentence:'If she calls, I ___ answer.',gapChoices:['will','would','have','am'],gapAnswer:'will'},

  {id:'b1-second-conditional',level:'B1',title:'Second Conditional',subtitle:'Hypothesen & Ratschläge',rule:'If + Past Simple, would + Grundform beschreibt hypothetische oder unwahrscheinliche Situationen in Gegenwart oder Zukunft.',examples:[{english:'If I were you, I would wait.',german:'Wenn ich du wäre, würde ich warten.'},{english:'If we had more time, we would travel more.',german:'Wenn wir mehr Zeit hätten, würden wir mehr reisen.'}],mistake:'If I would be you, I would wait.',correct:'If I were you, I would wait.',promptGerman:'Wenn ich mehr Zeit hätte, würde ich mehr lesen.',targetEnglish:'If I had more time, I would read more.',gapSentence:'If I ___ you, I would ask first.',gapChoices:['were','would be','am','have been'],gapAnswer:'were'},
  {id:'b1-reported-speech',level:'B1',title:'Reported Speech',subtitle:'Aussagen wiedergeben',rule:'Bei indirekter Rede verschieben sich Zeitformen häufig zurück, wenn das Einleitungsverb in der Vergangenheit steht. Pronomen und Zeitangaben werden an den Kontext angepasst.',examples:[{english:'She said that she was tired.',german:'Sie sagte, dass sie müde sei.'},{english:'He told me that he needed help.',german:'Er sagte mir, dass er Hilfe brauche.'}],mistake:'She said me she is tired.',correct:'She told me that she was tired.',promptGerman:'Er sagte, dass das Treffen verschoben worden sei.',targetEnglish:'He said that the meeting had been postponed.',gapSentence:'She said she ___ more time.',gapChoices:['needed','needs yesterday','need to','needing'],gapAnswer:'needed'},
  {id:'b1-relative-clauses',level:'B1',title:'Relative Clauses',subtitle:'who · which · that',rule:'Relativsätze verbinden Informationen über Personen oder Dinge. Who bezieht sich auf Personen, which auf Dinge, that kann in vielen defining clauses beide ersetzen.',examples:[{english:'The woman who called is my manager.',german:'Die Frau, die angerufen hat, ist meine Chefin.'},{english:'The file that you sent is correct.',german:'Die Datei, die du geschickt hast, ist richtig.'}],mistake:'The person which called me...',correct:'The person who called me...',promptGerman:'Das Buch, das du empfohlen hast, ist interessant.',targetEnglish:'The book that you recommended is interesting.',gapSentence:'The colleague ___ helped me is from Spain.',gapChoices:['who','which','where','whose is'],gapAnswer:'who'},

  {id:'b2-third-conditional',level:'B2',title:'Third Conditional',subtitle:'Irreale Vergangenheit',rule:'If + Past Perfect, would have + past participle bewertet eine vergangene Situation, die nicht eingetreten ist.',examples:[{english:'If we had known, we would have acted differently.',german:'Wenn wir es gewusst hätten, hätten wir anders gehandelt.'},{english:'She would have arrived earlier if she had left on time.',german:'Sie wäre früher angekommen, wenn sie rechtzeitig losgefahren wäre.'}],mistake:'If I would have known, I had called.',correct:'If I had known, I would have called.',promptGerman:'Hätten wir früher begonnen, hätten wir die Frist eingehalten.',targetEnglish:'If we had started earlier, we would have met the deadline.',gapSentence:'If they had warned us, we would have ___ earlier.',gapChoices:['left','leave','leaving','leaves'],gapAnswer:'left'},
  {id:'b2-passive',level:'B2',title:'Passive Voice',subtitle:'Prozess & Ergebnis hervorheben',rule:'Be + past participle lenkt den Fokus auf Handlung oder Ergebnis statt auf den Handelnden. Die Zeitform steckt im Verb „be“.',examples:[{english:'The report was completed yesterday.',german:'Der Bericht wurde gestern fertiggestellt.'},{english:'The issue has been resolved.',german:'Das Problem wurde gelöst.'}],mistake:'The report completed yesterday.',correct:'The report was completed yesterday.',promptGerman:'Die Entscheidung wurde bereits bestätigt.',targetEnglish:'The decision has already been confirmed.',gapSentence:'The documents were ___ on Friday.',gapChoices:['sent','send','sending','sends'],gapAnswer:'sent'},
  {id:'b2-modal-deduction',level:'B2',title:'Modal Deduction',subtitle:'must · might · can’t',rule:'Must drückt eine starke logische Schlussfolgerung aus, might/may eine Möglichkeit und can’t eine starke negative Schlussfolgerung.',examples:[{english:'She must be busy.',german:'Sie muss wohl beschäftigt sein.'},{english:'They might have missed the train.',german:'Sie könnten den Zug verpasst haben.'}],mistake:'He must to be at work.',correct:'He must be at work.',promptGerman:'Sie könnten die Nachricht übersehen haben.',targetEnglish:'They might have missed the message.',gapSentence:'He ___ have forgotten the appointment.',gapChoices:['might','might to','must to','can to'],gapAnswer:'might'},

  {id:'c1-inversion',level:'C1',title:'Inversion',subtitle:'Formell betonen',rule:'Nach bestimmten negativen oder einschränkenden Ausdrücken steht in formellem Englisch Hilfsverb vor Subjekt: Never have I…, Only then did…, Should you…',examples:[{english:'Only then did we understand the risk.',german:'Erst dann verstanden wir das Risiko.'},{english:'Should you need help, please contact us.',german:'Sollten Sie Hilfe benötigen, kontaktieren Sie uns.'}],mistake:'Only then we understood the risk.',correct:'Only then did we understand the risk.',promptGerman:'Erst später wurde das ganze Ausmaß deutlich.',targetEnglish:'Only later did the full extent become clear.',gapSentence:'Rarely ___ we seen such rapid change.',gapChoices:['have','we have','did have','are'],gapAnswer:'have'},
  {id:'c1-cleft',level:'C1',title:'Cleft Sentences',subtitle:'Gezielte Betonung',rule:'What-clefts und it-clefts heben gezielt einen Satzteil hervor: What matters is…, It was X that…',examples:[{english:'What matters is the long-term effect.',german:'Entscheidend ist die langfristige Wirkung.'},{english:'It was the timing that caused the problem.',german:'Es war der Zeitpunkt, der das Problem verursachte.'}],mistake:'What it matters is the result.',correct:'What matters is the result.',promptGerman:'Entscheidend ist, wie wir darauf reagieren.',targetEnglish:'What matters is how we respond to it.',gapSentence:'What ___ most is the long-term value.',gapChoices:['matters','matter','is matter','mattering'],gapAnswer:'matters'},
  {id:'c1-advanced-conditionals',level:'C1',title:'Advanced Conditionals',subtitle:'Inversion & mixed forms',rule:'Fortgeschrittene Bedingungssätze können „if“ durch Inversion ersetzen oder Zeitbezüge mischen, wenn Ursache und Folge in unterschiedlichen Zeiten liegen.',examples:[{english:'Had we known earlier, we would have changed course.',german:'Hätten wir es früher gewusst, hätten wir den Kurs geändert.'},{english:'Were the market to change, we would reconsider.',german:'Sollte sich der Markt ändern, würden wir neu überlegen.'}],mistake:'Had we knew earlier...',correct:'Had we known earlier...',promptGerman:'Wären die Bedingungen anders, wäre die Entscheidung einfacher.',targetEnglish:'Were the conditions different, the decision would be easier.',gapSentence:'Had we ___ the warning, we would have acted sooner.',gapChoices:['received','receive','receiving','receives'],gapAnswer:'received'},

  {id:'c2-hedging',level:'C2',title:'Hedging & Precision',subtitle:'Aussagen exakt absichern',rule:'C2-Ausdruck vermeidet unnötige Absolutheit. Formulierungen wie appears to, may well, arguably, to some extent oder does not necessarily helfen, Evidenz und Sicherheit exakt zu kalibrieren.',examples:[{english:'The findings appear to support this interpretation.',german:'Die Ergebnisse scheinen diese Interpretation zu stützen.'},{english:'This does not necessarily imply causation.',german:'Das impliziert nicht notwendigerweise Kausalität.'}],mistake:'The data proves definitely that...',correct:'The data strongly suggests that...',promptGerman:'Die Daten deuten darauf hin, beweisen die Annahme jedoch nicht eindeutig.',targetEnglish:'The data points to this interpretation, but does not conclusively establish it.',gapSentence:'The evidence does not ___ establish causality.',gapChoices:['conclusively','conclusion','conclusive to','conclude that to'],gapAnswer:'conclusively'},
  {id:'c2-nominalisation',level:'C2',title:'Nominalisation',subtitle:'Komplexität elegant verdichten',rule:'Nominalisierungen können in akademischen und professionellen Texten Prozesse kompakt darstellen. Sie sollten bewusst eingesetzt werden, ohne den Satz unnötig schwer zu machen.',examples:[{english:'The decline prompted a reassessment.',german:'Der Rückgang führte zu einer Neubewertung.'},{english:'Implementation requires careful coordination.',german:'Die Umsetzung erfordert sorgfältige Koordination.'}],mistake:'Because demand declined made us reassess.',correct:'The decline in demand prompted a reassessment.',promptGerman:'Die unerwartete Verzögerung erforderte eine vollständige Neubewertung.',targetEnglish:'The unexpected delay necessitated a complete reassessment.',gapSentence:'The disruption ___ a review of the strategy.',gapChoices:['necessitated','necessity','necessary to','necessitating to'],gapAnswer:'necessitated'},
  {id:'c2-register',level:'C2',title:'Register Control',subtitle:'Wirkung ans Publikum anpassen',rule:'Auf C2-Niveau wird nicht nur grammatisch korrekt formuliert, sondern Ton, Direktheit, Verdichtung und Wortwahl werden gezielt an Publikum, Zweck und Machtverhältnis angepasst.',examples:[{english:'Proceeding at this stage would be premature.',german:'Ein Fortfahren wäre in diesem Stadium verfrüht.'},{english:'You may wish to reconsider the proposed timeline.',german:'Sie sollten den vorgeschlagenen Zeitplan eventuell überdenken.'}],mistake:'Your plan is bad and too early.',correct:'Proceeding on the current basis would be premature.',promptGerman:'Ein sofortiger Start wäre unter diesen Umständen schwer zu rechtfertigen.',targetEnglish:'An immediate launch would be difficult to justify under these circumstances.',gapSentence:'The current proposal would be difficult to ___.',gapChoices:['justify','justification','justifying to','justified to'],gapAnswer:'justify'}
];

export function grammarTopicsForLevel(level:CefrLevel) {
  return grammarTopics.filter(topic=>topic.level===level);
}

export function grammarTopic(id:string) {
  return grammarTopics.find(topic=>topic.id===id) ?? grammarTopics[0];
}

function rotateTokens(value:string) {
  const tokens=value.replace(/([,.!?;:])/g,' $1 ').replace(/\s+/g,' ').trim().split(' ');
  const cut=Math.max(2,Math.floor(tokens.length/2));
  return [...tokens.slice(cut),...tokens.slice(0,cut)];
}

export function buildGrammarLesson(id:string):Lesson {
  const topic=grammarTopic(id);
  const concepts=[`grammar.${topic.id}`];
  const xp=topic.level==='C2'?18:topic.level==='C1'?15:topic.level==='B2'?13:topic.level==='B1'?10:topic.level==='A2'?8:6;
  const difficulty=topic.level==='A1'?1:topic.level==='A2'?2:topic.level==='B1'?3:topic.level==='B2'?4:5;
  const example=topic.examples[0];
  return {
    id:`practice-grammar-${topic.id}-${Date.now()}`,
    courseId:'de-en',level:topic.level,unitId:'grammar-lab',title:`${topic.level} · ${topic.title}`,subtitle:topic.subtitle,estimatedMinutes:8,newConcepts:[],
    exercises:[
      {id:`${topic.id}-g1`,type:'multiple-choice',instruction:'Wähle die korrekte Form.',prompt:topic.gapSentence,choices:topic.gapChoices,answer:topic.gapAnswer,conceptIds:concepts,difficulty,xp,explanation:topic.rule},
      {id:`${topic.id}-g2`,type:'translation',instruction:'Wende die Regel aktiv an.',prompt:topic.rule,sourceText:topic.promptGerman,acceptedAnswers:[topic.targetEnglish],conceptIds:concepts,difficulty,xp:xp+2,explanation:`Typischer Fehler: ${topic.mistake} → ${topic.correct}`},
      {id:`${topic.id}-g3`,type:'sentence-build',instruction:'Baue den korrekten Zielsatz.',prompt:topic.promptGerman,tokens:rotateTokens(topic.targetEnglish),answer:topic.targetEnglish,conceptIds:concepts,difficulty,xp:xp+2},
      {id:`${topic.id}-g4`,type:'fill-gap',instruction:'Setze die passende Form ein.',prompt:topic.title,sentence:topic.gapSentence,choices:topic.gapChoices,answer:topic.gapAnswer,conceptIds:concepts,difficulty,xp:xp+1},
      {id:`${topic.id}-g5`,type:'listening',instruction:'Höre das Beispiel und ordne die Bedeutung zu.',prompt:topic.subtitle,speech:example.english,choices:[example.german,topic.examples[1]?.german ?? topic.promptGerman,topic.promptGerman,'Die Aussage hat eine andere Bedeutung.'],answer:example.german,conceptIds:concepts,difficulty,xp:xp+2},
      {id:`${topic.id}-g6`,type:'dictation',instruction:'Schreibe das Grammatikbeispiel exakt.',prompt:'Achte besonders auf die Zielstruktur.',speech:topic.targetEnglish,acceptedAnswers:[topic.targetEnglish],conceptIds:concepts,difficulty,xp:xp+3},
      {id:`${topic.id}-g7`,type:'speaking',instruction:'Sprich den Zielsatz laut.',prompt:topic.promptGerman,speech:topic.targetEnglish,acceptedAnswers:[topic.targetEnglish],conceptIds:concepts,difficulty,xp:xp+3},
      {id:`${topic.id}-g8`,type:'multiple-choice',instruction:'Erkenne den typischen Fehler.',prompt:topic.mistake,choices:[topic.correct,topic.mistake,topic.targetEnglish,example.english],answer:topic.correct,conceptIds:concepts,difficulty,xp:xp+2,explanation:topic.rule}
    ]
  };
}
